.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
Closes #
The reminders in the issue template have to be deleted when creating issue and the delete operation is so unnecessary that we just comment them.
Comment the reminders in the issue template.
No.
No need.
=> docs: comment reminders in the issue templates

server/src/limiter.rs
Since we are not mutating the values there is no need to take a `write` lock. Taking a `read` lock is sufficient.
No
Run limiter tests.
=> refactor: Reduce lock exclusivity for read operation

server/src/http.rs
Closes #27  
See issue above.
Add a new HTTP endpoint
```
POST /flush_memtable
```
No
Test manually.
This is what data directory look like after write two rows
```
$ tree         
.               
├── manifest
│   ├── 000003.log
│   ├── CURRENT        
│   ├── IDENTITY      
│   ├── LOCK
│   ├── LOG            
│   ├── MANIFEST-000001
│   └── OPTIONS-000005                                                            
├── store
└── wal
├── 000003.log
├── CURRENT
├── IDENTITY
├── LOCK
├── LOG
├── MANIFEST-000001
└── OPTIONS-000005
```
This is what data directory look like after flush
```
$ tree
.
├── manifest
│   ├── 000003.log
│   ├── CURRENT
│   ├── IDENTITY
│   ├── LOCK
│   ├── LOG
│   ├── MANIFEST-000001
│   └── OPTIONS-000005
├── store
│   ├── 1
│   │   └── 1099511627777
│   │       └── …
```
=> feat: flush memtable HTTP API

.github/workflows/ci.yml, README-CN.md, README.md
Closes #
update readme, add WeChat QR code
no
no need
=> docs: update readme

.dockerignore
Closes #
Directories like docs, target are copied when build docker image, this can be inefficient when those directories contains lots of files.
add ` .dockerignore` file
No
Test manually.
Copy time drop from 400s to 0.4s in my local environment (target dir: 12G).
```
=> [build 4/6] COPY . /ceresdb                                                                                                                                 0.4s
=> [build 5/6] WORKDIR /ceresdb                                                                                                                                0.0s
=> 
```
=> build: add .dockerignore

docs/rfcs/YYYYmmDD-template.md, docs/rfcs/text/YYYYmmDD-template.md
Closes #
Template for our RFC!
Add `docs/rfcs/`, it contains `text/` for rfc markdown and `resource/` for images.
no
no need
=> docs: add RFC template

Cargo.toml, interpreters/Cargo.toml, query_engine/Cargo.toml, server/Cargo.toml, sql/Cargo.toml
Closes #
Forget to reorder workspace dependencies in #40. Sorry for my mistake😢
Reorder workspace dependencies in alphabetical order
No
No
=> build: reorder workspace dependencies

analytic_engine/src/storage_options.rs, docs/example.toml
Closes #
`data_path` config is changed in #20, but `example.toml` still use old format.
No
Test manually.
=> chore: fix storage config

README-CN.md, README.md
Closes #58 
>This kind of information is important for the end-users.
Add `Platform Support` section to readme
no
no need
=> docs: document supported arch

analytic_engine/src/instance/flush_compaction.rs, analytic_engine/src/instance/open.rs, analytic_engine/src/instance/write.rs
Closes #
The memtable may cause oom if it can not be flushed in time when replaying wal.
Flush memtable when replaying wal.
None.
Test manually.
=> feat: flush memtable in time when replay wal

server/src/mysql/worker.rs
Closes #
Change ErrorKind to not supported.
No
No need.
=> chore: more accurate error kind

analytic_engine/src/table/mod.rs, analytic_engine/src/tests/alter_test.rs, analytic_engine/src/tests/drop_test.rs, interpreters/src/create.rs, interpreters/src/drop.rs, interpreters/src/tests.rs, sql/src/planner.rs, table_engine/src/memory.rs, table_engine/src/table.rs
=> fix: affected rows for create/drop statements default 0

README-CN.md, README.md
Signed-off-by: WeiZhang <kweizh@gmail.com>
Closes #139
replace dead link to slack with a valid one
no
N/A
=> docs: :hammer: fix slack dead link

docs/user-guide/src/deploy/README.md, docs/user-guide/src/deploy/static_routing.md
Close #
Users may want to deploy CeresDB as a cluster but now there is no such a guide to explain how to create CeresDB cluster.
Provide a guide for how to create static, rule-based routing deployment of CeresDB.
=> docs: user guide about static routing

.github/workflows/dockerhub-description.yml, .github/workflows/dockerhub-publish.yml, docs/dockerhub-description.md
Closes #126 
After #121, we can publish image to docker hub, but with empty description, this PR fix this problem.
- Add a new workflow to update docker hub description when `dockerhub-description.md`/`dockerhub-description.yml` is updated in `main`
- Rename docker.yml to `dockerhub-publish.yml` to keep naming consistent.
No
Not yet, it need to be merge into main to test.
=> chore: add docker hub description workflow

README.md
- "Clone this repository by 'git' and enter it" -> Clone this repository using 'git' and enter it
- "including 'Rust' toolchain -> including the 'Rust' toolchain
- "the compilation of the project actually has version requirements for some dependencies" -> the compilation of the project has version requirements for dependencies
=> Minor Grammar and Concision Changes in README.md

.github/workflows/user_guide.yml
Closes #
User guide of HTML version is supported by mdbook, and it's more readable than md version.
Add a new workflow to automate the HTML generation process.
No
Tested in my forked repo:
- https://github.com/jiacai2050/ceresdb/actions/runs/2729841600
=> docs: add user guide workflow to generate html pages

.github/workflows/dockerhub-publish.yml
Signed-off-by: WeiZhang <kweizh@gmail.com>
N/A
1. always run docker build
2. not push image on forks
3. only push image on tag with `v` prefix
No
Run Github workflow
=> build(ci): :hammer: not run the build and push CI on forks

docs/dev/roadmap-CN.md, docs/dev/roadmap.md
Closes #170
A new version (`v0.2.0`) has been released for a while. And the detailed milestone is also changed. 
Update roadmap
=> docs: update Roadmap.md

Cargo.lock, benchmarks/Cargo.toml, benchmarks/bench.toml, benchmarks/benches/bench.rs, benchmarks/config/bench.toml, benchmarks/src/config.rs, benchmarks/src/lib.rs, benchmarks/src/util.rs, benchmarks/src/wal_write_bench.rs
Part of #162
To compare performance between `dyn Payload` and `pre-code` in wal write, we need a benchmark.
Add benchmark of wal write.
No
Nonthing chenged.
=> feat: add wal write benchmark

.github/workflows/ci.yml
Closes #52
Supersede #204 , to check if Cargo.lock has been changed all by ourselves, without any other dependencies.
No
Testing with those command
```bash
cp ${LOCK_FILE} ${LOCK_FILE}.bak
git clone https://github.com/apache/parquet-testing.git components/parquet-testing
make test-ut
echo "# test" >> ${LOCK_FILE}
diff ${LOCK_FILE} ${LOCK_FILE}.bak
```
It will fail https://github.com/jiacai2050/ceresdb/runs/8065062616?check_suite_focus=true
=> chore: check Cargo.lock in CI

docs/guides/src/analytic_engine/README.md, docs/guides/src/analytic_engine/options.md
Part of https://github.com/CeresDB/ceresdb/issues/77#issuecomment-1217376966
The hybrid format has been merged in main, but no docs.
improve options section
Yes, all users can refer this doc to create hybrid table.
`mdbook serve` locally to check page style is fine.
=> docs: improve options section

configs/minimal.toml, docs/example.toml, docs/guides/src/dev/compile_run.md
Closes #
Local is useful to test locally
Start server locally with minimal.toml
=> chore: add minimal config

docker/entrypoint.sh
Close #229 
Fix running docker bug, refer to #229 .
=> fix(docker): remove configuration overridden by env

.dockerignore, .github/workflows/ci.yml, .github/workflows/docker-build-image.yml, .github/workflows/dockerhub-description.yml, .github/workflows/dockerhub-publish.yml, docker/basic.sh, docs/dockerhub-description.md, docs/minimal.toml
Fix
- https://github.com/CeresDB/ceresdb/actions/runs/2968788373
- https://github.com/CeresDB/ceresdb/runs/8127447581?check_suite_focus=true
CI
=> chore: fix image build

analytic_engine/src/compaction/picker.rs, analytic_engine/src/instance/flush_compaction.rs, analytic_engine/src/sst/file.rs, analytic_engine/src/sst/parquet/builder.rs, analytic_engine/src/sst/parquet/encoding.rs, analytic_engine/src/sst/parquet/reader.rs, analytic_engine/src/table/version_edit.rs, analytic_engine/src/table_options.rs, proto/protos/analytic_common.proto, proto/protos/sst.proto
Closes #
Refer to #227 
Persist collapsible info in metadata of parquet.
No.
Modify `hybrid_record_encode_and_decode` test to test it.
=> feat: persist collapsible info in parquet meta_data

docs/guides/src/dev/compile_run.md
Closes #
`Configs` dir removed, update the `Compile and run` chapter to ensure run ceresdb correctly.
Update the `Compile and run` chapter to ensure run ceresdb correctly.
No.
No.
=> docs: update complie and run chapter

Cargo.lock, Cargo.toml, catalog_impls/src/volatile.rs, cluster/src/cluster_impl.rs, cluster/src/lib.rs, meta_client/src/lib.rs, meta_client/src/meta_impl.rs, meta_client/src/types.rs, server/src/route/cluster_based.rs
Part of #235
The latest ceresdbproto has been updated, and adapt ceresdb-server to it for following work.
- Adapt to latest ceresdbproto.
None.
No need.
=> chore: adapt to latest ceresdbproto

analytic_engine/src/compaction/scheduler.rs, analytic_engine/src/instance/flush_compaction.rs, analytic_engine/src/table/data.rs, analytic_engine/src/table/mod.rs, common_util/src/time.rs
Closes #
Support flush tables that have not been flushed for a long time.
=> feat: support flush tables periodically

catalog_impls/src/volatile.rs, cluster/src/cluster_impl.rs, cluster/src/lib.rs, cluster/src/shard_table_manager.rs, cluster/src/shard_tables_cache.rs, server/src/grpc/mod.rs, src/setup.rs
Part of #235 
Implemenat the logic for close/open shards.
Support close/open shards.
None.
No test for this, and this will be tested with meta by manual.
=> feat: support open&close shards

Cargo.lock, Cargo.toml, analytic_engine/src/instance/write.rs, analytic_engine/src/meta/meta_update.rs, analytic_engine/src/sst/file.rs, analytic_engine/src/table/version_edit.rs, common_types/Cargo.toml, common_types/src/schema.rs, interpreters/Cargo.toml, interpreters/src/context.rs, interpreters/src/table_manipulator/meta_based.rs, interpreters/src/table_manipulator/mod.rs, meta_client/src/lib.rs, meta_client/src/meta_impl.rs, meta_client/src/types.rs
Part of #235 
Do real job of creating/dropping table by meta client.
NOTE: This pr is blocked by https://github.com/CeresDB/ceresdbproto/pull/27.
- Add encoding for schema;
- Send creating/dropping table request to ceresmeta;
None.
- Add a new UT for schema encoding.
- Creating/Dropping table by ceresmeta will be tested by manual.
=> feat: do create drop table

cluster/src/cluster_impl.rs, cluster/src/shard_tables_cache.rs
Closes #
For now, opening a shard is not idempotent, which is not expected by CeresMeta.
- Make opening a shard idempotent.
None.
Tested with CeresMeta.
=> fix: make open shard idempotent

Cargo.lock, benchmarks/Cargo.toml, benchmarks/README.md, benchmarks/benches/bench.rs, benchmarks/config/bench.toml, benchmarks/src/bin/parquet-reader.rs, benchmarks/src/config.rs, benchmarks/src/parquet_bench.rs
Closes #
Perf is always good, add a new bench case for async reader.
Bench https://docs.rs/parquet/latest/parquet/arrow/async_reader/index.html
No
Not required
=> feat: add async parquet reader bench

Cargo.toml, sql/src/planner.rs
Closes #
When building docker image for releasing v0.4.0, the high memory consumption leads to the building failure.
- Bump the version to v0.4.0;
- Adjust the building profile for release.
No.
No need to test.
=> chore: bump the version and adjust the building profile

.github/workflows/ci.yml, Cargo.lock, analytic_engine/src/instance/drop.rs, analytic_engine/src/instance/flush_compaction.rs, analytic_engine/src/instance/write.rs, analytic_engine/src/instance/write_worker.rs, sql/src/promql/convert.rs, sql/src/provider.rs
Closes #
The error message is not readable when table is not found.
- Refactor the message for table is not found.
The error message will be different.
By the harness test.
=> chore: fix error message when table is not found

Cargo.lock, wal/Cargo.toml, wal/src/lib.rs, wal/src/message_queue_impl/mod.rs, wal/src/message_queue_impl/region_meta.rs
Part of #284 
See  #284.
+ The record format used in wal on message queue.
+ The region meta module.
None.
Will add test later.
=> feat:  region meta in wal manager on kafka

docs/guides/src/dev/roadmap.md
None
The roadmap of this project is out of date. So we should discuss on it and let the community be consensus of what we are going to do.
The roadmap doc.
Community members and potential users may be confused about the project's future.
No need.
=> docs: proposal of roadmap

Cargo.lock, proto/build.rs, proto/protos/wal.proto, proto/protos/wal_on_mq.proto, proto/src/lib.rs, wal/Cargo.toml, wal/src/kv_encoder.rs, wal/src/message_queue_impl/encoding.rs, wal/src/message_queue_impl/mod.rs, wal/src/message_queue_impl/region_meta.rs
Part of #284 
see #284  
+ Add common log key and value for all wal implementations to use.
+ Add message queue's meta key and value.
None.
Test by ut.
=> feat: encoding in wal's message queue impl.

components/message_queue/src/kafka/kafka_impl.rs, components/message_queue/src/lib.rs, components/message_queue/src/tests/cases.rs, wal/src/message_queue_impl/log_cleaner.rs, wal/src/message_queue_impl/snapshot_synchronizer.rs
Close #366 
Enhancement to mq's kafka implementation.
+ add some useful traits.
+ add a test about multiple consumers on a same topic.
+ rename `delete_up_to` to `delete_to`.
None.
Test by ut.
=> feat: enhancement to mq's kafka implementation

components/parquet_ext/src/prune/equal.rs
Part of #363 
Prepare for bloom filter pruning.
- Support filter row groups with `EqPrunner`;
None.
New UT.
=> feat: support filter_row_groups by EqPruner

wal/src/message_queue_impl/region.rs, wal/src/message_queue_impl/region_meta.rs, wal/src/message_queue_impl/test_util.rs
Closes #384
+ see #384.
Implement region's recovery.
None.
Test by ut.
=> feat: implement region recovery

tools/src/bin/sst-convert.rs
Closes #
`sst-convert` support hybrid storage format
- Compression default to zstd
- Add a `-f` option to set format
No
Manullay
=> feat: sst-convert support convert to hybrid format

components/table_kv/Cargo.toml
Closes #
To fix bug mentioned in https://github.com/oceanbase/obkv-table-client-rs/pull/5.
No.
=> chore: update obkv-client to latest version

Cargo.lock, Cargo.toml
Closes #
Prepare for remove manual installation of protoc in the ci workflow.
Update the version of ceresdbproto.
None.
Existing unit test.
=> chore: update the ceresdbproto to latest

Cargo.lock, tests/harness/Cargo.toml, tests/harness/src/case.rs, tests/harness/src/runner.rs, tests/harness/src/setup.rs
Replace #388
Upgrade ceresdb-client to latest version in harness.
No
Test harness itself.
=> chore: bump client in test harness

docs/guides/src/quick_start.md
Closes #
It's awkward to wrap SQL in JSON, so server accept plain text request in #287 but not docs 
Update quick start section.
No
Manually
=> docs: update http api

wal/Cargo.toml, wal/src/manager.rs, wal/src/message_queue_impl/config.rs, wal/src/message_queue_impl/mod.rs, wal/src/message_queue_impl/namespace.rs, wal/src/message_queue_impl/region.rs, wal/src/message_queue_impl/region_context.rs, wal/src/message_queue_impl/snapshot_synchronizer.rs, wal/src/message_queue_impl/wal.rs, wal/src/table_kv_impl/mod.rs, wal/src/tests/read_write.rs, wal/src/tests/util.rs
Closes #371 
See #371 .
+ implement `Namespace` of wal on mq.
+ implement the `WalManager` interface for it.
You can start ceresDB with wal on kafka now!
Test by ut.
=> feat: Impl wal on mq namespace

wal/src/table_kv_impl/namespace.rs
Closes #
There are cleaner bugs in wal on obkv.
Fix the cleaner bugs in wal on obkv.
None.
Test manually.
=> fix: cleaner bugs of wal on obkv

analytic_engine/src/instance/open.rs, analytic_engine/src/table/data.rs, analytic_engine/src/table/version.rs
Closes #282 
See #282 .
See #282 .
None.
Test by existing ut.
=> feat: replay from flushed sequence

server/src/grpc/storage_service/mod.rs
Closes #
The grpc service executing time duration metric is incorrectly.
Fix grpc service executing time duration metric.
No.
No need.
=> fix: fix grpc service metrics

wal/src/table_kv_impl/namespace.rs
Closes #
A infinite loop bug [pr 418](https://github.com/CeresDB/ceresdb/pull/418).
Fix bug above.
None.
Test manually.
=> fix: purging buckets in initializing bug

Cargo.lock, components/object_store/Cargo.toml, components/object_store/src/disk_cache.rs
Closes #
Followup PR of #420, add CRC for cached bytes
No
UT
=> feat: add disk cache value crc

.github/workflows/ci.yml, .github/workflows/dockerhub-description.yml
Closes #
Modify some config in workflows.
* Remove `.github/*` in CI ignore path.
* `workflows/dockerhub-description` run on the workflow_dispatch event.
No.
No need.
=> chore: modify some config in workflows

Cargo.lock, components/object_store/Cargo.toml, meta_client/Cargo.toml
Closes #
Reuse http client for oss sdk,
- https://github.com/jiacai2050/oss-rust-sdk/commit/a6c54471d0b187667395d6cac931bd4e01a9f4e4
=> chore: bump oss sdk

table_engine/src/partition/rule.rs, table_engine/src/partition/rule/mock.rs, table_engine/src/partition/rule/mod.rs
Closes #
Part of #492 
See #492 .
Define the trait for other modules' later development.
+ define partition trait.
None.
Not need temporarily.
=> feat: define partition rule trait

server/src/config.rs, server/src/grpc/forward.rs, server/src/grpc/mod.rs, server/src/grpc/storage_service/mod.rs, server/src/grpc/storage_service/query.rs, server/src/server.rs
Part of #147 
Check #147 
- Add `forward` module to do traffic auto redirecting for grpc query;
Support forward config.
New unit test.
=> feat: auto forward query for grpc

server/src/grpc/remote_engine_service/mod.rs
Closes #
When insert into a partition table, the affected_rows result is wrong.
* Fix affected_rows.
No.
=> fix: fix partition table affected_rows

.pre-commit-config.yaml, scripts/license-header.txt
Closes #
There are some convention in our coding rules, it's annoying to manually fix them.
So PR add git commit hooks to automatically fix them.
Add pre-commit config, it will
- Ensure validation of toml/yaml files
- Ensure Cargo.toml is sorted, depend on https://github.com/DevinR528/cargo-sort
- Ensure license header
Developers can install those hooks via
```
pre-commit install
```
This command only need to execute once, it will work when `git commit` next time.
Manually
=> feat: add pre commit hooks

analytic_engine/src/sst/file.rs
Closes #
After rebase main branch, the `breaking-changes` is broken.
Fix the issues caused by rebasing.
None.
Existing test.
=> fix: remove extra params

docs/guides/src/deploy/static_routing.md
Closes #
There are some bugs in the example config in the deployment doc.
Fix the wrong config in the deployment doc.
None.
No need.
=> docs: wrong schema in the static routing example config

docs/example-cluster-0.toml, docs/example-cluster-1.toml, docs/guides/src/deploy/dynamic_routing.md
Closes #
Update `meta addr` in example-cluster config for better deployment.
* Update `meta addr` in example-cluster config for better deployment.
* Update `dynamic_routing` doc.
No.
No need.
=> docs: update example cluster config

.github/actions-rs/gcrov.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml
Closes #425 
Add `codecov` to show test coverage report.
* Add coverage github workflow.
* Use [llvm-cov](https://github.com/taiki-e/cargo-llvm-cov) for code coverage .
No.
No need.
=> chore: add llvm cov codecov

.github/workflows/docker-build-image.yml, .github/workflows/dockerhub-publish-nightly.yml, .github/workflows/dockerhub-publish.yml, .github/workflows/tsbs.yml, Dockerfile, scripts/run-tsbs.sh
Closes #
Protobuf is required in CI.
CI itself.
=> chore: fix missing deps in CI

.github/workflows/tsbs.yml, Cargo.toml, Dockerfile, scripts/run-tsbs.sh
Closes #
When lto is true, release build would fail on machine with 16G(9G free), so remove it.
=> chore: remove lto

CONTRIBUTING.md, Cargo.lock, common_types/src/schema.rs, integration_tests/Cargo.toml, integration_tests/README.md, integration_tests/cases/local/05_ddl/create_tables.result, integration_tests/cases/local/05_ddl/create_tables.sql, integration_tests/cases/local/config.toml
Closes #
Ensure timestamp is in primary key
- Bump sqlness to https://github.com/CeresDB/sqlness/releases/tag/v0.3.0
- Add tests for missing timestamp in primary key
No
New integration_tests
=> test: add testcase for timestamp not in primary key

integration_tests/cases/local/03_dml/issue-302.result, integration_tests/cases/local/03_dml/issue-302.sql
Closes #302 
Add test in integration_test to cover #302 .
Add test `issue-302` in `integration_test`.
No.
=> test: add test for issue 302

.github/workflows/ci.yml
Closes #
To make CI run faster
- style-check, unit test, integration test have no relation, which means they can run in parallel.
No
CI itself.
- https://github.com/CeresDB/ceresdb/actions/runs/4135058171
=> chore: run ci in parallel

src/setup.rs
Closes #364 
Implement system table in cluster mode. 
* Add catalog manager proxy when create meta based catalog manager.
System table query cloud be used in cluster mode like this:
```
curl --location --request POST 'http://127.0.0.1:5440/sql' \
--header 'Content-Type: application/json' \
-d'{
"query": "select * from system.public.tables"
}'
{"rows":[{"timestamp":0,"catalog":"ceresdb","schema":"public","table_name":"demo","table_id":0,"engine":"Analytic"}]}%
```
Verify in local environment.
=> feat: add cluster mode system table

wal/src/message_queue_impl/region_context.rs
Closes #
Now I assume that in recovery, no flush of specific table will be triggered on the sequence which is not the marked deleted one among the meta snapshot. So mapping between sequence and kafka offset is not stored in the meta snapshot.
However, this assumption is unreasonable. Fortunately, it is easy to process this situation by just not updating the marked deleted sequence in this flush.
Allow the mapping above incomplete.
None.
Test by ut.
=> feat: allow mapping between sequence and kafka offset incomplete

.github/workflows/ci.yml
Closes #
Fix upload log file bug in CI. Now trigger the CI multiple times and the file will be overwritten..
* Add the suffix of the uploaded file
None.
Test in my fork  repository.
=> chore: fix CI upload log

README-CN.md, README.md
Closes #
remove status in readme
remove status in readme
None
=> feat: remove status in readme

Cargo.lock, Cargo.toml, common_util/src/runtime/mod.rs, src/bin/ceresdb-server.rs
Closes #
Add rustc version in version info
- Rename  `CSE_CERES_META_NODE_ADDR` to  `CERESDB_SERVER_ADDR`
- Add rustc version
No
No need
=> chore: add rustc version

Cargo.lock, Cargo.toml, integration_tests/Cargo.toml, integration_tests/src/database.rs, router/src/cluster_based.rs, router/src/rule_based.rs, server/src/grpc/forward.rs
Closes #
- Bump ceresdb-client to 1.0
- Bump sqlness to 0.4
No
CI
=> chore: bump client

components/logger/src/lib.rs, server/src/http.rs
Closes #
- Log level change to info
No
CI
=> chore: update log level

cluster/src/config.rs, server/src/config.rs, server/src/grpc/storage_service/mod.rs, server/src/grpc/storage_service/write.rs
Closes #
Auto create table is an important feature, so we decide to support this always. 
- Remove `auto_create_tables` options
CI
=> fix: remove auto create table option

README-CN.md, README.md
=> chore: update readme

Cargo.lock, Cargo.toml
=> chore: release 1.0.0

.github/workflows/dockerhub-publish-nightly.yml
Closes #
Fix https://github.com/CeresDB/ceresdb/actions/runs/4312100528
See: https://github.com/orgs/community/discussions/27086
No
https://github.com/CeresDB/ceresdb/actions/runs/4314472017/jobs/7527551391.
It will publish to image here: https://github.com/CeresDB/ceresdb/pkgs/container/ceresdb-server
=> chore: image name must be lowercase

README-CN.md, README.md
=> docs: change the description of qr-code

server/src/grpc/storage/mod.rs, server/src/grpc/storage/query.rs, server/src/proxy/forward.rs, server/src/proxy/grpc/mod.rs, server/src/proxy/grpc/sql_query.rs, server/src/proxy/mod.rs
Closes #
Impl query with proxy. Refer to #681 .
* Impl query with proxy. 
* Support forwarding query.
=> feat: impl query with proxy

README-CN.md, README.md
None.
Replace wechat official account qr-code.
No need.
=> docs: replace qr-code

server/src/grpc/storage/mod.rs, server/src/proxy/grpc/mod.rs, server/src/proxy/grpc/prom_query.rs, server/src/proxy/grpc/sql_query.rs, server/src/proxy/grpc/write.rs
Closes #
Impl prom query with proxy.
* Impl prom query with proxy.
* Refactor some code in write and sql query.
=> Feat proxy prom query

.github/ISSUE_TEMPLATE/bug_report.yml
Closes #
Version are important to reproduce bug.
=> chore: update issue template

server/src/grpc/storage/mod.rs, server/src/proxy/grpc/sql_query.rs, server/src/proxy/mod.rs
Closes #
Impl stream query with proxy.
* Impl stream query with proxy.
* Support forwarding stream query.
No.
Integration test.
=> feat: impl stream query with proxy

integration_tests/cases/env/local/influxql/basic.result, integration_tests/cases/env/local/influxql/basic.sql, integration_tests/src/database.rs
Closes #
Add tests for #783.
- Add integration tests for get request
No
CI
=> feat: add integration tests for influxql request

Cargo.lock, Cargo.toml
Closes #
1.1.0 is ready for release 🚀
Bump version
No
No need.
=> chore: bump version to 1.1.0

Cargo.lock, server/Cargo.toml, server/src/http.rs
Closes #
CPU profiler is useful to debug bottleneck.
Add `/debug/cpu_profile/{seconds}` in http 
No
Manually
=> feat: add cpu profiler

.github/workflows/dockerhub-publish-nightly.yml
Closes #
Add commit id of nightly docker image.
Add commit id of nightly docker image.
No.
No need.
=> chore: add commit id of nightly docker image

analytic_engine/src/table/metrics.rs
Closes #819
Write batch size is important for write throughput.
Add histgram metrics for write batch
No
No need
=> chore: add write batch metrics

partition_table_engine/src/partition.rs, server/src/proxy/grpc/sql_query.rs, server/src/proxy/grpc/write.rs, server/src/proxy/mod.rs, server/src/proxy/util.rs
Closes #
Support write partition table in grpc service.
* Open partition table in proxy when write it.
No.
=> feat: support write partition table in grpc service

server/src/proxy/forward.rs
Closes #
Cleanup forward config
Forwarded timeout is None by default
No
CI
=> chore: clean forward configs

server/src/proxy/http/prom.rs
Closes #836
- When tag value is null, return empty string instead.
No
Manually
=> fix: avoid panic when convert prom result

analytic_engine/src/sst/parquet/writer.rs
Closes #
An obvious bug when init filter
No
=> fix: build filter when needed

server/src/context.rs, server/src/grpc/storage_service/mod.rs, server/src/http.rs, server/src/mysql/service.rs, server/src/mysql/worker.rs, server/src/proxy/http/prom.rs
Closes #
RequestContext should only contains request-level variable, such as tenant/database.
Remove runtime from request context
No
CI
=> refactor: remove runtime from request context

.github/workflows/ci.yml, integration_tests/Makefile, integration_tests/prom/prometheus.yml, integration_tests/prom/remote-query.py, integration_tests/prom/run-tests.sh
Closes #
Currently there are no integration tests for prometheus remote query.
- Add basic query tests
No
CI
=> test: add prometheus integration tests

.github/workflows/ci.yml, Cargo.lock, Makefile, server/Cargo.toml
Closes #
Add some commands in Makefile.
* Add `install-udeps`.
* Add `install-cargo-sort`.
* Add `udeps`.
* Add `pre-commit` in `dev-setup`.
No.
CI.
=> chore: add some commands in Makefile

wal/src/table_kv_impl/encoding.rs, wal/src/table_kv_impl/namespace.rs
=> Revert "chore!: rename table name in table_kv based wal"

Cargo.lock, Cargo.toml, docs/example-cluster-0.toml, docs/example-cluster-1.toml, integration_tests/config/ceresdb-cluster-0.toml, integration_tests/config/ceresdb-cluster-1.toml
Closes #
Bump the version to 1.2.0
Bump the version to 1.2.0
None.
CI.
=> chore: bump the version to 1.2.0 and update the config example

Cargo.lock, Cargo.toml
Closes #781
- https://github.com/jiacai2050/prom-remote-api/pull/2
No
CI and manually
=> fix: snappy decode error for prom remote write

server/src/http.rs, server/src/metrics.rs
Closes #
Currently there are no metrics for http handler.
Add http handle metrics
No
Manually
=> feat: add metrics for http requests

Cargo.lock, Makefile, components/tracing_util/Cargo.toml, components/tracing_util/src/logging.rs, src/setup.rs
Closes #
+ Add console subcriber to tracing.
+ Add related configs to decide whether open with tokio console server.
+ Modify makefile to support build with unstable tokio.
Test manually.
=> feat: support tokio console for debugging

analytic_engine/src/sst/parquet/mod.rs, proxy/src/grpc/mod.rs, proxy/src/handlers/mod.rs, proxy/src/lib.rs, query_frontend/src/lib.rs, server/src/grpc/meta_event_service/mod.rs, server/src/grpc/mod.rs, server/src/grpc/remote_engine_service/mod.rs, server/src/grpc/storage_service/mod.rs, server/src/lib.rs, table_engine/src/partition/rule/df_adapter/mod.rs, table_engine/src/partition/rule/mod.rs
Closes #
Remove useless `pub(crate)`.
* Remove useless `pub(crate)`.
* Remove useless `#[allow(dead_code)]`.
No.
CI.
=> chore: remove useless code

Cargo.lock, Cargo.toml
Closes #
Bump the version to 1.2.2
No need to test.
=> chore: bump the version to 1.2.2

Cargo.lock, proxy/Cargo.toml, proxy/src/grpc/metrics.rs, proxy/src/grpc/mod.rs, proxy/src/grpc/write.rs, server/src/grpc/metrics.rs, server/src/grpc/remote_engine_service/mod.rs, server/src/grpc/storage_service/mod.rs
add grpc write failed counter metric
- add counter metric in grpc proxy
- add counter metric in grpc remote engine service
Existing tests
=> refactor: add grpc write failed counter metric

Cargo.lock, Cargo.toml, analytic_engine/src/sst/parquet/meta_data.rs
Related with #967, reduce CPU consumption.
- https://github.com/CeresDB/xorfilter/pull/1
- https://github.com/CeresDB/xorfilter/pull/2
@zouxiang1993 will benchmark this in his test env.
=> chore: bump xor8

analytic_engine/src/instance/wal_replayer.rs, wal/src/message_queue_impl/region.rs
Part of #799 
see title.
None.
=> chore: add logs and metric to recovery

table_engine/src/predicate.rs
add testcases for time range Predicate
ut.
=> chore: add testcases for time range predicate

Cargo.lock, benchmarks/Cargo.toml, components/profile/Cargo.toml
maybe close #1008
Updated version due to bugs in upstream `findshlibs`
manual
=> fix: update pprof version

Cargo.toml, benchmarks/Cargo.toml, components/profile/Cargo.toml
`pprof` in toml use workspace
`pprof` in toml use workspace
CI
=> refactor: pprof in toml use workspace

Cargo.lock, Cargo.toml
=> chore: bump pprof version

analytic_engine/src/row_iter/chain.rs
Now, no actual scan duration stats in chain iterator, and I think it important.
Add actual scan duration stats into chain iterator.
Test manually.
=> chore: add actual scan duration stats into chain iterator

analytic_engine/src/compaction/scheduler.rs
See title
- Remove ! in logic of keep scheduling compaction
- Existing tests
- mannually tests
=> fix: logic of keep scheduling compaction

Cargo.lock, components/table_kv/Cargo.toml, components/table_kv/src/lib.rs, components/table_kv/src/metrics.rs, components/table_kv/src/obkv.rs
In one of our deployment,  we see lots of obkv timeout requests, so we need to add some metrics for trouble shooting.
Add metrics for different obkv operations.
=> feat: add obkv operation metrics

proxy/src/http/sql.rs
Check response header when query failed in proxy.
=> chore: check response header when query failed in proxy

Cargo.lock, proxy/src/hotspot.rs, proxy/src/lib.rs, remote_engine_client/Cargo.toml, remote_engine_client/src/lib.rs, server/src/server.rs
Currently hotspot will not records remote engine requests 
Add hotspot for remote engine
No need
=> feat: hotspot record remote engine requests

Cargo.lock, Cargo.toml
See https://github.com/CeresDB/arrow-datafusion/commit/9c3a537e25e5ab3299922864034f67fb2f79805d
Existing UT
=> chore: bump datafusion

.github/workflows/ci.yml, .github/workflows/dockerhub-publish.yml
See https://github.com/CeresDB/ceresdb/pull/1135#issuecomment-1666687504
=> chore: don't trigger image build via tag push

Cargo.lock, components/table_kv/Cargo.toml
See https://github.com/oceanbase/obkv-table-client-rs/pull/74
=> chore: bump obkv

README.md
=> chore: modified `Acknowledgements`

README-CN.md
=> chore: modified README-CN's Acknowledgements

proxy/src/read.rs
Panics when failed to dedupping query.
Send the error to the waiters rather than exiting directly.
Manual tests.
=> fix: panic if dedupped query fails

README-CN.md, README.md
=> chore: add wechat group qrcode

Cargo.lock, Cargo.toml, analytic_engine/Cargo.toml, analytic_engine/src/instance/engine.rs, analytic_engine/src/instance/mem_collector.rs, analytic_engine/src/instance/mod.rs, analytic_engine/src/instance/open.rs, analytic_engine/src/lib.rs, analytic_engine/src/manifest/details.rs, analytic_engine/src/space.rs, analytic_engine/src/table/data.rs, analytic_engine/src/table/version.rs, analytic_engine/src/table_meta_set_impl.rs, components/sampling_cache/Cargo.toml, components/sampling_cache/src/lib.rs, proxy/src/read.rs
If there are massive tables, the check for total memory usage costs a lot of cpu resources.
Introduce a sampling mechanism to avoid frequent memory usage check.
All the tests in the ci should pass.
=> feat: cache space total memory

integration_tests/Makefile, integration_tests/build_meta.sh
This refers to https://github.com/CeresDB/ceresmeta/pull/265.
=> test: simplify ceresmeta-server installation

.github/ISSUE_TEMPLATE/config.yml
The blank issue is disabled and issue in a different format can't be submit.
Enable the blank issue.
No need.
=> chore: enable blank issue

analytic_engine/src/tests/read_write_test.rs
=> fix: increase wait duration for flush

integration_tests/cases/env/cluster/ddl/create_tables.result
=> fix: fix test create table result

integration_tests/cases/env/local/ddl/query-plan.result, server/src/http.rs, table_engine/src/provider.rs
=> chore: disable timeout for http api

.asf.yaml
@dfoulks1 This should need a force merge because we don't have a "Required" status ..
=> ci: remove missing Required status

README-CN.md
=> chore: git repo link type fix

integration_tests/sdk/go/alteraddcolumn.go, integration_tests/sdk/go/autocreatetable.go, integration_tests/sdk/go/go.mod, integration_tests/sdk/go/issue-779.go, integration_tests/sdk/go/main.go, integration_tests/sdk/go/util.go, integration_tests/sdk/java/pom.xml
=> chore: more rename to horaedb

analytic_engine/src/instance/open.rs
Reduce two `match`to only one.
CI
=> chore: refactor for better readability

server/src/grpc/remote_engine_service/mod.rs
Currently there are no error log for remote server, this make it's hard to debug.
No need.
=> chore: add error log for remote server

df_engine_extensions/src/dist_sql_query/physical_plan.rs, integration_tests/cases/env/cluster/ddl/partition_table.result, integration_tests/cases/env/cluster/ddl/partition_table.sql
See #1405
Disable percentile functions
CI
=> fix: disable percentile for distributed tables

.asf.yaml, CONTRIBUTING.md, README-CN.md, README.md, docs/dockerhub-description.md
=> chore: update website url

README-CN.md, README.md
Fix logo link in readme.
No need.
=> chore: fix logo link in readme

.asf.yaml
=> chore: update github pages

.asf.yaml
Remove github pages in asf.yaml.
No need.
=> chore: remove github pages in asf.yaml

README-CN.md
The link for the issue status of README-CN.md is broken.
Update the link.
Looks right.
=> chore: fix issue status of README-CN.md

Cargo.lock, Cargo.toml
Update version to 2.0.0, prepare for releasing v2.0.0.
=> chore: update version to 2.0.0, prepare for releasing v2.0.0

src/analytic_engine/src/tests/read_write_test.rs, src/horaedb/src/setup.rs
=> chore: rename more ceresdb to horaedb

.github/pr-title-checker-config.json, .github/workflows/check-pr-title.yml
Check whether the PR title is valid.
Valid PR title start with: `feat|fix|refactor|chore|docs`
Manual test.
=> chore: add check-pr-title action

.github/workflows/auto-label-pr.yml
Automatically label the pr based on the pr title.
Automatically label the pr based on the pr title.
Manual test.
=> chore: add auto-label-pr action

horaemeta/README.md
I noticed that the previous repository has been archived, maybe it would be better to update the new link
=> chore: update link

horaemeta/CONTRIBUTING.md
=> chore(horaemeta): add building docs

Cargo.lock, Cargo.toml, src/wal/src/local_storage_impl/config.rs, src/wal/src/local_storage_impl/segment.rs, src/wal/src/local_storage_impl/wal_manager.rs
- Bump version
- Update WAL segment file convention to `seg_{id}`
CI
=> chore: bump version 2.1.0

.github/workflows/ci.yml, Makefile, horaemeta/go.mod, integration_tests/sdk/go/go.mod, licenserc.toml
Those files should contain asf headers.
CI
=> chore: fix license header

.github/workflows/links.yml, CONTRIBUTING.md, README-CN.md, README.md, docs/rfcs/20220702-prometheus-read-extension.md, horaemeta/CONTRIBUTING.md
Sync with website
- Add URL check ci
CI
=> chore: update community

LICENSE, NOTICE
See https://lists.apache.org/thread/29nyod5d73tn5nov7f5pm0tg42gq57vw
Adhere to https://www.apache.org/legal/src-headers.html
No need.
=> chore: fix LICENSE and NOTICE

.github/workflows/publish-image.yml
Close #1589 
Upgrade `publish-image.yml` for skip build latest docker tag for RC version.
pass
=> fix: skip build latest docker tag for RC version.

src/components/object_store/src/aliyun.rs
Avoid splicing bucket multiple times in oss url
CI
=> fix:  avoid splicing bucket multiple times in oss url

Cargo.lock, Cargo.toml, Makefile, src/metric_engine/Cargo.toml, src/metric_engine/src/compaction/mod.rs, src/metric_engine/src/compaction/runner.rs, src/metric_engine/src/compaction/scheduler.rs, src/metric_engine/src/manifest.rs, src/metric_engine/src/read.rs, src/metric_engine/src/storage.rs, src/metric_engine/src/types.rs
Compaction runner is responsible for compact old sst & delete expired sst.
CI
=> feat: add compaction runner

.github/workflows/ci.yml, src/metric_engine/src/manifest/encoding.rs
=> refactor: use `Read` trait to convert Bytes to Snapshot

Cargo.lock, src/metric_engine/src/compaction/scheduler.rs, src/metric_engine/src/storage.rs, src/server/Cargo.toml, src/server/src/main.rs
In order to test `TimeMergeStorage`, I plan to generate random arrow data and trigger compaction via http API
Not required.
=> feat: add demo server for benchmark

Cargo.lock, Cargo.toml, src/metric_engine/Cargo.toml, src/metric_engine/src/metric/mod.rs, src/metric_engine/src/types.rs
=> feat: init metric manager
