- Cargo.lock
- wal/Cargo.toml
Closes #34 
We are using an outdated branch (`tikv-5.2`, which is updated around 7 months ago) of `rust-rocksdb`. It brings lots of compile errors either in upgrading other dependencies #26 or in new toolchains #34.
Switch to the master branch.
no
No?
> chore(deps): switch to rust-rocksdb master branch

- server/src/limiter.rs
This MR simplifies the `Plan::Query` case to improve the performance and readability.
There are 2 changes:
1. Remove inefficient `clone()` which can be expensive and simply iterate over values holding the lock.
2. Refactor `for` loop into `.iter().any(...)` which can be potentially faster than `for` loop as compiler could optimize it.
No
Run limiter tests.
> refactor: Simplify and optimize `should_limit` method in Limiter

- .github/workflows/ci.yml
Closes #
Sometimes CI can get stuck for a day:
https://github.com/CeresDB/ceresdb/runs/7129006500?check_suite_focus=true
Set timeout params to kill dead CI. Build jobs have 30 mins and non-build job has 10 mins
no
no need
> chore: set timeout for CI jobs

- .github/workflows/ci.yml
Closes #
CI timeout was set to 30 mins in #76. This threshold is a bit low and may fail some health jobs. More context in https://github.com/CeresDB/ceresdb/pull/78#issuecomment-1174550469
Enlarge CI timeout to 60 mins for build jobs and 20 mins for lint job
no
no need
> chore: enlarge CI timeout

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/table/metrics.rs
- analytic_engine/src/table/version.rs
Closes #68 
Implement `Purge` flush policy. Detailed in #68.
- new flush option `TableFlushPolicy`
- new field in `TableFlushRequest`: `max_sequence` and `policy`
- change `MemTableView::pick_memtables_to_flush` to pick memtable based on sequence number rather than memtable id
no
By existing UT
> feat: new flush policy - purge flush

- Cargo.lock
- wal/Cargo.toml
Closes #16
Bump rocksdb (again) to make it able to compile under gcc 12 with release mode
Bump rocksdb. The branch is `tikv-6.1` which may be more stable (https://github.com/tikv/rust-rocksdb/pull/704#issuecomment-1171999478)
no
`cargo build --release` with `gcc (GCC) 12.1.0`
> chore: bump rocksdb to branch tikv-6.1

- server/src/handlers/sql.rs
- server/src/mysql/writer.rs
Closes #60 
This PR modifies the Response data structure in ceresdb/server/src/handlers/sql.rs. 
* ResponseRow: one record with response
* ResponseRows: type of Vec<ResponseRow>
* ResponseColumn: column struct, for keep column type and name
* Row: Helper type that is convenient for http serialize, this is one map
* mod http_format: ResponseRow in custom format by Serializer
* mod row_format: Row in custom format by Serializer
not
> fix: Query fields are sorted by creation

- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/engine.rs
- analytic_engine/src/instance/alter.rs
- analytic_engine/src/instance/close.rs
- analytic_engine/src/instance/create.rs
- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/instance/write_worker.rs
- analytic_engine/src/row_iter/chain.rs
- analytic_engine/src/row_iter/merge.rs
- analytic_engine/src/row_iter/record_batch_stream.rs
- analytic_engine/src/setup.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/table/mod.rs
- benchmarks/src/merge_memtable_bench.rs
- benchmarks/src/merge_sst_bench.rs
- benchmarks/src/sst_tools.rs
Related #72
To support various `SstFactory` in Instance easily, we need make it as an inner `Trait Object`.
Remove `Fa` in `Instance`, and `various` place change to `SstFactoryRef`.
No
The refactor is tested by the compiler.
> refactor: remove Fa type param in Instance

- Cargo.lock
- components/table_kv/Cargo.toml
Closes #95 
Support arm platform
Upgrade the dependency crate obkv-table-client-rs. Its old version cannot be compiled on arm platform
Users who uses mac M1 cannot build ceresdb.
Build shoud be successful on arm platforms
> fix: fix compile error on arm platform

- common_types/Cargo.toml
- common_types/src/datum.rs
- common_types/src/lib.rs
Closes #103
Feature-gate heavy dependencies in `common_types` crate, allows downstream `ceresdb-client-py` to disable them.
Adds an on-by-default `arrow_deps` feature to make `arrow_deps` optional.
`arrow_deps` is a on-by-default feature, so it's not a breaking change.
```bash
cd common_types
cargo build
cargo build --no-default-features
```
> refactor: feature gate `arrow_deps` in `common_types`

- sql/src/ast.rs
- sql/src/parser.rs
- sql/src/planner.rs
Closes #113 
Table Name (or other identifiers) with back quotes should be treated as literal token. But our interpreter will use the token with back quotes which will lead to some inconsistent behaviors like reported in #113 
Replace `ObjectName` with `TableName` in parsed SQL statement to override the `ToString` implement, which will remove quotes and join every token with `.`
No
Unit test
> fix: table name with quote

- CONTRIBUTING.md
Closes #
We have added an integration test framework for user-facing interface's test. It should be documented in the contributing guide `CONTRIBUTING.md`.
Add a section about integration test to `CONTRIBUTING.md`
no
no need
> docs: add integration test section to `CONTRIBUTING.md`

- README-CN.md
- README.md
Closes #96
I have scripted the prerequirements and tested on MacOS Monterey.
> Add build guidance for mac users

- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/engine.rs
- analytic_engine/src/instance/alter.rs
- analytic_engine/src/instance/close.rs
- analytic_engine/src/instance/create.rs
- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/instance/write_worker.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/meta/details.rs
- analytic_engine/src/meta/mod.rs
- analytic_engine/src/setup.rs
- analytic_engine/src/table/mod.rs
- components/object_store/src/lib.rs
- wal/src/manager.rs
Part of #72
Make `Instance` and other relative structs  more simple.
Remove Meta and Wal type params in Instance
No
The refactor is tested by the compiler.
> refactor: remove Meta and Wal type params in Instance

- analytic_engine/src/instance/alter.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/meta/meta_update.rs
- analytic_engine/src/payload.rs
Closes #82
quote from #82:
>`AlterSchema` and `AlterOption` are now persisted in the manifest. It would be better to keep manifest simple (only contains SST file information, sequence number, etc.). And schema modification is related to data, putting them in two separate places may bring some problems.
This PR focus on the second target -- put DDL (altering schema and options) together with data WAL.
A more detailed reason is that in distributed mode, we have a writer node and serval reader nodes. Where the writer serves all the related write requests, including writing data and altering schema/options. And readers sync new data from their writer. They communicate with data WAL. However, the data WAL used only contains the data logs. This is problematic when for example, the schema is …
> feat: persist `AlterSchema` and `AlterOptions` to data WAL

- system_catalog/src/tables.rs
- tests/cases/01_system/system_tables.result
Closes #129 
select system.public.tables will return error
I modified the creation method of record_schema_with_key. The original creation method cannot create a RecordBatch of the corresponding capacity according to the request parameters in the request, resulting in an error when filling the data
https://github.com/CeresDB/ceresdb/blob/main/system_catalog/src/tables.rs#141 
However, I found that when I executed the following statement, the returned `RecordBatchVec` was empty,I will find the reason for this problem later
```
SELECT
`timestamp`,
`catalog`
FROM
system.public.tables
WHERE
table_name = '01_system_table1';
```
none
none
> fix:select system.public.tables will return error

- .github/workflows/ci.yml
Closes #5 
Currently  CI will take 50+ mintues to execute, which is too long, developers can do nothing but wait before review/merge...
Simplify CI jobs, to be exactly:
1. Remove `linux-build-lib` job, which is a pre-task for others. However this is not required, and other task can just run in parallel.
2. Remove container, run CI directly on ubuntu
3. Run clippy & rustfmt within one job
No
- https://github.com/jiacai2050/ceresdb/runs/7826879006
The CI execution time only take 7min now
> fix: ci cache dependencies

- Cargo.lock
- arrow_deps/Cargo.toml
- common_types/src/datum.rs
- tests/cases/00_dummy/select_1.result
- tests/cases/local/basic.result
- tests/cases/local/basic.sql
Closes #123 
Double quoted string is supported in Mysql and ceresdb plans to support such dialect.
+ Bump datafusion's version.
+ Add datum's conversion from double quoted string in ceresdb.
Users can use double quoted string like what they do in Mysql now.
Test by integrated tests.
> feat: support double quoted string.

- .github/workflows/deploy-docs.yml
Closes #
After #186, user-guide is renamed to guides, but build script still use old directory.
- https://github.com/jiacai2050/ceresdb/runs/7853729539?check_suite_focus=true
> docs: fix build dir

- wal/Cargo.toml
Closes #
`async-trait` crate has been used by multiple crates and all of them has the version 0.1.53 except the `wal` crate.
Update the version of `async-trait` to 0.1.53 used by `wal` crate.
None.
Existing unit test.
> chore: update the async_trait used by wal to 0.1.53

- analytic_engine/src/context.rs
- analytic_engine/src/engine.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/table/mod.rs
Closes #
In our design #175 a table handle `RoleTable` is decoupled with `TableData`, and needs to be able to change dynamically. One way is making `TableImpl` fetch the table handle from `Instance` every time rather than keep one. This PR finished (partially) the part in `TableImpl` -- keep some infos (space id and table id) for fetching the table handle.
- refactor: remove unused struct `CommonContext`
- refactor: add fields to `TableImpl`
The second change is for making `RoleTable` can be change dynamically. So we need to fetch the table handle from `Instance` each time rather than keep an unchangeable handle. But we do not have `RoleTable` for now so I also keep `SpaceAndTable` to pass compilation. It should be removed maybe after #188.
no
this patch doesn't need
> refactor: store `SpaceId` and `TableId` in `TableImpl`

- Cargo.lock
- arrow_deps/Cargo.toml
Closes #
We need a customized patch branch of DataFusion, it was maintained in my personal fork `waynexia/arrow-datafusion`. To achieve better governance and let more join the maintenance I move that branch to this organization. 
Switches DataFusion's upstream, from `waynexia/arrow-datafusion` to `CeresDB/arrow-datafusion`.
no
no
> chore: switch datafusion fork

- analytic_engine/src/sst/builder.rs
- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/sst/parquet/hybrid.rs
- analytic_engine/src/sst/parquet/mod.rs
- analytic_engine/src/sst/parquet/reader.rs
- analytic_engine/src/sst/reader.rs
- common_types/src/datum.rs
- common_types/src/record_batch.rs
- common_types/src/schema.rs
part of  #77 
See issue above
- And a new table option `stroage_format`, read from env now
- Write record as hybrid format, read will be supported in future PR.
Unit tests
> feat: write hybrid storage format

- analytic_engine/src/instance/alter.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/meta/details.rs
- analytic_engine/src/payload.rs
- benchmarks/src/util.rs
- benchmarks/src/wal_write_bench.rs
- wal/src/kv_encoder.rs
- wal/src/table_kv_impl/namespace.rs
- wal/src/tests/util.rs
Closes #
Building Payload in `encode_batch` can improve performance.
1. Add `encode_batch` to encode batch payload in LogBatchEncoder.
2. Receive `&impl Payload` in encode to encode single payload.
No
Unit Tests.
> refactor: build Payload in encode_batch for LogBatchEncoder

- common_types/src/datum.rs
- server/src/mysql/error.rs
- sql/src/planner.rs
- tests/cases/03_dml/insert_mode.result
- tests/cases/03_dml/insert_mode.sql
Closes #211
Now CeresDB reports failure when inserting negative number value and that is a bug needing fix. And the bug actually will lead to the failure of inserting any **explicitly signed** number.
Fix the parsing procedure from `Expr` to `Datum` to ensure numbers with sign are allowed to insert.
None.
Add new UT tests and integration tests.
> fix: insert negative number value

- catalog/src/schema.rs
- catalog_impls/src/volatile.rs
- cluster/src/cluster_impl.rs
- cluster/src/config.rs
- cluster/src/lib.rs
- cluster/src/table_manager.rs
- cluster/src/topology.rs
- common_types/src/schema.rs
- common_types/src/table.rs
- meta_client/src/types.rs
- query_engine/src/logical_optimizer/type_conversion.rs
- server/src/config.rs
- server/src/grpc/mod.rs
- server/src/grpc/route.rs
- server/src/route/cluster_based.rs
- server/src/route/mod.rs
- server/src/route/rule_based.rs
- server/src/schema_config_provider/cluster_based.rs
- server/src/schema_config_provider/config_based.rs
- server/src/schema_config_provider/mod.rs
Closes #92 
The routing information when starting CeresDB with CeresMeta is stored in CeresMeta, and we need to provide such information to the clients by `route` grpc service.
Implement the router based on `Cluster`, and then provide the `route` gRPC service based on the router.
None because the `route` service is compatible.
Some new unit tests to ensure this PR.
> feat: support route in cluster mode

- cluster/src/cluster_impl.rs
- meta_client/src/meta_impl.rs
Closes #
Deadlock occurs when fail to send heartbeat stream and reconnect the gRPC server. Actually, `reconnect_hearbeat_channel` will take the write lock on the `grpc_client` but it is very implicit.
- Avoid taking the write lock on the `grpc_client` in the `reconnect_heartbeat_channel`, and let the caller to update the `grpc_client` manually.
- Remove topology cache update procedure because it can't handle the updates.
None.
Test by manually.
> fix: deadlock when reconnect heartbeat channel

- Cargo.lock
- analytic_engine/src/table_options.rs
- catalog_impls/src/volatile.rs
- ceresdbproto_deps/Cargo.toml
- cluster/src/cluster_impl.rs
- cluster/src/lib.rs
- cluster/src/table_manager.rs
- cluster/src/topology.rs
- meta_client/src/lib.rs
- meta_client/src/meta_impl.rs
- meta_client/src/types.rs
- server/src/config.rs
- server/src/route/cluster_based.rs
- server/src/route/hash.rs
- server/src/route/mod.rs
- server/src/route/rule_based.rs
Closes #
For a table that haven't been created, the cluster-based router will respond with no nodes, but that is unacceptable for creating table request.
For a table that doesn't exist, the cluster-based router will pick one random node in the cluster for that.
Route request for non-existed table will be replied with a random node.
Test by manually with client.
> feat: support to route for missing tables

- .github/workflows/ci.yml
- Makefile
- analytic_engine/src/role_table/leader.rs
- analytic_engine/src/role_table/mod.rs
- analytic_engine/src/sst/parquet/index.rs
- etc/license.template
- rustfmt.toml
- scripts/check-license.sh
- src/adapter.rs
Closes #
Referring to https://github.com/rust-lang/rustfmt/pull/5246, `rust fmt` no longer provides license checking.
We need to check the file license in another way.
Use  a script to check the file license.
Refer to https://github.com/tikv/tikv/commit/8be0b14d34382eaa7ff9814714af19043547466e
Thanks tikv.
No.
No need.
> fix:fix license check

- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/instance/write_worker.rs
- analytic_engine/src/space.rs
- analytic_engine/src/table/data.rs
Closes #183 
* A table may be flushed multiple times.
* A table may be operated by another `WorkerLocal` which will break our concurrent invariant "The worker is single threaded and holding this is equivalent to holding a write lock"
I added the action to filter out the tables it owns based on the current `workerlocal`.
> fix: flush of one table might be triggered multiple times

- .github/workflows/ci.yml
- .github/workflows/docker-build-image.yml
- .gitignore
- Makefile
Closes #11 
Now the submodule is initialized by cloning the repo manually, and actually it can be fetched by checkout action.
- Let the submodule be initialized by `checkout` action.
- Adjust the trigger condition (only when pushed to `main` branch) for `docker-build-image.yml`.
None.
No need to test.
> chore: fix submodule init

- catalog_impls/src/cluster.rs
- catalog_impls/src/lib.rs
- cluster/src/cluster_impl.rs
- cluster/src/lib.rs
- cluster/src/table_manager.rs
- common_types/src/schema.rs
Part of #245.
`CatalogManager` and `SchemaManager`'s interfaces are redundant in some sorts. This is one step towards `Cluster` and `catalog`'s combination. The next step should be to implement table manipulating operations on top of this.
This patch implements `CatalogManager` and `SchemaManager` using `TableManager`, and implement `catalog::manager::Manager` for `ClusterImpl`
The new `catalog::manager::Manager` implementation should replace `volatile`, but I haven't removed the old one to keep this patch small.
No so far.
untested.
> refactor: use TableManager to implement `CatalogManager` and `SchemaManager`

- server/src/config.rs
- server/src/grpc/write.rs
- src/setup.rs
Closes #
In `static routing` mode, ceresdb  should open the `schema`s defined in config.
Open the `schema`s defined in config.
No.
> feat: create schema in static routing

- cluster/src/cluster_impl.rs
- cluster/src/table_manager.rs
- meta_client/src/lib.rs
- meta_client/src/meta_impl.rs
- meta_client/src/types.rs
- server/src/server.rs
- src/setup.rs
Part of #235
Remove the event handling from the cluster, and afterwards a service will be started in ceresdb-server, for handling rpc from CeresMeta.
- Remove event handling from Cluster.
- Remove some unused types: `*Cmd`.
None.
Not ready for test.
> refactor: remove event handling from cluster

- Cargo.lock
- server/Cargo.toml
- server/src/handlers/sql.rs
- server/src/http.rs
Closes #
Fow now, HTTP endpoint `sql` only accept JSON request, it's not convenient to wrap sql inside `{"query": "sql"}`
Enhance sql handle endpoint, to accept both json and raw text request
Yeah, you can make http request like this directly:
```
$ curl -d 'show tables' -H 'content-type: text/plain' 0:5440/sql
{"rows":[]}
```
Manually
> feat: enhance sql handle, accept both json and text request

- .github/workflows/ci.yml
- .github/workflows/tsbs.yml
Closes #
In current CI, the cache size is 4G after gzipped, which is too large, one issue for this is that the cache may contains both debug and release target, which is useless
- https://github.com/CeresDB/ceresdb/actions/runs/3224489192/jobs/5275667928
Update CI cache key, so release target will not be mixed with debug mode.
No
Not required.
> chore: fix CI cache key, release mode should not mix with debug

- Cargo.lock
- catalog_impls/src/volatile.rs
- cluster/Cargo.toml
- cluster/src/cluster_impl.rs
- cluster/src/lib.rs
- server/src/grpc/mod.rs
- server/src/server.rs
Part of #235
After the event loop mechanism is removed, we support a meta event service instead.
- Support the meta event service (only the skeleton without any implementations).
None.
Not ready for test.
> feat: support meta event service

- meta_client/src/lib.rs
- meta_client/src/meta_impl.rs
- src/setup.rs
Closes #304 
A blocked-on task for building meta client is started in the init procedure, leading to the panic mentioned by #304.
Avoid running blocked-on task in the init procedure.
Now this is tested by manual.
> fix: avoid running blocked-on task when building meta client

- analytic_engine/src/instance/write_worker.rs
- analytic_engine/src/table/data.rs
I added a function in the write_worker.rs to centralize the logic of choosing worker:
pub fn find_worker(table_id: usize, worker_num: usize) -> usize {
table_id % worker_num
}
> refactor: centralize the logic of choosing worker

- docs/harness.toml
- tests/Makefile
- tests/harness/src/setup.rs
Closes #
Logs are required to troubleshoot why server response unexpected result.
Add two environment variables to set log files
No
Test harness itself
> chore: support set log file when running test harness

- Cargo.toml
Closes #
Minimize release binary size. 
Refer to [min-sized-rust](https://github.com/johnthagen/min-sized-rust).
* Enable [lto](https://doc.rust-lang.org/cargo/reference/profiles.html#lto).
* Set [opt-level](https://doc.rust-lang.org/cargo/reference/profiles.html#opt-level) to "z".
The new setting minimizes the release binary size from 1.3G to 510M.
> chore: minimize release binary size

- analytic_engine/src/instance/open.rs
- analytic_engine/src/meta/details.rs
- analytic_engine/src/wal_synchronizer.rs
- wal/src/manager.rs
- wal/src/rocks_impl/manager.rs
- wal/src/table_kv_impl/region.rs
- wal/src/table_kv_impl/wal.rs
- wal/src/tests/util.rs
…and add its adapting logic to `BatchLogIteratorAdapter`.
Closes #
The `BatchLogIteratorAdapter` just support `BlockingLogIterator` as its inner. It is not enough, because in other wal implementation, the iterator return from `read_batch` may be originally async, the  `BatchLogIteratorAdapter` should take  it in consideration.
+ Define a new trait  `AsyncLogIterator`.
+ Add its adapting logic to `BatchLogIteratorAdapter`.
None.
By exist ut.
> feat: add async inner to `BatchLogIteratorAdapter`

- Cargo.toml
Part of #294 
After #322, release build will fail on host with only 8G memory, this PR introduce a quick-release profile to fix this.
```
Compiling rocksdb v0.3.0 (https://github.com/tikv/rust-rocksdb.git?rev=084102f7e4d1901cbe3f2782c5c63cb7af628bac#084102f7)
Compiling wal v0.4.0-alpha (/home/changcheng/app/before-sql/ceresdb-main/wal)
Compiling analytic_engine v0.4.0-alpha (/home/changcheng/app/before-sql/ceresdb-main/analytic_engine)
Compiling cluster v0.4.0-alpha (/home/changcheng/app/before-sql/ceresdb-main/cluster)
Compiling catalog_impls v0.4.0-alpha (/home/changcheng/app/before-sql/ceresdb-main/catalog_impls)
Compiling server v0.4.0-alpha (/home/changcheng/app/before-sql/ceresdb-main/server)
error: could not compile `ceresdb`
Caused by:
process didn't exit successfully: `rustc …
```
> chore: add quick release profile

- Cargo.lock
- Cargo.toml
- interpreters/src/table_manipulator/meta_based.rs
- server/src/server.rs
- src/setup.rs
Closes #
Now the table manipulator is hard coded when setup.
- Choose correct table manipulator when setup ceresdb-server.
None.
Test by manual.
> fix: use right table manipulator when setup

- Cargo.lock
- Cargo.toml
- components/message_queue/Cargo.toml
- components/message_queue/src/kafka/config.rs
- components/message_queue/src/kafka/kafka_impl.rs
- components/message_queue/src/kafka/mod.rs
- components/message_queue/src/lib.rs
- components/message_queue/src/tests/cases.rs
- components/message_queue/src/tests/mod.rs
- components/message_queue/src/tests/util.rs
> feat: message queue and its kafka impl 

- components/message_queue/src/kafka/kafka_impl.rs
- components/message_queue/src/lib.rs
- components/message_queue/src/tests/cases.rs
Closes #
The race's checking should not be done in mq interface level, it should be done in high-level. So I refactor it to make it simpler.
Refactor the mq interface and its kafka implemetation.
None.
By new and exist ut.
> refactor: make mq interface simpler.

- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/sst/parquet/mod.rs
- analytic_engine/src/sst/parquet/reader.rs
- components/parquet_ext/src/lib.rs
- components/parquet_ext/src/reverse_reader.rs
- components/parquet_ext/src/serialized_reader.rs
Closes #271
After #269, some parquet API is deprecated, this PR adopt to the new API.
Replace ParquetFileArrowReader with ParquetRecordBatchReader
No
Existing UT
> fix: adopt new parquet api

- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/mod.rs
- analytic_engine/src/sst/parquet/reader.rs
- analytic_engine/src/sst/reader.rs
- common_types/src/time.rs
- table_engine/src/predicate.rs
Closes #
In #312, performance has regression, so we can't replace old reader with the async reader, this PR add an async reader beside the old reader, which can be chosen by environment below
```
export ASYNC_PARQUET_READER=true
```
Add a new parquet reader based on DataFusion's ParquetExec, which use `ParquetRecordBatchStream` to parse parquet file.
No
UT `test_parquet_build_and_read`
> feat: add async parquet reader

- Cargo.lock
- Cargo.toml
- benchmarks/Cargo.toml
- benchmarks/src/bin/sst-tools.rs
- src/bin/ceresdb-server.rs
- tools/Cargo.toml
- tools/src/bin/sst-convert.rs
- tools/src/lib.rs
- tools/src/sst_util.rs
Closes #
For now, we need to test different sst options to determine which is best for performance, but there is no fast way to convert existing sst to other options, so this PR add a cli to do this job.  
Add tools workspace member, and there is one cli: `sst-convert`, 
```
cargo run --bin sst-convert -- -h
tools 0.4.0
CeresDB Authors <ceresdbservice@gmail.com>
USAGE:
sst-convert [OPTIONS] --store-path <STORE_PATH> --input <INPUT> --output <OUTPUT>
OPTIONS:
-b, --batch-size <BATCH_SIZE>      Row group size of new sst file [default: 8192]
-c, --compression <COMPRESSION>    Compression of new sst file(values:
uncompressed/lz4/snappy/zstd) [default: uncompressed]
-h, --help                         Print help information
-i, --input <INPUT>                Input sst file(relative to …
```
> feat: add tools sst-convert

- analytic_engine/src/sst/parquet/reader.rs
- benchmarks/src/util.rs
- components/parquet_ext/src/reverse_reader.rs
- components/parquet_ext/src/serialized_reader.rs
- tools/src/bin/sst-convert.rs
- tools/src/sst_util.rs
Part of #363 
After #351, the filter result about the row groups is not pushed down to parquet reading procedure.
- Apply the missing filtering results to the parquet reader.
None.
Current module will be updated in the recent future, and more UT should be added later.
> fix: apply missing filtering on parquet reader

- docs/example-cluster-0.toml
- docs/example-cluster-1.toml
- docs/guides/src/SUMMARY.md
- docs/guides/src/deploy/dynamic_routing.md
None.
CeresDB with dynamic cluster mode has been released in last week, but deploy document has not been updated, which is supported in this pull request.
* Add dynamic routing deploy document.
* Update cluster config example, Emphasize that the `meta_addr` is in http format.
Supported dynamic cluster mode deploy document for user.
It's has been tested before v0.4 released.
> docs: update dynamic cluster mode doc

- components/message_queue/src/tests/cases.rs
Closes #
Tests on message queue's kafka implementation should not be run automatically.
Add `ignore` to message queue's tests.
None.
None.
> fix: add ignore to  test on message queue's kafka implementation.

- wal/src/log_batch.rs
- wal/src/manager.rs
- wal/src/message_queue_impl/region.rs
- wal/src/rocks_impl/manager.rs
- wal/src/table_kv_impl/region.rs
Closes #378 
See #378 .
+ Add table id in `LogEntry`.
+ Modify related module.
None.
Test by exist ut.
> feat: add table id to `LogEntry`

- Cargo.lock
- Cargo.toml
- analytic_engine/Cargo.toml
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/sst/file.rs
- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/table/version_edit.rs
- common_types/src/datum.rs
- proto/protos/sst.proto
Part of #363 
Described in #363, bloom filter is beneficial for columns with high cardinality, so this PR append bloom filter to sst's meta when write SST files.
Update sst write process, loop record batch twice:
- first to build bloom filter
- second to write to underlying storage.
> Note: for now, all columns is appended with bloom filter, some columns may not suitable for it, we can remove them in future to reduce meta size.
No
Add UT: test_partition_record_batch
After we support prune by bloom filter, we can add more test cases.
> feat: add bloom filter when write sst

- analytic_engine/src/sst/parquet/builder.rs
Refactor for #370
Previous implementation for building row groups from record batch is a little bit complex, and this pr will do some refactoring work for that.
- Refactor the `partition_record_batch`;
None.
Existing ut.
> refactor: build row groups from record batch stream

- interpreters/src/show.rs
- sql/src/parser.rs
Closes #
After #331, show tables support `like` syntax, this PR add more testcases and refactor some code.
Refactor `is_table_matched` to make it more readable.
No
Existing UT
> refactor: show tables

- wal/src/tests/read_write.rs
- wal/src/tests/util.rs
Closes #386 
See #386 
Refactor tests in wal.
None.
They are tests themselves.
> refactor: wal unit tests.

- analytic_engine/src/sst/file.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/mod.rs
- analytic_engine/src/sst/parquet/reader.rs
- analytic_engine/src/sst/parquet/row_group_filter.rs
- analytic_engine/src/sst/reader.rs
- components/parquet_ext/src/prune/equal.rs
Part of #363 
Utilize the bloom filter stored in the sst meta data to do filtering on the row groups according to the provided predicate.
- Support filter row groups in when reading file.
- Update the `EqPruner`'s interface to make it more reasonable.
None.
New unit test.
> feat: filter row groups by bloom filter

- benchmarks/src/bin/parquet-reader.rs
- benchmarks/src/parquet_bench.rs
Closes #
In parquet sync read, file is read out before iterate record batch, this PR update async read bench, to let it have same logic with sync version
Not required
A benchmark for parquet file with 103951966 rows
```
[2022-11-14T09:03:56Z INFO  benchmarks::parquet_bench]                                                                                                               
ParquetBench Async total rows of sst:103951966, total batch num:12690,
open cost:790.76716ms, filter cost:149.713098ms, iter cost:9.603906449s
[2022-11-14T09:31:39Z INFO  benchmarks::parquet_bench] 
ParquetBench Sync total rows of sst:103951966, total batch num:12690,
open cost:969.653961ms, filter cost:165.7483ms, iter cost:9.981503914s
```
> feat: read all bytes out before do async bench

- components/object_store/src/aliyun.rs
- components/object_store/src/cache.rs
Closes #365 
It is a basic and common feature of OSS to get range of the object file.
- Support get range of object for aliyun oss
None.
Add a new test for header making.
> feat: support get_range in aliyun oss

- meta_client/src/meta_impl.rs
None.
CeresDB interacts with CeresMeta through grpc implemented in `meta_client`, and now the timeout of grpc is not set, this will cause CeresDB to be blocked when the network fails.
* Add timeout config in `meta_client`.
None.
Local manual test.
> fix: add meta client timeout

- Cargo.lock
- common_types/src/lib.rs
- common_types/src/time.rs
Closes #
The CI of #401 was skipped, leading to that the update of Cargo.lock is not included.
- Update the Cargo.lock.
- Move the datafusion part to sub separate module in `common_types::time` for ceresdb-client-rs to use.
None.
Existing UT.
> fix: wrong cargo lock

- .github/workflows/ci.yml
- .github/workflows/tsbs.yml
- Cargo.lock
- Dockerfile
- docs/guides/src/dev/compile_run.md
- proto/Cargo.toml
- proto/build.rs
Closes #
#406 has updated the ceresdbproto to avoid its requirement for protoc, but the `proto` still needs the protoc. Let's introduce the `protoc-bin-vendored` for automatic installation of protoc.
- Remove the installation of protoc.
- Introduce `protoc-bin-vendored` to install protoc by the crate itself.
None.
Existing test.
> chore: remove manual installation of protoc

- analytic_engine/src/meta/details.rs
- analytic_engine/src/setup.rs
- wal/src/kv_encoder.rs
- wal/src/rocks_impl/manager.rs
- wal/src/table_kv_impl/encoding.rs
- wal/src/table_kv_impl/mod.rs
- wal/src/table_kv_impl/model.rs
- wal/src/table_kv_impl/namespace.rs
- wal/src/table_kv_impl/table_unit.rs
- wal/src/table_kv_impl/wal.rs
- wal/src/tests/read_write.rs
- wal/src/tests/util.rs
Closes #389 
See #389.
+ Replace old log format with common log format.
+ Rename `Region` to `TableUnit`.
+ Support scanning in two existing wal implementations.
None.
Test by ut.
> feat: refacor existing wal implementations to support scanning logs of shard

- docs/guides/src/quick_start.md
- docs/guides/src/sql/identifier.md
- tests/cases/local/basic.result
- tests/cases/local/basic.sql
Closes #220 
- Add case-sensitive testcase
- Update docs explain this
- Format SQL in docs
No
Test harness
> test: add case sensitive demo

- Cargo.lock
- components/object_store/Cargo.toml
- components/object_store/src/lib.rs
- components/object_store/src/mem_cache.rs
Part of #391
Add CachedStore in object store module, it can
- evict item based on configured memory capacity
- support partition to reduce lock contention
No
New unit test
- `test_mem_cache_evict`
- `test_mem_cache_partition`
> feat: add memory based cache for object store

- analytic_engine/src/meta/details.rs
- wal/src/table_kv_impl/table_unit.rs
Closes #
Now, most options in operations of manifest can't be configured. It may make the process failed to setup due to the default setting is unreasonable, and we must make them configurable.
Make manifest operations configurable.
User can set more options about manifest now.
Test by existing ut.
> feat: make manifest operations more configurable

- README-CN.md
Closes #429
Fix the broken link of  the conventional commit guide in the Chinese version of README-CN.md
- Update link target in README-CN.md
no
doesn't need
> docs: fix broken conventional commit document link(#429)

- wal/src/table_kv_impl/table_unit.rs
Closes #
Now, load last sequence step in obkv wal has a logic error, which leads to a serious bug about load a mistaken last sequence.
Fix above bug.
None.
Test manually.
> fix: load last sequence in obkv wal

- wal/src/message_queue_impl/namespace.rs
Closes #
Now, I found drop wal on mq may need to panic because dropping runtime in `drop()`. 
You can reproduce it using following cmd(need a kafka cluster):
```
RUST_BACKTRACE=1 cargo test --workspace --package wal --lib -- read_write::test_kafka_wal --ignored
```
The error message:
```
---- tests::read_write::test_kafka_wal stdout ----
thread 'tests::read_write::test_kafka_wal' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /Users/kamiu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/mod.rs:89:25
stack backtrace:
0: std::panicking::begin_panic
at …
```
> fix: drop bug of wal on mq, can't not drop runtime

- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/sst/parquet/hybrid.rs
Closes #403 
Fix bugs described in #403 .
Hybrid storage compresses multi-record batches into one record batch.
There is a bug where `collapsible_col_arrays` in `TsidBatch` only stores the first record batch data, other record batch data are lost.
No.
Modify some tests to cover this bug.
> fix: hybrid storage encode bug in multi record batch

- analytic_engine/src/lib.rs
- analytic_engine/src/setup.rs
- wal/src/table_kv_impl/model.rs
- wal/src/table_kv_impl/namespace.rs
Closes #
Background of this pr:
+ now, our `manifest` is `wal` based, and in `wal` on obkv, there is a `ttl` based logs clean strategy.
But data in `manifest` should be permanent and shouldn't be cleaned due to `ttl`. So we should hide the `ttl` of `wal` on obkv, while it is set for `manifest`.
+ the `ttl` and `permanent` strategies are incompatible, so we should check it while opening `wal` (on obkv).
See above background.
Obkv users should switch to new config.
Test manually.
> refactor: manifest wal config

- Cargo.lock
- Cargo.toml
Closes #
After hard working from both CeresDB team and community, lots of new features and bugfixes and landed in CeresDB, it's time for another release 🚀
Bump project version
- Improve query performance
- Utilize the bloom filter stored in the sst meta data to do filtering on the row groups according to the provided predicate
- Refactor sst cache based on weighted LRU.
- Add a new async parquet reader.
- Support `get_range` api in aliyun oss to avoid OOM when sst is large.
- Add memory based cache for object store.
- Improve CeresDB cluster mode 
- Implement distributed wal based on kafka.(unstable)
- Implement expansion and transferLeader control with [ceresmeta](https://github.com/CeresDB/ceresmeta).(unstable)
- Refactor cluster metadata management in ceresemta.
- Replace protobuf with …
> chore: bump version to 1.0.0-alpha01

- sql/src/ast.rs
- tests/cases/local/03_dml/case_insensitive.result
- tests/cases/local/03_dml/case_insensitive.sql
Part of #442
Change table name to lowercase when not quoted
Yes, table name will be converted to lowercase when not quoted
Test harness
> feat: convert table name to lowercase when not quoted

- .github/workflows/docker-build-image.yml
- docs/example-cluster-0.toml
- docs/example-cluster-1.toml
- docs/minimal.toml
Closes #
After #421, config of object store is changed, but minimal config is still using old format, and it will cause error below
```
thread 'main' panicked at 'Failed to parse config.: ParseToml { path: "/etc/ceresdb/ceresdb.toml", source: Error { inner: ErrorInner { kind: Custom, l
ine: Some(21), col: 0, at: Some(381), message: "missing field `mem_cache_capacity`", key: ["analytic", "storage"] } }, backtrace: Backtrace(   0: <sna
```
No 
CI
> fix: object_store config

- Cargo.lock
- analytic_engine/src/lib.rs
- analytic_engine/src/setup.rs
- analytic_engine/src/storage_options.rs
- analytic_engine/src/tests/util.rs
- common_util/src/time.rs
- components/object_store/Cargo.toml
- components/object_store/src/disk_cache.rs
- components/object_store/src/lib.rs
- docs/harness.toml
- proto/build.rs
- proto/protos/cache.proto
- proto/protos/oss_cache.proto
- proto/src/lib.rs
Close #391
Final PR for  #391
- Add DiskCacheStore, ObjectStore wrapper which use disk as cache. Some features:
- Cache key is used as filename, something like `2-2199023255565-1.sst-0-3297`
- When startup, it will recover cache from given cache dir
- Besides sst cache file, there is a `manifest.json` file contains following info:
```json
{
"create_at": "2022-12-01T08:51:15.167795+00:00",
"page_size": 1048576,
"version": 1
}
```
- Setup DiskCacheStore
No
Unit test in disk_store.rs and test harness
> feat: add disk based object store cache

- server/src/http.rs
- server/src/server.rs
- src/bin/ceresdb-server.rs
- src/setup.rs
Closes # https://github.com/CeresDB/ceresdb/issues/436
Support dynamic setting of log level to avoid server restart.
Add API `logLevel`, log level could be updated like this:
```curl --location --request PUT 'http://localhost:5440/log_level?level=debug'```
None.
Manual test in local environment.
> feat: add dynamic setting log level

- analytic_engine/src/lib.rs
- analytic_engine/src/storage_options.rs
Closes #
Use default value for StorageOptions, otherwise server will throw following errors when those options are not configured
```
thread 'main' panicked at 'Failed to parse config.: ParseToml { path: "/tmp/db.toml", source: Error { inner: ErrorInner { kind: Custom, line: Some(33), col: 0, at: Some(674), message: "missing field `disk_cache_capacity`", key: ["analytic", "storage"] } }, backtrace: Backtrace(   0: backtrace::backtrace::libunwind::trace
```
No
Start server locally
> chore: use default value for StorageOptions

- sql/src/planner.rs
- tests/cases/local/03_dml/case_insensitive.result
- tests/cases/local/03_dml/insert_mode.result
- tests/cases/local/05_ddl/alter_table.result
- tests/cases/local/05_ddl/create_tables.result
- tests/cases/local/05_ddl/create_tables.sql
- tests/cases/local/06_show/show_create_table.result
- tests/cases/local/basic.result
Closes #
After #340 merged, it can't define (tsid, timestamp_key_name) as primary key. And this pr will fix this problem.
- Refactor the generation of create table plan;
- We can define a primary key with tsid;
The tsid column will be the last column in the schema after this pr, compared with that tsid column just follows the timestamp key column.
New sql test in the harness.
> fix: wrong primary key when define tsid and timestamp key as primary key

- analytic_engine/src/sst/metrics.rs
- analytic_engine/src/sst/mod.rs
- analytic_engine/src/sst/parquet/async_reader.rs
Closes #
The default implementation of `get_byte_ranges` in `AsyncFileReader` is sequentially.
Refer to: https://github.com/apache/arrow-rs/blob/99ced481308e870f69792e49cd23a529fa3ccc70/parquet/src/arrow/async_reader.rs#L124-L140
* Implement parallel `get_byte_ranges` using `get_ranges` in `ObjectStore`.
* Add a histogram to record the length of `get_range`.
No.
> feat: impl parallel get_byte_ranges for ObjectStoreReader

- analytic_engine/src/sst/parquet/builder.rs
- sql/src/ast.rs
- sql/src/parser.rs
- tests/cases/local/03_dml/case_insensitive.result
- tests/cases/local/03_dml/case_insensitive.sql
Closes #
For #442 .
Now we convert table name to quoted style to prevent `datafusion` from converting it to lowercase. 
All changes are in `sql/src/parser.rs`.
Main steps:
+ extract the table name from `select ast`.
+ convert it to quoted style.
+ rebuild the `select ast`.
Table name in ceresdb will be case-sensitive.
Test by ut and integrated test.
> feat: convert table name to quoted style

- analytic_engine/src/sst/parquet/encoding.rs
- common_types/src/schema.rs
- interpreters/src/alter_table.rs
- proto/protos/common.proto
- server/src/grpc/storage_service/mod.rs
- server/src/grpc/storage_service/prom_query.rs
- sql/src/planner.rs
- tests/cases/local/05_ddl/create_tables.result
- tests/cases/local/05_ddl/create_tables.sql
Closes #
Currently, the field in the schema `enable_tsid_primary_key` is useless. Let's remove it.
Remove `enable_tsid_primary_key` field in the schema.
This will lead to breaking change for that the field `enable_tsid_primary_key` is part of the format of stored schema.
> refactor: remove `enable_tsid_primary_key`

- analytic_engine/src/meta/details.rs
- analytic_engine/src/setup.rs
- wal/src/manager.rs
- wal/src/rocks_impl/manager.rs
- wal/src/tests/read_write.rs
- wal/src/tests/util.rs
Closes #
Now, If you write log with a not default region id in key, you will be unable to recover it when you restart the database(use a rocksdb based wal). It make no sense, so we should adjust the recover process in rocksdb based wal.
Adjust the recover process in rocksdb based wal.
None.
Test by ut.
> feat: make rocksdb wal compatible with other distributed implementation

- components/object_store/src/prefix.rs
Closes #
The real path from the `StoreWithPrefix` contains the extra `prefix` which should be stripped.
- Remove the extra `prefix` from the result of `StoreWithPrefix`;
None.
New tests.
> fix: wrong path in the result from StoreWithPrefix

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/flush_compaction.rs
Closes #
Currently, there is no limit on the memory usage by the background compaction task, leading to frequent OOM on the prod environment.
- Add memory usage limit for compaction scheduler, so the task will be skipped and put back to the request queue if the memory threshold is reached.
None.
> feat: support memory usage limit on background compaction

- Cargo.lock
- analytic_engine/src/setup.rs
- components/object_store/Cargo.toml
- components/object_store/src/mem_cache.rs
Closes #
In our test env, OOM happens a lot when memory store is on, when disable it the OOM also disappear, so I suspect the LRU dependence has mem leak bug.
Change LRU to https://github.com/marmeladema/clru-rs/, which has more testcases, and smaller amount of unsafe code.
No
Unit tests, and will also check in test env.
> fix: lru-weighted-cache mem leak

- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/encoding.rs
Closes #
Now, parquet builder has support manual flushing api, we can try to support bloom filter in hybrid format. 
Manual flushing after writing a hybrid row group.
None.
Test by ut.
> feat: support bloom filter in hybrid format

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/write_worker.rs
Closes #
In current implementation, when a table has no write any more, its data will never be compacted.
- Update scheduler, do table compact at fixed interval.
No
Manullay.
> fix: compact table in background scheduler

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/flush_compaction.rs
- components/profile/Cargo.toml
- components/profile/src/lib.rs
Closes #471 
The #471 is caused by the wrong path of profile result output. And this PR will fix it.
- Add some logs for some module.
- Fix wrong path for the profile result output.
- Create the profile output file if not exists.
None.
Test manually.
> fix: wrong profile output os path for heap profiling

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/table_options.rs
- proto/protos/analytic_common.proto
Part of #408
The target of #408 plan to limit output sst file, but there is no easy way to tell how large the output file will be, so
this PR use another strategy: limit total input size.
When pick files for compaction, add a new limit: `max_input_sstable_size`,
it will control total input file size to compact.
For now, we can custom it via environment variables, such as
```
export CERESDB_MAX_INPUT_SSTABLE_SIZE=1G
```
No
New unit test `test_size_tiered_picker`
> feat: add max_input_sstable_size

- Cargo.lock
- Cargo.toml
- analytic_engine/Cargo.toml
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/row_iter/mod.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/reader.rs
- benchmarks/src/merge_memtable_bench.rs
- benchmarks/src/merge_sst_bench.rs
- benchmarks/src/sst_bench.rs
- benchmarks/src/sst_tools.rs
- benchmarks/src/util.rs
- common_types/src/projected_schema.rs
- common_types/src/record_batch.rs
- tools/src/bin/sst-convert.rs
Closes #
Now, the concurrent level while pulling sst data is on file level, we can enhance it to row group level.
Test by ut.
> feat: scan row groups in one sst file parallelly

- analytic_engine/src/sst/file.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/reader.rs
- analytic_engine/src/sst/parquet/row_group_filter.rs
Prepare for #489 
Currently, bloom filter index is necessary in the sst reader. However, this is actually optional.
- Make the bloom filter index in the sst reader optional.
None.
Current tests.
> feat: make the bloom filter optional in sst meta

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/setup.rs
- components/object_store/src/mem_cache.rs
Prepare #489 
Mentioned by #489, some data from the object store is not necessary to do caching so an object store with readonly cache are needed.
- Add object store with readonly cache for the instance.
- Object store with readonly cache is used for reading input data in compaction procedure.
None.
> feat: support store with readonly cache

- analytic_engine/src/sst/parquet/encoding.rs
Closes #53.
We don't have plan to switch to parquet2 any more.
In old version of parquet, there is no way to get inner writer.
Upstream have added this method, so don't required this workaround.
No 
Old unit test
> fix: remove EncodingWriter

- Cargo.lock
- sql/Cargo.toml
- sql/src/ast.rs
- sql/src/lib.rs
- sql/src/parser.rs
- sql/src/partition.rs
- sql/src/planner.rs
- table_engine/src/partition/mod.rs
Closes #
We need to support table partition now, this pr is for supporting parsing the related sql to statement.
The syntax is same as [Mysql](https://dev.mysql.com/doc/refman/8.0/en/partitioning-types.html) .
But now, we only support the hash strategy. 
Add sql syntax support for creating partition table(only hash strategy).
Mainly modify `sql/src/parser.rs`.
Ceresdb can accept related sql syntax now(but related function is not supported yet).
Test by ut.
> feat: support parsing partition table creating

- server/src/grpc/storage_service/prom_query.rs
- server/src/grpc/storage_service/query.rs
- server/src/grpc/storage_service/write.rs
- server/src/handlers/admin.rs
- server/src/handlers/error.rs
- server/src/handlers/sql.rs
- server/src/limiter.rs
Closes #470 
Refer to #470.
- Support limit query by `BlockRule`;
- Add a `BlockRule` called `QueryWithoutPredicate` to block the query like `select * from t`;
- Expose the operation of the block rules to http api service; 
Support block query with block rules, especially, `QueryWithoutPredicate`.
> feat: support query limit by rule

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/table/data.rs
- benchmarks/src/merge_memtable_bench.rs
- benchmarks/src/merge_sst_bench.rs
- benchmarks/src/sst_bench.rs
- benchmarks/src/sst_tools.rs
- benchmarks/src/util.rs
- tools/src/bin/sst-convert.rs
Prepare for #495 
Refer to #495:
> Currently, the sst type is used to decide which type of sst reader/builder to create, but this option is configured for table level, that is to say, one table can only use one sst type. I guess this is not reasonable, and it is more flexible and elegant to allow the data of one table being encoded in different sst formats. So I guess we make this option only works when deciding the type of sst builder, and add a new sst type called Auto for the flexibility of choosing a better sst format.
- Remove sst type option when reading sst;
- Add a new sst type called `Auto`;
None.
> chore: adjust usage of sst type

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/row_iter/chain.rs
- analytic_engine/src/row_iter/merge.rs
- analytic_engine/src/row_iter/record_batch_stream.rs
- analytic_engine/src/setup.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/builder.rs
- benchmarks/src/merge_memtable_bench.rs
- benchmarks/src/merge_sst_bench.rs
- benchmarks/src/sst_bench.rs
- benchmarks/src/sst_tools.rs
- benchmarks/src/util.rs
- tools/src/bin/sst-convert.rs
Closes #
#490 introduced two object store for ceresdb instance, and that is a little bit ugly.
- Introduce `ObjectStorePicker` to replace the two object stores.
None.
> feat: introduce ObjectStorePicker to replace the two object stores

- table_engine/src/lib.rs
- table_engine/src/remote/mock_impl.rs
- table_engine/src/remote/mod.rs
- table_engine/src/remote/model.rs
Closes #
Part of #492 
See #492.
We need to read/write the remote table engine.
+ define the remote table engine trait
None.
Not need now.
> feat: define remote table engine trait

- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/builder.rs
- common_util/src/error.rs
- common_util/src/lib.rs
Prepare for #495 
In order to control how to decode our custom sst file, the object store must be separated from the Parquet SST async reader because the api of object store has no flexibility to introduce another footer after the original file content.
- Separate the ObjectStore from the parquet sst async reader.
None.
> refactor: separate object store from parquet sst async reader

- Cargo.lock
- catalog_impls/src/table_based.rs
- interpreters/src/tests.rs
- server/src/lib.rs
- server/src/local_tables.rs
- server/src/server.rs
- src/setup.rs
- system_catalog/src/sys_catalog_table.rs
Closes #413 
See #413  
+ modify the `VisitorImpl::visit_tables` to just collect the table infos.
+ move the actual recovery work to `SchemaImpl::open_table`.
None.
Test by exist ut.
> refactor: recovery in standalone mode

- interpreters/src/show_create.rs
- proto/protos/meta_update.proto
- sql/src/ast.rs
- sql/src/parser.rs
- sql/src/partition.rs
- table_engine/src/partition/mod.rs
Closes #
In order to support the key partition feature, it is necessary to support parse the statement.
- Support parse key partition;
Now user can use key partition statement to create table.
TODO
> feat: support parse key partition

- Cargo.lock
- proto/Cargo.toml
- proto/build.rs
- proto/protos/remote_engine.proto
- proto/src/lib.rs
Closes #
In the process of implementing the partition table, remote calls between ceresdb-server are involved.
So `remote_engine` grpc service is needed.
Define remote_engine grpc service.
No.
No need.
> chore: define remote_engine grpc service

- Cargo.lock
- Cargo.toml
- analytic_engine/src/meta/meta_update.rs
- interpreters/src/table_manipulator/meta_based.rs
- meta_client/src/types.rs
- proto/protos/meta_update.proto
- server/src/grpc/meta_event_service/mod.rs
- table_engine/src/partition/mod.rs
Closes #
To support creation of partition tables, we have updated the data structure in ceresdbproto and added encodedPartitionInfo. CeresDB needs to adapt to this adjustment.
* Update ceresdbproto
* Adapt to new data structures.
* Modify `meta_update` to decode/encode oneof struct.
None.
Pass exists unit tests.
> feat: update ceresdb proto & adapter to partition info

- common_types/src/schema.rs
- common_util/src/avro.rs
Closes #
Part of #492 
We convert all `int` related types to `int32` and `int64`, because only these two int types in `avro` now.
So when converting `Value`(`avro` datum) to `Datum`, we should convert it back to the right type in schema.
Modify `avro_value_to_datum` in `avro.rs` for converting back to the right type.
None.
Test by ut.
> fix: fix conversion by avro

- server/src/handlers/sql.rs
Closes #
Now  `convert_records` will intercept the `record_ batches` only uses the first element, which will result in multiple `records_batch` in the query result is truncated.
* Traverse `record_batch` to return all data.
None.
Pass existing unit test.
> fix: fix convert record batch

- analytic_engine/src/sst/parquet/async_reader.rs
Closes #
Some log are too verbose, so PR try to normalize them
Update log when reading sst
No
No need
> chore: add more context for query log

- common_util/src/avro.rs
- integration_tests/cases/local/03_dml/insert_mode.result
Closes #525 
Fix the base case in integration test.
Fix the base case.
None.
Test by integration test.
> fix: fix integration test's bad case

- .github/workflows/ci.yml
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/row_iter/record_batch_stream.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/file.rs
- analytic_engine/src/sst/manager.rs
- analytic_engine/src/sst/meta_cache.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/table/version_edit.rs
- benchmarks/src/sst_bench.rs
- benchmarks/src/sst_tools.rs
- benchmarks/src/util.rs
- proto/protos/sst.proto
- tools/src/bin/sst-convert.rs
Closes #321
1. Remove size, row_num from sst metadata. Those two fields cannot be known before write sst, so we have to store them in other place(manifest now).
2. When read sst, pass one more arg: file_size, which is stored inside FileHandle.
No 
Existing UT
> fix: remove size from sst metadata

- analytic_engine/src/meta/details.rs
- interpreters/src/show_create.rs
- proto/protos/meta_update.proto
- sql/src/partition.rs
- table_engine/src/partition/mod.rs
- table_engine/src/partition/rule/df_adapter/mod.rs
- table_engine/src/partition/rule/factory.rs
- table_engine/src/partition/rule/key.rs
Closes #
Add version field in `PartitionInfo` for future extension.
* Add version field in `PartitionInfo` for future extension.
* Rename `Definition` to `PartitionDefinition`.
No.
Old tests have covered.
> chore: add version in PartitionInfo

- Cargo.lock
- Cargo.toml
- interpreters/src/table_manipulator/meta_based.rs
- meta_client/src/types.rs
- sql/src/ast.rs
- sql/src/plan.rs
- sql/src/planner.rs
Closes #
Support drop partition table.
Add `PartitionInfo` in `DropTablePlan` to support drop partition table.
Support drop partition table.
Manual testing with `ceresmeta`.
> feat: support drop partition table

- router/src/cluster_based.rs
- server/src/grpc/forward.rs
Closes #
Auto picking a random node for non-existing table may leading to confusion to the router's user.
- Remove the logic for auto picking a random node for non-existent table;
Empty routing result will be returned for non-existent table.
> avoid routing for non-existent table

- Cargo.lock
- Cargo.toml
- cluster/src/cluster_impl.rs
- cluster/src/lib.rs
- server/src/grpc/meta_event_service/mod.rs
Closes #
Support closing and opening table.
* Implement `open_table_on_shard` in `meta_event_service`.
* Implement `close_table_on_shard` in `meta_event_service`.
No.
No need.
> feat: add open_table_on_shard and close_table_on_shard in meta_event_service

- analytic_engine/src/instance/open.rs
Closes #
Since the read-only partition table and table(follower role) need to be opened in multi servers, the server cannot do snapshot of the manifest when the table is opened.
* Disable `do_snapshot` when recover table data.
No.
No need.
> feat: disable do_snapshot when recover table data

- Cargo.lock
- Cargo.toml
- benchmarks/Cargo.toml
- benchmarks/src/bin/ipc.rs
- common_types/src/lib.rs
- common_types/src/remote_engine.rs
- components/arrow_ext/Cargo.toml
- components/arrow_ext/src/ipc.rs
- components/arrow_ext/src/lib.rs
- proto/protos/remote_engine.proto
- remote_engine_client/Cargo.toml
- remote_engine_client/src/client.rs
- remote_engine_client/src/lib.rs
- server/Cargo.toml
- server/src/grpc/remote_engine_service/mod.rs
Closes #
In current implementation, remote service communication bewteen ceresdb using
avro to serialize RecordBatch. For arrow ecosystem, there is a designated serialization method -- [Arrow IPC](https://github.com/apache/arrow/blob/master/docs/source/format/Columnar.rst#serialization-and-interprocess-communication-ipc)
Some benchmark:
```
cd benchmarks && cargo run --bin ipc -r
Arrow IPC encoded size:1348496
Arrow IPC encode/decode cost:1ms
Avro encoded size:904634
Avro encode/decode cost:284ms
```
Encoded bytes using Arrow IPC will take more space  1348496/904634 = 1.4, but it's more much less time.
After zstd compression, IPC is better than avro in both size and speed.
```
Arrow IPC encoded size:780181
Arrow IPC encode/decode cost:8ms
Avro encoded size:904634
Avro encode/decode …
```
> feat: use arrow-ipc to communicate between remote server and client

- docs/guides/src/operation/system_table.md
- server/src/config.rs
- server/src/consts.rs
- server/src/context.rs
- server/src/grpc/forward.rs
- server/src/grpc/mod.rs
- server/src/grpc/storage_service/mod.rs
- server/src/grpc/storage_service/prom_query.rs
- server/src/grpc/storage_service/query.rs
- server/src/grpc/storage_service/route.rs
- server/src/grpc/storage_service/write.rs
- server/src/handlers/sql.rs
- server/src/http.rs
- server/src/mysql/worker.rs
- server/src/server.rs
Closes #
Currently, it is unreasonable to use tenant as the schema when accessing grpc/http service.
- Add new header `x-ceresdb-schema`;
- For compatibility, `tenant` is still used as schema if `schema` is not set.
User now can use `x-ceresdb-schema` header to set schema instead of `x-ceresdb-access-tenant`.
> support schema header for http/grpc service

- Cargo.lock
- common_util/src/lib.rs
- common_util/src/partitioned_lock.rs
- remote_engine_client/Cargo.toml
- remote_engine_client/src/cached_router.rs
- remote_engine_client/src/channel.rs
- remote_engine_client/src/client.rs
- remote_engine_client/src/config.rs
- remote_engine_client/src/lib.rs
- table_engine/src/remote/model.rs
Closes #
Part of #492 
Now, we do route work in each request, that make performance too bad.
So, this pr add a cached router in remote engine client. 
Add cached router for remote engine client.
None.
Test manually.
> feat: add cached router for remote engine client

- analytic_engine/src/table/metrics.rs
- analytic_engine/src/table/partition.rs
- server/src/grpc/meta_event_service/mod.rs
- server/src/grpc/metrics.rs
- server/src/grpc/remote_engine_service/mod.rs
- server/src/grpc/storage_service/mod.rs
Closes #
Add some metrics for performance troubleshooting.
* Add some metrics for `PartitionTable`.
* Add some metrics for grpc service.
No.
No need.
> chore: add some metrics for PartitionTable and grpc service

- Cargo.lock
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/file_reader.rs
- analytic_engine/src/sst/mod.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/builder.rs
- components/parquet_ext/Cargo.toml
- components/parquet_ext/src/lib.rs
- components/parquet_ext/src/meta_data.rs
- integration_tests/cases/local/03_dml/case_insensitive.result
- integration_tests/cases/local/05_ddl/create_tables.result
- integration_tests/cases/local/06_show/show_create_table.result
Prepare for #495
In order to control how to decode our custom sst file, the object store must be separated from the Parquet SST async reader because the api of object store has no flexibility to introduce another footer after the original file content.
(Actually, this is a similar with #503, which is reverted by #536, and we need to move on to the custom storage format which needs this PR.)
Separate the ObjectStore from the parquet sst async reader.
None.
> refactor: separate object store from async reader

- server/src/error_util.rs
- server/src/grpc/meta_event_service/error.rs
- server/src/grpc/remote_engine_service/error.rs
- server/src/grpc/storage_service/error.rs
- server/src/http.rs
Closes #561
No
New UT: test_remove_backtrace
> fix: truncated error message

- analytic_engine/src/instance/alter.rs
- analytic_engine/src/instance/create.rs
- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/meta/details.rs
- analytic_engine/src/meta/meta_update.rs
- analytic_engine/src/table/data.rs
- wal/src/kv_encoder.rs
- wal/src/manager.rs
- wal/src/message_queue_impl/encoding.rs
- wal/src/message_queue_impl/log_cleaner.rs
- wal/src/message_queue_impl/region.rs
- wal/src/message_queue_impl/region_context.rs
- wal/src/message_queue_impl/snapshot_synchronizer.rs
- wal/src/message_queue_impl/test_util.rs
- wal/src/rocks_impl/manager.rs
- wal/src/table_kv_impl/encoding.rs
- wal/src/table_kv_impl/model.rs
- wal/src/table_kv_impl/namespace.rs
- wal/src/table_kv_impl/table_unit.rs
- wal/src/tests/read_write.rs
Closes #
While tables moved from shards, following bugs will be occurred:
+ manifest will drop, because `shard id` has changed, because now we locate manifest log by table id + shard id.
+ may loading a error last sequence, because we scan the wal data for this now. And while table just be moved to an new shard, no data will be scanned.
Fix above bugs.
None.
Test by ut and manually.
> fix: bugs when table migrate between shards

- table_engine/src/partition/mod.rs
Closes #
At present, the prefix of  sub partition table name is "____",  which is too long.
Change the prefix of sub partition table name to "__".
No.
No need.
> chore: change the prefix of sub partition table name to "__"

- Cargo.lock
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/row_iter/chain.rs
- analytic_engine/src/row_iter/merge.rs
- analytic_engine/src/row_iter/record_batch_stream.rs
- analytic_engine/src/sst/builder.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/header.rs
- analytic_engine/src/sst/meta_data/mod.rs
- analytic_engine/src/sst/mod.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/builder.rs
- analytic_engine/src/sst/parquet/encoding.rs
- benchmarks/src/merge_memtable_bench.rs
- benchmarks/src/merge_sst_bench.rs
- benchmarks/src/sst_bench.rs
- benchmarks/src/sst_tools.rs
- benchmarks/src/util.rs
- components/parquet_ext/Cargo.toml
- components/parquet_ext/src/lib.rs
- components/parquet_ext/src/meta_data.rs
- tools/src/bin/sst-convert.rs
Closes #495
In order to introduce our custom storage format, we choose to put the 4B header into the sst file, which is uniform with the parquet file format.
- Add `SstReadHint` to avoid some other extra io;
- Add `HeaderParser` for supporting detect file format;
- According to the header, decide which reader to use.
None.
Existing.
> feat: detect sst header

- Cargo.lock
- Cargo.toml
- analytic_engine/src/meta/details.rs
- interpreters/src/show_create.rs
- interpreters/src/table_manipulator/meta_based.rs
- meta_client/Cargo.toml
- meta_client/src/types.rs
- server/src/grpc/meta_event_service/mod.rs
- sql/src/partition.rs
- table_engine/Cargo.toml
- table_engine/src/partition/mod.rs
- table_engine/src/partition/rule/df_adapter/mod.rs
- table_engine/src/partition/rule/factory.rs
- table_engine/src/partition/rule/key.rs
Closes #
Refer to #572 
In order to support the case where the partition table is opened by multiple machines in a non-cloud environment, store the partition info of PartitionTable in ceresmeta.
* Pass partition info to ceresmeta.
No.
> feat: pass partition info to ceresmeta when create table

- table_engine/src/partition/rule/df_adapter/extractor.rs
Closes #
We implemented table partition in the last release, but querying partitioned tables through `select in` will lead to the failure to identify the correct partitions, resulting in full table scanning. We need to support select in to improve query performance.
* Implement parsing of `select in` in `filterExtractor`
None.
Pass unit test.
> feat: support querying partition tables through select in

- .pre-commit-config.yaml
- Cargo.toml
- integration_tests/README.md
Closes #
Current release profile is not the best concerning performance, and some options can be configured for better performance, but with slow compiling time and high memory consumption.
- Add `lto=true` and `codegen-units=1` to `release` profile;
- Remove `better-release` profile, and add `release-slim` profile for a smaller and slower binary;
- Fix the bug that `cargo-sort` doesn't work in the precommit;
None.
Current ci.
> feat: improve the release profile and add release-slim profile

- Makefile
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/row_group_filter.rs
Closes #
Some logs are missing when troubleshooting some performance issues.
- Add some logs in the reading sst procedure.
None.
No need to test logs.
> feat: add some logs for reading sst

- .github/codecov.yml
Closes #
Exclude some directories that don't need code coverage.
Ignore following dirs in codecov:
- "benchmarks"
- "integration_test"
- "meta_client"
- "remote_engine_client"
- "wal/src/message_queue_impl"
- "wal/src/table_kv_impl"
No.
No need.
> chore: add codecov.yml to ignore some dirs that don't need code coverage

- Cargo.lock
- server/Cargo.toml
- server/src/context.rs
- server/src/grpc/mod.rs
- server/src/grpc/storage_service/mod.rs
- server/src/grpc/storage_service/write.rs
- server/src/handlers/mod.rs
- server/src/handlers/prom.rs
- server/src/handlers/sql.rs
- server/src/http.rs
- server/src/mysql/worker.rs
- server/src/server.rs
Closes #577
Add remote storage API support in HTTP module.
Yes, add two HTTP API, prometheus users can use them by add following config to their prometheus.yml
```yml
remote_write:
- url: "http://127.0.0.1:5000/prom/v1/write"
remote_read:
- url: "http://127.0.0.1:5000/prom/v1/read"
```
Manually
> feat: implement prom remote storage api

- sql/src/parser.rs
- sql/src/partition.rs
Closes #
Now partition num in table partition is not restricted,  you can set the partition num to an unaccpetable huge number. 
In this pr we make a restriction on it, it cannot be greater than MAX_PARTITION_NUM(1024 now).
User can not set a partition num greater than MAX_PARTITION_NUM while creating partitioned table.
Test by ut.
> feat restrict partition num

- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- integration_tests/Cargo.toml
- integration_tests/cases/local/03_dml/issue-59.result
- integration_tests/cases/local/03_dml/issue-59.sql
- query_engine/src/context.rs
Closes #59
- Enable SingleDistinctToGroupBy
- Bump sqlness to 0.2
- https://github.com/CeresDB/sqlness/releases/tag/v0.2.0
No
CI
> fix: re-enable SingleDistinctToGroupBy

- .github/workflows/dockerhub-publish-nightly.yml
Closes #
Current nightly docker image name is too verbose, this PR make it more readable
- before: nightly-20230201214631-aa306ecb54a5f3863d4041182e2a46d48daad3d0
- after: nightly-20230201-aa306ec
> chore: make nightly image name readable

- server/src/mysql/worker.rs
- server/src/mysql/writer.rs
Closes #596 
Remove `Output` to `Response` convension
No
CI
> fix: remove unnecessary type conversion in MysqlWorker

- server/src/grpc/meta_event_service/mod.rs
Closes #
Now error occured while handling meta's request isn't printed in datanode, that make trouble in debugging.
Print error datanode before returning to meta.
None.
Test manually.
> feat: print error in datanode

- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/meta_data.rs
- analytic_engine/src/sst/parquet/row_group_filter.rs
- analytic_engine/src/sst/parquet/writer.rs
- proto/protos/sst.proto
Closes #
Currently, the bloom filter is only optional on file level, and the bloom filters on column level are still required. However, in some cases, a column bloom filter may be useless, which can be avoided after this PR.
And for compatibility, the version of bloom filter should be introduced.
- Introduce the version of bloom filter. [Breaking Change]
- Make bloom filter optional on column level.
None.
> feat: make bloom filter optional on column level

- server/src/grpc/storage_service/mod.rs
Closes #
I find this bug when write docs https://github.com/CeresDB/docs/pull/25
Primary key already is `tsid, timestamp` by default in SQL, update grpc to follow this.
No 
UT
> primary keys defaults to tsid, timestamp

- components/message_queue/src/kafka/kafka_impl.rs
- server/src/grpc/mod.rs
- server/src/http.rs
- server/src/mysql/error.rs
- server/src/mysql/service.rs
Closes #
When troubleshooting in local my host, I found those logs are useful.
No
This is what looks now
```
2023-02-06 16:07:24.514 INFO [server/src/http.rs:462] HTTP server starts listening on 127.0.0.1:5440
2023-02-06 16:07:24.515 INFO [server/src/server.rs:114] Server start, open local tables
2023-02-06 16:07:24.515 INFO [server/src/server.rs:128] Server start, create default schema if not exist
2023-02-06 16:07:24.516 INFO [server/src/server.rs:131] Server start, start services
2023-02-06 16:07:24.516 INFO [server/src/mysql/service.rs:54] MySQL server starts listening on 127.0.0.1:3307
2023-02-06 16:07:24.516 INFO [server/src/server.rs:138] Server start finished
2023-02-06 16:07:24.516 INFO [server/src/grpc/mod.rs:168] Grpc server starts listening on 127.0.0.1:8831
2023-02-06 …
```
> chore: add logs

- df_operator/src/udfs/time_bucket.rs
- query_engine/src/logical_optimizer/order_by_primary_key.rs
Closes #
In #601 , some `Result`s are handled directly using `unwrap`, which is too rough.
Return error instead of unwrap.
No.
Old tests are covered.
> fix: avoid some unwrap with result

- query_engine/src/executor.rs
- sql/src/provider.rs
- table_engine/src/provider.rs
Closes #622 
ConfigOptions is a structure for passing setting in `datafusion`, which supports passing custom setting.
Use ConfigOptions to transfer custom settings.
No.
Add new test.
> feat: use ConfigOptions to transfer custom settings

- Cargo.lock
- Cargo.toml
- analytic_engine/Cargo.toml
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/sst/meta_data/cache.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/sst/parquet/meta_data.rs
- analytic_engine/src/sst/parquet/mod.rs
- analytic_engine/src/sst/parquet/row_group_filter.rs
- analytic_engine/src/sst/parquet/row_group_pruner.rs
- analytic_engine/src/sst/parquet/writer.rs
- analytic_engine/src/sst/writer.rs
- components/parquet_ext/src/prune/equal.rs
- components/parquet_ext/src/prune/min_max.rs
- proto/protos/sst.proto
Closes #510
See issue above
- Replace bloom with xor8 filter
- Add `Filter` trait to represent different filters
No
Old UT
> feat: replace bloom with xor8 filter

- docs/example-cluster-0.toml
- docs/example-cluster-1.toml
- docs/example-standalone-static-routing.toml
- docs/minimal.toml
- integration_tests/cases/local/config.toml
- server/src/config.rs
- server/src/server.rs
- src/setup.rs
Closes #
It is strange that `DeployMode` is placed in the top-level configuration, it needs to be placed in a sub-configuration.
The `service` section in config is renamed to `server`.
The `service` section in config is renamed to `server`.
> chore: refacor ceresdb config

- Cargo.lock
- Cargo.toml
- docs/minimal.toml
- integration_tests/Cargo.toml
- integration_tests/src/database.rs
- meta_client/src/types.rs
- remote_engine_client/src/cached_router.rs
- router/src/cluster_based.rs
- router/src/lib.rs
- router/src/rule_based.rs
- server/src/grpc/forward.rs
- server/src/grpc/storage_service/mod.rs
- server/src/grpc/storage_service/prom_query.rs
- server/src/grpc/storage_service/route.rs
- server/src/grpc/storage_service/sql_query.rs
- server/src/grpc/storage_service/write.rs
- server/src/handlers/prom.rs
- sql/src/frontend.rs
Closes #
Adopt with latest protobuf
- Extract schema from database field in request context
Yes, SDK will pass request context
CI
> feat: support request context

- wal/src/message_queue_impl/log_cleaner.rs
- wal/src/message_queue_impl/region.rs
- wal/src/message_queue_impl/region_context.rs
Closes #
Now, the order of sync meta snapshot and clean logs in wal onk kafka is unreasonable.
We must ensure that the meta snapshot has been persisted successfully before cleaning the related logs. 
See title.
None.
Test by ut.
> fix: correct the order of sync meta snapshot and clean logs in wal on kafka

- analytic_engine/src/instance/flush_compaction.rs
Closes #650 
Refer to #650 
Update the `flushed_sequence_num` after compaction.
None.
Existing ut.
> fix: update flushed_sequence_num after compaction

- Cargo.lock
- Cargo.toml
- analytic_engine/src/sst/parquet/async_reader.rs
- common_types/src/schema.rs
- components/parquet_ext/src/prune/min_max.rs
- components/parquet_ext/src/reverse_reader.rs
Part of #616 
See #616 
See title.
None.
Test by ut.
> feat: replace column index with id when persisting schema in manifest

- common_types/src/datum.rs
- integration_tests/cases/local/03_dml/issue-637.result
- integration_tests/cases/local/03_dml/issue-637.sql
Closes #637 
Fix the problem of table creation failure mentioned in issue.
* Fix `SqlDataType` convert error.
* Add create table test with `VARBINARY` type. 
User could create table with `VARBINARY` type normally.
Pass integration tests.
> fix: fix varbinary type error

- analytic_engine/src/instance/alter.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/manifest/details.rs
- benchmarks/src/wal_write_bench.rs
- wal/src/lib.rs
- wal/src/manager.rs
- wal/src/tests/read_write.rs
- wal/src/tests/util.rs
Closes #
Currently, the default implementation of `encoder` method in `WalManager` trait is useless because callers can use the `LogBatchEncoder` directly to create such encoder.
Remove the `encode` method defined in `WalManager`.
None.
> refactor: remove encoder method from WalManager

- server/src/config.rs
- server/src/http.rs
Closes #
Make
- All internal apis begin with `debug`
- Admin related apis begin with `admin`
Yes
No need
> chore: normalize http api

- analytic_engine/src/lib.rs
- analytic_engine/src/sst/parquet/meta_data.rs
- components/parquet_ext/src/prune/min_max.rs
Closes #
In #631 xor filter is introduced, however there is one bug on that PR, filter is not built correctly.
- Fix xor filter build
- Add string type testcase in min-max prune
No
Newly added UT.
> fix: xor filter build

- integration_tests/cases/env/cluster/05_ddl/partition_table.result
- integration_tests/cases/env/cluster/05_ddl/partition_table.sql
Closes #
Add partition_table test in `integration_test`.
Add partition_table test in `integration_test`.
No.
> test: add partition_table test in integration_test

- analytic_engine/src/manifest/details.rs
Closes #
Currently, the not found error won't be thrown when access an object file in the aliyun oss by oss sdk, leading to possible panic when restarting.
Take a workaround way (check whether the error message contains '404' or 'not found') to detect the not found error.
None.
Manual test.
> fix: can't recognize aliyun oss NotFoundError when load manifest

- .github/workflows/dockerhub-publish-nightly.yml
Closes #
Separate nightly images from public release images
Change registry to github
- https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
No
No need
> chore: push nightly image to ghcr.io

- .github/workflows/dockerhub-publish-nightly.yml
Fix https://github.com/CeresDB/ceresdb/actions/runs/4310351950
After #684, image publish has errors
```
ceresdb/ceresdb-server:nightly-20230302: server message: insufficient_scope: authorization failed
```
- https://github.com/jiacai2050/ceresdb/actions/runs/4311415390
- https://github.com/jiacai2050/ceresdb/pkgs/container/ceresdb
Ref
- https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
> fix: nightly docker image name

- common_util/src/partitioned_lock.rs
- components/object_store/src/mem_cache.rs
- remote_engine_client/src/cached_router.rs
- remote_engine_client/src/channel.rs
Closes #
The tokio lock has performance issues when hot contention occurs, which may leading to yielding by tokio runtime schedule. That is to say, we should use std lock if the critical section is short or doesn't run across await point.
And the [api docs](https://docs.rs/tokio/1.26.0/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use) of tokio has made a explanation for the choice between tokio lock and std lock.
- Replace the tokio lock with std lock as much as possible.
None.
> refactor: replace tokio lock with std lock in some sync scenarios

- Cargo.lock
- query_engine/Cargo.toml
- query_engine/src/logical_optimizer/type_conversion.rs
Closes #
I found the following query response nothing :
```
curl -H POST 'http://127.0.0.1:5440/sql' -H 'Content-Type: application/json' -d '{
"query": "INSERT INTO demo(`t`, name,value, dat,`time`) VALUES(1667374200022, '\''ceresdb05'\'', 1.0, '\''9999-10-13'\'','\''-23:59:59.999'\'')"
}'
curl -H POST 'http://127.0.0.1:5000/sql' -H 'Content-Type: application/json' -d '{
"query": "select * from demo where t > '\''2023-03-02 15:40:00'\''"
}'
```
Actually it should response:
```
{"rows":[{"tsid":7907694565448534541,"t":1677743400000,"name":"ceresdb01","value":1.0}]}
```
And I found the reason is , according to  https://github.com/apache/arrow-rs/pull/2814, function `string_to_timestamp_nanos` returns a UTC timestamp instead of  local timestamp;
1. When no time zone is specified,  parse it …
> fix:  Parse string without specify time zone to local time stamp

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
Closes #
The rust version used in CI workflows is stale.
Update the rust version defined in CI workflows.
None.
https://github.com/ShiKaiWi/ceresdb/actions/runs/4351144689
> ci: upgrade the Rust version used in CI

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/table/mod.rs
Closes #
Such flush policy is not needed any more.
- Remove table flush policy.
None.
> refactor: remove table flush policy

- analytic_engine/src/row_iter/chain.rs
- analytic_engine/src/row_iter/merge.rs
- analytic_engine/src/sst/file.rs
- analytic_engine/src/tests/compaction_test.rs
Closes #427 #534
- Hold sst reference in merge/chain iterator, so sst cannot be pushed to purge queue when there are queries.
No
CI
> fix: avoid file purge when they are used in queries

- .github/workflows/coverage.yml
Closes #
Modifying non-code files does not require running `code coverage`.
Add `paths-ignore` in code coverage workflow configuration.
```
paths-ignore:
- 'docs/**'
- 'etc/**'
- '**.md'
- '.dockerignore'
- 'docker/**'
```
> chore: modify code coverage trigger conditions

- server/src/grpc/storage_service/write.rs
- sql/src/planner.rs
Closes #
When write to CeresDB via Prometheus remote write, I got following error
```bash
2023-03-08 06:32:48.818 ERRO [server/src/http.rs:520] handle error: Rejection(GRPCWriteError { source: ErrNoCause { code: 400, msg: "tag index 7 is not found in tag_names:[\"env\", \"instance\", \"job\", \"le\", \"space\", \"tenant\", \"type\"], table:cse_rpc_duration_seconds_bucket" } })
2023-03-08 06:32:48.818 ERRO [server/src/http.rs:520] handle error: Rejection(GRPCWriteError { source: ErrNoCause { code: 400, msg: "tag index 7 is not found in tag_names:[\"env\", \"instance\", \"job\", \"le\", \"space\", \"tenant\", \"type\"], table:cse_rpc_duration_seconds_bucket" } })
```
Tag index is hard to debug which tag cause problem.
- Log concrete tag when write failed
No
CI
> chore: add concrete tag to log when write failed

- Cargo.lock
- components/message_queue/Cargo.toml
- components/object_store/Cargo.toml
- components/table_kv/Cargo.toml
- meta_client/Cargo.toml
- wal/Cargo.toml
Closes #662 
Replace native-tls with [rustls](https://github.com/rustls/rustls)
edit Cargo.toml
none
none
> feat: replace native-tls with rustls

- Cargo.lock
- analytic_engine/src/setup.rs
- components/object_store/Cargo.toml
- components/object_store/src/aliyun.rs
Closes #608, close #396
Since OSS is S3-compatible, so we can access OSS via S3 client directly.
- https://www.alibabacloud.com/help/en/object-storage-service/latest/use-aws-s3-sdk-to-access-oss
- Use S3 client in object_store crate to access OSS
No
Manually
> refactor: remove custom oss impl

- Cargo.lock
- integration_tests/src/database.rs
- server/Cargo.toml
- server/src/handlers/error.rs
- server/src/handlers/influxdb.rs
- server/src/handlers/mod.rs
- server/src/http.rs
Part of #682 
- Refactor influxdb http handler to make it more modular  
- Support influxdb line protocol write(convert to gRPC write internal)
No
CI
> feat: add influxdb write

- Cargo.lock
- components/table_kv/Cargo.toml
Closes #
related with https://github.com/oceanbase/obkv-table-client-rs/pull/21
Table client will init timeout when one OB server is invalid, eg, OUT_OF_MEM, SERVER_IS_INIT.
Update OceanBase rust client
Integration test
> fix: Panicked when OceanBase table client is initialing

- analytic_engine/src/compaction/picker.rs
Closes #729 
Refer to #729 
- Avoid being divided by zero.
None.
Add a tests for it.
> fix: div zero when compaction

- server/src/grpc/meta_event_service/error.rs
- server/src/grpc/meta_event_service/mod.rs
Closes #721 
The shard will stop opening if opening a table fails, and no other normal tables will be opened in that shard.
Access to these tables will fail.
* Print warn log if opening a table fails
* Continue to open shard
> fix: failure to open a single table does not interrupt the shard's opening process

- Cargo.lock
- Cargo.toml
- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/storage_options.rs
- analytic_engine/src/table_options.rs
- cluster/src/config.rs
- common_util/Cargo.toml
- common_util/src/config.rs
- common_util/src/toml.rs
- components/logger/src/lib.rs
- components/tracing_util/src/logging.rs
- meta_client/src/meta_impl.rs
- query_engine/src/config.rs
- remote_engine_client/src/config.rs
- router/src/endpoint.rs
- router/src/rule_based.rs
- server/src/config.rs
- server/src/grpc/forward.rs
- server/src/http.rs
- server/src/limiter.rs
- server/src/server.rs
- src/config.rs
- src/setup.rs
Closes #693
Refer to #693
- Support debug api for reviewing the config when running;
Yes. Try the new api `/debug/config`, which will output the runtime config in json format.
Manually. Here is the output of the api:
```
[node]
addr = "127.0.0.1"
zone = ""
idc = ""
binary_version = ""
[server]
bind_addr = "0.0.0.0"
mysql_port = 3307
http_port = 5440
grpc_port = 8831
http_max_body_size = 65536
grpc_server_cq_count = 20
resp_compress_min_length = "4MiB"
auto_create_table = true
[server.forward]
enable = false
thread_num = 4
max_send_msg_len = 20971520
max_recv_msg_len = 1073741824
keep_alive_while_idle = true
[server.forward.keep_alive_interval]
secs = 600
nanos = 0
[server.forward.keep_alive_timeout]
secs = 3
nanos = 0
[server.forward.connect_timeout]
secs = 3
nanos = 0 …
```
> feat: http debug api for config

- sql/src/influxql/mod.rs
- sql/src/influxql/planner.rs
Closes #
Now, we are unable to support from multiple measurements in influxql.
So, we should check and reject them. 
See title.
Will get error information while pass the influxql which selects from multiple measurement.
Test by ut.
> feat: return error while encountering unsupport from in influxql

- analytic_engine/src/instance/create.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/space.rs
- analytic_engine/src/table/data.rs
Closes #
Followup PR of #722
When table open failed when recovery, we should prevent user from creating table with same name, otherwise schema maybe wong, and seq will be reset to 0.
- Add open failed table in Space, and check it when create new table.
No
CI, but I don't test this corner case since I don't know how to mock recovery failure of one table.
> feat: don't allow create table which failed when open

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
Closes #
Modify trigger ci conditions.
* Codecoverage runs every three hours starting at 1:00 UTC.
* Modify the limitation that the CI workflow can only run when it is submitted to the main branch.
No.
No need.
> chore: modify workflows

- Cargo.lock
- Cargo.toml
- analytic_engine/Cargo.toml
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/meta_data/cache.rs
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/sst/parquet/meta_data.rs
- analytic_engine/src/sst/parquet/writer.rs
- analytic_engine/src/sst/writer.rs
- benchmarks/src/sst_tools.rs
- common_util/Cargo.toml
- components/parquet_ext/Cargo.toml
- components/parquet_ext/src/async_arrow_writer.rs
- components/parquet_ext/src/lib.rs
- tools/src/bin/sst-convert.rs
Closes #486 
Refer to #486 
- Introduce `AsyncArrowWriter` in the `parquet_ext` crate;
- Build sst in stream way using `AsyncArrowWriter`;
None.
> feat: build sst in stream way

- Cargo.lock
- catalog_impls/Cargo.toml
- catalog_impls/src/table_based.rs
- interpreters/Cargo.toml
- server/src/handlers/influxdb.rs
- server/src/lib.rs
- src/setup.rs
- table_engine/src/lib.rs
- table_engine/src/memory.rs
- table_engine/src/proxy.rs
Closes #
Now, rust-analyzer will report cyclic dependecy like:
```
[ERROR project_model::workspace] cyclic deps: server(CrateId(478)) -> interpreters(CrateId(256)), alternative path: interpreters(CrateId(256)) -> catalog_impls(CrateId(97)) -> server(CrateId(478))
``` 
We should fix it.
Move table engine proxy to table_engine crate.
Rust-analyzer will not compare cyclic dependency now.
Test by ut.
> fix: move table engine proxy to table_engine crate

- .github/workflows/ci.yml
- Cargo.lock
- sql/Cargo.toml
Closes #
* Upgrade influxql-logical-planner version.
* Add merge_group in CI.  PRs in the merge queue need to wait for CI completion before they can be merged.
No.
No need.
> chore: upgrade influxql-logical-planner version and modify CI setting

- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/lib.rs
- common_types/src/row/mod.rs
- common_types/src/schema.rs
Closes #
Currently, one large write request may lead to one large WAL log, which is not friendly for some wal implementations.
- Support split write table request to multiple batches.
None.
New unit tests and existing integraion tests.
> feat: support split write request to batches for small wal logs

- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/row_iter/dedup.rs
- analytic_engine/src/row_iter/merge.rs
- analytic_engine/src/row_iter/mod.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/writer.rs
- benchmarks/src/config.rs
- benchmarks/src/merge_memtable_bench.rs
- benchmarks/src/merge_sst_bench.rs
- benchmarks/src/parquet_bench.rs
- benchmarks/src/sst_bench.rs
- benchmarks/src/sst_tools.rs
- benchmarks/src/util.rs
- tools/src/bin/sst-convert.rs
Closes #735
Currently, streaming reading sst has already been supported. However, the max record batches in flight is not configurable, which is hard-coded as 1024. This pr makes it configurable, especially for normal query and compaction reading.
- Make `scan_max_record_batches_in_flight` configurable;
- Refactor the implementation for Stream based on a future method;
A new config options is provided called `scan_max_record_batches_in_flight.
> feat: configurable record batches in flight

- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/setup.rs
- common_util/src/config.rs
- server/src/server.rs
> fix: rename as_bytes to as_byte in ReadableSize (#428)

- Cargo.lock
- integration_tests/cases/env/local/influxql/basic.result
- server/Cargo.toml
- server/src/handlers/error.rs
- server/src/handlers/influxdb.rs
- server/src/handlers/query.rs
- sql/src/influxql/planner.rs
Closes #
Now, we return the influxql result using our inner format rather than influxdb format, we should modify it to the latter.
Convert the influxql result to influxdb format.
Get the influxdb compatible result when using influxql to query data. 
Test by ut.
> feat: convert the influxql result using influxdb format

- .pre-commit-config.yaml
- scripts/check-license.sh
- scripts/license-header.txt
Closes #
Update license insert, add `use-current-year`
- When edit old file, pre-commit will update license header to `2022-{current-year}`
Manually.
This is what other project does:
- https://github.com/facebook/rocksdb/blob/main/table/format.cc
- https://github.com/tikv/tikv/blob/master/src/coprocessor_v2/raw_storage_impl.rs
It seems year format is not very strict, and we can define format used in CeresDB.
> chore: fix insert-license pre-commit

- Cargo.lock
- Cargo.toml
- analytic_engine/Cargo.toml
- analytic_engine/src/instance/read.rs
- analytic_engine/src/row_iter/mod.rs
Closes #
Replace unfold with async-stream.
Replace unfold with async-stream.
No.
Integration test.
> chore: replace unfold with async-stream

- integration_tests/src/database.rs
- server/src/handlers/influxdb.rs
- server/src/handlers/query.rs
- server/src/http.rs
Closes #
See title.
And after doing this, we can connect ceresdb to grafana with inluxdb protocol.
See title.
Can use the same influxdb1.8 compatible query api to query data from ceresdb.
Test manually.
> feat: make influxql query interface compatible with influxdb1.8

- cluster/src/config.rs
- server/src/config.rs
- server/src/schema_config_provider/config_based.rs
- src/setup.rs
Closes #
Simplify schema config setting. If we don't provide a define one, we need to set schema config one by one, something like
```
[[cluster_deployment.topology.schema_shards]]
schema = 'public_0'
default_timestamp_column_name = 'time'
[[cluster_deployment.topology.schema_shards.shard_views]]
shard_id = 0
[cluster_deployment.topology.schema_shards.shard_views.endpoint]
addr = '127.0.0.1'
port = 8831
[[cluster_deployment.topology.schema_shards.shard_views]]
shard_id = 1
[cluster_deployment.topology.schema_shards.shard_views.endpoint]
addr = '127.0.0.1'
port = 8831
```
This is very inconvient.
- Add default schema config in server
```toml
[server.default_schema_config]
default_timestamp_column_name = "time"
```
- Update bind_addr to 127.0.0.1, which is more safe than before.
No
Manully
> feat: add default schema config

- server/src/http.rs
Closes #
Current influxql handler can't process get request correctly
```sh
curl -i -XPOST "http://localhost:5440/influxdb/v1/write" --data-binary '
fff,tag1=t1,tag2=t2 field1=90,field2=100 1679994647000
fff,tag1=t1,tag2=t2 field1=91,field2=101 1679994648000
fff,tag1=t11,tag2=t22 field1=90,field2=100 1679994647000
fff,tag1=t11,tag2=t22 field1=91,field2=101 1679994648000
'
curl  -G 'http://localhost:5440/influxdb/v1/query' --data-urlencode 'q=select * from fff'
```
Command above will throw `Rejection(LengthRequired)` error when query.
- Remove body limit for influxql handler 
No
CI
> fix: remove body limit for influxql request

- .github/workflows/ci.yml
- integration_tests/Makefile
- integration_tests/sdk/java/pom.xml
- integration_tests/sdk/java/src/main/java/io/ceresdb/App.java
- integration_tests/sdk/java/src/main/resources/log4j2.xml
Part of #685
- Add java sdk tests
No
CI
> feat: add java integration tests

- server/src/grpc/storage_service/mod.rs
Closes #
Route in grpc service use read_runtime.
Route in grpc service use read_runtime.
No.
No need.
> chore: route use read_runtime

- Cargo.lock
- Cargo.toml
- common_types/src/schema.rs
- server/src/grpc/metrics.rs
- server/src/grpc/remote_engine_service/mod.rs
- table_engine/src/remote/model.rs
Closes #
The schema of partition table will be obtained from the first sub-table, so a remote engine is needed to implement the table information access interface.
Impl getTableInfo in remoteEngine service.
No.
Testing will be conducted with the partition table, and it will be used internally by the engine without affecting external users for the time being.
> feat: impl getTableInfo in remoteEngine service

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- integration_tests/Makefile
- integration_tests/sdk/rust/Cargo.toml
- integration_tests/sdk/rust/src/main.rs
Closes #
Add integration test for rust sdk.
see title.
None.
None.
> feat: add rust sdk test

- components/object_store/src/disk_cache.rs
Closes #769 
Error will be thrown breaking execution, when data in the disk cache is corrupted, which is unavoidable.
- Report cache miss when cache content is corrupted instead.
None.
The new unit test for it is added.
> fix: avoid error when disk cache miss

- common_types/src/record_batch.rs
- components/arrow_ext/src/ipc.rs
- server/src/proxy/grpc/sql_query.rs
Closes #
Currently, empty record batch will be generated by the datafusion, and will be sent to the client too. Avoid the empty record batch because it is a waste for both server and client.
- Avoid encoding the empty record batch into the `SqlQueryResponse`;
1. The client won't receive any empty record batch;
2. The schema information won't be sent to the client if the whole query response is empty;
As for the second cheanges, all the sdks has been tested for the compatibility.
> fix: avoid send empty record batch to client

- analytic_engine/src/instance/open.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/table/data.rs
- analytic_engine/src/tests/table.rs
- analytic_engine/src/tests/util.rs
- catalog/src/schema.rs
- catalog_impls/src/table_based.rs
- common_types/src/table.rs
- interpreters/src/table_manipulator/catalog_based.rs
- server/src/grpc/meta_event_service/mod.rs
- system_catalog/src/sys_catalog_table.rs
- table_engine/src/engine.rs
Closes #
Delete useless cluster version in engine.
Delete useless cluster version in engine.
No.
Old tests have covered.
> chore: remove useless cluster_version

- Makefile
- scripts/run-tsbs.sh
Closes #
In order to prepare for nightly running tsbs on a server, the run-tsbs script should more configurable.
- Expose more config, including log directory, ceresdb grpc addr and so on;
- Record the ceresdb pid and kill it after finished;
None.
It has been used on the https://github.com/ShiKaiWi/ceresdb-benchmark
> refactor: make tsbs more configurable

- wal/src/table_kv_impl/namespace.rs
Closes #
It occurs error when dropping expired wal table. 
```
2023-04-04 12:08:40.363 ERRO [components/table_kv/src/obkv.rs:439] Failed to drop table, table_name:wal_wal_20230317000000_000003, err:Table not dropped, table:wal_wal_20230317000000_000003.
Backtrace:
0 <snafu::backtrace_shim::Backtrace as snafu::GenerateBacktrace>::generate::hfa679d2c718d0b38
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.6.10/src/backtrace_shim.rs:15
table_kv::obkv::TableNotDropped<__T0>::build::hf3dea826ebd60599
/xunming/ceresdb/components/table_kv/src/obkv.rs:23
table_kv::obkv::TableNotDropped<__T0>::fail::hfb145a30c5888703
/xunming/ceresdb/components/table_kv/src/obkv.rs:23
table_kv::obkv::ObkvImpl::try_drop_kv_table::h7edb8769b0ed116c
/xunming/ceresdb/components/table_kv/src/obkv.rs:374 …
```
> fix: avoid break when drop wal table failed

- .github/workflows/ci.yml
- Makefile
- integration_tests/Makefile
- integration_tests/mysql/basic.sh
- server/src/mysql/builder.rs
- server/src/mysql/error.rs
- server/src/mysql/service.rs
- server/src/mysql/worker.rs
- server/src/server.rs
Closes #
After #803, mysql protocol is broken
```bash
2023-04-06 15:04:39.811 ERRO [server/src/mysql/worker.rs:99] MysqlWorker on_query failed. err:Failed to create request context, err:Missing router.   
Backtrace:                                                                                                                                            
0 backtrace::backtrace::libunwind::trace::h02fd638a62f821d3                                                                                          
/Users/jiacai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/libunwind.rs:93                                       
backtrace::backtrace::trace_unsynchronized::h21f1d53b167bd280 …
```
> fix: add router when build request context for mysql

- analytic_engine/src/lib.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/setup.rs
- analytic_engine/src/tests/util.rs
- server/src/http.rs
- server/src/server.rs
- wal/src/manager.rs
- wal/src/rocks_impl/config.rs
- wal/src/rocks_impl/manager.rs
- wal/src/rocks_impl/mod.rs
- wal/src/tests/util.rs
Closes #
Max background jobs is hard-code, expose an option to configure this.
- Add new options for background jobs.
- Add new http endpoint for debugging `GET /debug/stats`, this require following config:
```
[analytic.wal.data_namespace]
enable_statistics = true
max_background_jobs = 8
```
No
No need.
> feat: expose rocksdb background jobs option

- Cargo.lock
- integration_tests/Cargo.toml
- integration_tests/Makefile
- integration_tests/README.md
- integration_tests/src/main.rs
Closes #
Run all tests in local env is time-consuming, so add this filter.
- Add env_filter in integration tests.
No
Manually
> feat: integration test support env filter

- Cargo.lock
- Cargo.toml
- cluster/Cargo.toml
- components/logger/Cargo.toml
- components/object_store/Cargo.toml
- components/parquet_ext/Cargo.toml
- components/profile/Cargo.toml
- remote_engine_client/Cargo.toml
- server/Cargo.toml
- wal/Cargo.toml
- wal/src/rocks_impl/manager.rs
Closes #818
After upgrade cmake to 2.26, it can't build because of the failure of compiling rocksdb.
- Upgrade the rust-rocksdb to keep the latest with the version used by tikv.
- Remove unused dependancies.
None.
> feat: upgrade rust-rocksdb

- Cargo.lock
- integration_tests/cases/env/local/influxql/basic.result
- integration_tests/cases/env/local/influxql/basic.sql
- query_engine/Cargo.toml
- query_engine/src/context.rs
- query_engine/src/df_planner_extension/mod.rs
Closes #
Fill syntax is part of influxql.
- Bump iox, which contains changes to support ms time unit
- Register GapFill datafusion extension
Yes, fill is supported, like this:
```sql
SELECT count(water_level) FROM "h2o_feet"
where time < 1439828400000ms
group by location, time(5m) fill(1)
```
And we can query influxql in grafana directly.
New integration testcase
> feat: influxql support fill syntax

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/setup.rs
- analytic_engine/src/tests/util.rs
- benchmarks/src/wal_write_bench.rs
- docs/example-standalone-static-routing.toml
- server/src/grpc/mod.rs
- server/src/http.rs
- server/src/mysql/service.rs
- server/src/mysql/worker.rs
- src/config.rs
- src/setup.rs
- table_engine/src/engine.rs
- wal/src/message_queue_impl/namespace.rs
- wal/src/message_queue_impl/wal.rs
- wal/src/table_kv_impl/mod.rs
- wal/src/table_kv_impl/namespace.rs
- wal/src/table_kv_impl/table_unit.rs
- wal/src/table_kv_impl/wal.rs
- wal/src/tests/util.rs
Closes #
Currently, the `bg_runtime` is used for many scenarios, e.g. grpc service, hotspot recording, and so on. And `bg_runtime` is also used heavily by compaction, that is to say, the other scenarios will be hungry to run, leading to blocking in the key paths, e.g. write procedure.
- Replace the bg_runtime with default_runtime and compact_runtime.
The runtime config will be updated.
By manually tests, it is found written rows per second changes from 4K(1 bg thread) -> 100K(1 default thread + 1 compact thread).
> feat: replace bg runtime with default and compact runtime

- analytic_engine/src/instance/write.rs
- analytic_engine/src/table/metrics.rs
Closes #
In order to improve the write performance, some metrics for the write procedure are necessary but missing now.
- Add metrics for all stages during the write procedure.
None.
Manual test.
This is what the metrics looks like:
```
table_write_duration_bucket{type="encode",le="0.01"} 32
table_write_duration_bucket{type="encode",le="0.02"} 43
table_write_duration_bucket{type="encode",le="0.04"} 45
table_write_duration_bucket{type="encode",le="0.08"} 45
table_write_duration_bucket{type="encode",le="0.16"} 45
table_write_duration_bucket{type="encode",le="0.32"} 45
table_write_duration_bucket{type="encode",le="0.64"} 45
table_write_duration_bucket{type="encode",le="1.28"} 45
table_write_duration_bucket{type="encode",le="2.56"} 45
table_write_duration_bucket{type="encode",le="5.12"} 45 …
```
> feat: add metrics for write procedure

- server/src/handlers/mod.rs
- server/src/http.rs
- server/src/proxy/grpc/prom_query.rs
- server/src/proxy/http/mod.rs
- server/src/proxy/http/prom.rs
Closes #
Impl prom query with proxy.
* Impl prom query with proxy.
* Support forwarding prom query.
No.
Manual testing and CI.
> feat: impl prom query with proxy

- analytic_engine/src/tests/util.rs
- partition_table_engine/src/lib.rs
- partition_table_engine/src/partition.rs
- remote_engine_client/src/cached_router.rs
- remote_engine_client/src/channel.rs
- server/src/server.rs
- src/config.rs
- src/setup.rs
- table_engine/src/engine.rs
Closes #
Currently, the write runtime is also used for the remote engine client's network io, which may lead to extra time cost because of the scheduling overhead.
Use separate runtime for the io operations.
New config option `io_thread_num` in the runtime.
Manually tests.
> fix: improve remote write performance by using separate runtime

- scripts/run-tsbs.sh
Closes #
Currently, TSBS only supports default params for writing and reading. But different machines may prefer different params because of their different resources.
Support two more params for TSBS:
- WRITE_BATCH_SIZE
- WRITE_WORKER_NUM
None.
test by manual.
> feat: tsbs support more write options

- Cargo.lock
- Cargo.toml
- partition_table_engine/src/lib.rs
- partition_table_engine/src/partition.rs
- remote_engine_client/src/cached_router.rs
- remote_engine_client/src/client.rs
- remote_engine_client/src/lib.rs
- server/src/grpc/metrics.rs
- server/src/grpc/remote_engine_service/mod.rs
- server/src/server.rs
- table_engine/src/remote/mod.rs
- table_engine/src/remote/model.rs
- table_engine/src/table.rs
Closes #
Support `write_batch` in  `RemoteEngine`(using for partitioned table), that will send all write requests in the same node in once to reduce the rpc calls.
+ Add `write_batch` in `RemoteEngineClient`.
+ Add `write_batch` in `RemoteEngineService`.
+ Modify `write` in `PartitionTable` to make use of `write_batch` method. 
None.
Test by integration tests.
> feat: support write batch in remote engine

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/alter.rs
- analytic_engine/src/instance/close.rs
- analytic_engine/src/instance/create.rs
- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/serial_executor.rs
- analytic_engine/src/instance/serializer.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/space.rs
- analytic_engine/src/table/data.rs
- analytic_engine/src/table/mod.rs
- analytic_engine/src/table/version.rs
- common_util/src/runtime/mod.rs
- components/skiplist/src/list.rs
- server/src/grpc/mod.rs
- server/src/handlers/query.rs
- system_catalog/src/sys_catalog_table.rs
- table_engine/src/engine.rs
Prepare for #800 
Currently, the operations on tables are serialized by the worker queue, which has a serious disadvantage -- no work steal, which may leading to hungry of some tables' operations because of one big table.
This PR will replace the worker queue with a simple lock for every table.
- Replace the worker queue with lock for every table;
Remove the configs for the write workers.
> feat: serialize table operations by lock rather than queue

- analytic_engine/src/instance/create.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/serial_executor.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/table/data.rs
Closes #
Currently, once the flush is triggered by reaching the mutable_limit (7/8 write buffer size), the next write must be stalled because the flush trigger condition is still valid, and this is unreasonable because the mutable_limit is used to avoid write stall rather than impose write stall.
- For the flush case where the mutable limit is reached, flush won't be triggered if the table is in flushing;
- Adjust the mutable limit to 5/8, to trigger an earlier flush;
None.
> feat: avoid frequent write stall

- analytic_engine/src/table/data.rs
- scripts/run-tsbs.sh
Closes #
A bug in the run_tsbs.sh
- Fix the wrong syntax of the default write batch size in `run_tsbs.sh`.
None.
Manually.
> fix: wrong default write batch size for run_tsbs

- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/setup.rs
- analytic_engine/src/space.rs
- analytic_engine/src/sst/file.rs
- analytic_engine/src/table/version.rs
Closes #
Part of #799 
Make snapshot able to get snapshot from table data.
Make snapshot able to get snapshot from table data.
None.
Test by ut.
> feat: refactor manifest to get snapshot in memory

- Cargo.lock
- components/table_kv/Cargo.toml
Closes #
Currently the connection will be closed when querying to ob server with new version. To address this issue, so we need to  bump obkv client version.
see detail in:https://github.com/oceanbase/obkv-table-client-rs/pull/38
bump obkv client version  
Have been tested in [Oceanbase client repo](https://github.com/oceanbase/obkv-table-client-rs/pull/38)
> chore: bump obkv client version

- src/bin/ceresdb-server.rs
- src/config.rs
Closes #
Currently, the node address reported to CeresMeta is not allowed to be a domain name, but it is necessary for k8s deployment.
- Allow the node address reported to CeresMeta to be anything.
None.
> feat: support domain name as the ceresdb node addr

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/row_iter/merge.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/file.rs
- analytic_engine/src/sst/manager.rs
- analytic_engine/src/sst/parquet/row_group_pruner.rs
- analytic_engine/src/sst/parquet/writer.rs
- analytic_engine/src/table/version.rs
- analytic_engine/src/table/version_edit.rs
- analytic_engine/src/tests/compaction_test.rs
- benchmarks/src/merge_sst_bench.rs
- benchmarks/src/sst_tools.rs
- common_util/src/lib.rs
- tools/src/bin/sst-convert.rs
Closes #
Currently all sst are in level0, and we find that when flush memtable-> sst0,
build parquet filter cost lots of CPU, which affect write throughout indirectly.
Introduce SST at level 1, this is how data is moved between different components:
- memtable -> level0
- level0 -> level1
- level1 -> level1
Flush memtable will only output sst at level 0, and it will skip parquet filter building. 
Fow now, compaction strategy is same for 0->1 and 1->1, later we need to investigate different strategy for them.
No
CI
> feat: compaction support different level

- query_frontend/src/frontend.rs
- query_frontend/src/influxql/planner.rs
- query_frontend/src/lib.rs
- query_frontend/src/planner.rs
- query_frontend/src/provider.rs
- query_frontend/src/tests.rs
- server/src/handlers/query.rs
- server/src/proxy/http/query.rs
Closes #
Part of #830 
Now, we collect and keep all tables in influxql planner even though it is unused.
It is wasteful to do this. So in this pr, I make it just do such works on demand.
+ Add `all_tables` method in `MetaProvider`.
+ Just call `MetaProvider::all_tables` to get tables while they are actually needed(such as while influxql's `SchemaProvider::table_names` is called).
None.
Test by ut.
> feat: only collecting all tables on demand in influxql planner

- cluster/src/cluster_impl.rs
- cluster/src/config.rs
- cluster/src/shard_lock_manager.rs
- server/src/grpc/meta_event_service/mod.rs
- src/setup.rs
Closes #
There are some issues remaining in the #706.
- Address the comment reviews left in #706.
None.
> refactor: shard lock module

- server/src/proxy/http/prom.rs
- server/src/proxy/http/query.rs
Closes #856
Support querying partition table in prom query and http query.
* Support querying partition table in prom query.
* Support querying partition table in prom query http query.
No.
> feat: support querying partition table in prom query and http query

- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/lib.rs
Closes #
After #822, the compaction triggered by flush will take place less frequently. And #861, the filter won't be built for level0 sst, so the query performance may drop a little if we don't adjust the compaction frequency.
- Rename the config name `compaction_config` to `compaction`, which is more elegant;
- Adjust the interval of periodic compaction from 30m to 5m;
The config name `compaction_config` is replaced with `compaction`.
Manually.
> feat: rename the compaction_config to compaction and adjust interval

- Cargo.lock
- Cargo.toml
- common_types/src/tests.rs
- query_frontend/Cargo.toml
- query_frontend/src/frontend.rs
- query_frontend/src/planner.rs
- query_frontend/src/promql.rs
- query_frontend/src/promql/convert.rs
- query_frontend/src/promql/datafusion_util.rs
- query_frontend/src/promql/error.rs
- query_frontend/src/promql/remote.rs
- query_frontend/src/tests.rs
- server/Cargo.toml
- server/src/proxy/http/prom.rs
Related to #855
Currently prom requests is implemented based on sql, but there are some shortcomings:
1. Timestamp is hard-coded
2. Can't select column other than `value`
- Convert prom request to datafusion plan directly 
- Add special label `__ceresdb_field__` to set field column other than `value`
No
CI and manually
> refactor: implement prom remote query by convert to datafusion plan directly

- remote_engine_client/src/client.rs
Closes #
Some situations are not considered in remote client's evict logic.
See title.
None.
Test by integration test.
> fix: fix evict logic in remote client

- proxy/src/lib.rs
Closes #
Fix the problem that the partition table in the proxy memory was not dropped after the partition table was dropped.
Fix the problem that the partition table in the proxy memory was not dropped after the partition table was dropped.
No.
> fix: drop partition table

- wal/src/table_kv_impl/encoding.rs
- wal/src/table_kv_impl/namespace.rs
Closes #
The wal related table name in table_kv based wal is strange.
Rename related tables names.
BREAKING CHANGE, users using obkv based wal will lose the wal data.
Test by ut.
> chore!: rename table name in table_kv based wal

- .github/workflows/ci.yml
Closes #
The running time of `udeps` is too long, so it is suitable to put it in CI.
Remove udeps in CI.
No.
No need.
> chore: remove udeps in CI

- .github/pull_request_template.md
Closes #
We plan to use the PR description as the extended commit message, but the explanation in the PR description should not be included.
Remove the explanation in the PR tmpl.
None.
No need.
> fix: remove explanation in PR tmpl

- proxy/src/grpc/write.rs
- proxy/src/http/prom.rs
Closes #
Implement forwarding prom write.
Implement forwarding prom write.
No.
> feat: impl forwarding prom write

- proxy/src/http/prom.rs
- proxy/src/influxdb/types.rs
Closes #
For one metric, when tag name is different, it cannot be in same write request
Use `(metric, tag_names)` as group key when new write requests
No
CI and manually
> fix: new multiple write requests when tag names are different

- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/table/mod.rs
- common_types/src/row/mod.rs
- table_engine/src/engine.rs
- table_engine/src/table.rs
Closes #
Currently, massive small write requests will lead to bad performance because of the lock contention for table writes. By buffering the write requests blocked by the write lock into a wait queue, these small write requests may be merged, leading to a much better performance.
- Buffer the write requests blocked by the write lock and merge and write them when another write worker acquires the write lock.
None.
Existing tests and the newly added unit tests.
> feat: support merge small write requests

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/serial_executor.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/lib.rs
Closes #
Currently, when a flush table operation fails, write requests would aways fail. Perhaps we should consider flushing the memory table again when the next write request coming to address this issue.
* flush memory table again after flush failed
None
> chore: reflush memory tables after flush failed

- Cargo.lock
- Cargo.toml
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/sst/parquet/hybrid.rs
- common_types/src/column.rs
- common_types/src/column_schema.rs
- common_types/src/datum.rs
- common_types/src/record_batch.rs
- common_types/src/schema.rs
- components/parquet_ext/src/prune/min_max.rs
- integration_tests/build_meta.sh
- integration_tests/cases/common/dummy/select_1.result
- proxy/src/influxdb/types.rs
- query_engine/Cargo.toml
- query_engine/src/context.rs
- query_engine/src/df_planner_extension/mod.rs
- query_engine/src/logical_optimizer/type_conversion.rs
- query_frontend/Cargo.toml
- query_frontend/src/planner.rs
Related with #867
- Bump datafusion to 24
- Bump Arrow/Parquet to 38
- Bump sqlparser to 0.33
No
CI
> chore: bump datafusion

- integration_tests/cases/env/cluster/ddl/partition_table.result
- integration_tests/cases/env/cluster/ddl/partition_table.sql
- meta_client/src/lib.rs
- meta_client/src/types.rs
- proxy/src/forward.rs
- proxy/src/lib.rs
- proxy/src/write.rs
- router/src/cluster_based.rs
- router/src/lib.rs
- router/src/rule_based.rs
Closes #846 
Fix bug in #846.
Support automatic table creation in proxy module.
No.
> fix: auto create table

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/open.rs
Closes #
When restart server, there are too many logs about replay
```
2023-05-17 08:17:58.267 INFO [analytic_engine/src/instance/open.rs:272] Instance replay table log entries begin, table:meta_peers_refresh_counter, table_id:TableId(314), sequence:6103359                                            2023-05-17 08:17:58.268 INFO [analytic_engine/src/instance/open.rs:350] Instance replay table log entries end, table:meta_peers_refresh_counter, table_id:TableId(314), last_sequence:6103359                                         2023-05-17 08:17:58.277 INFO [analytic_engine/src/instance/open.rs:272] Instance replay table log entries begin, table:meta_peers_refresh_counter, table_id:TableId(314), sequence:6103859                                           
2023-05-17 08:17:58.278 INFO …
```
> chore: adjust log level

- integration_tests/cases/env/cluster/ddl/partition_table.result
- integration_tests/cases/env/cluster/ddl/partition_table.sql
- router/src/cluster_based.rs
- router/src/lib.rs
Closes #
Support for disabling router cache.
* Add `enable` in router config.
No.
CI.
> feat: support for disabling router cache

- Cargo.lock
- integration_tests/Cargo.toml
- integration_tests/src/database.rs
Closes #
Proxy module already supports query without passing `table_name`.
* Remove table_name `parser` in integration-test.
> chore: remove parse table name in integration-test

- .github/pull_request_template.md
Closes #
To utilize the PR description for commit message, the description should be made more concise.
Make the PR tmpl more concise.
None.
No need.
> feat: simplify the PR tmpl

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/sst/file.rs
Closes #
- Adjust logs to make it more readable.
- `trim_to_threshold` respect `max_input_sstable_size`.
Manually
> fix: limit input sst size when compact for old bucket

- proxy/src/lib.rs
- proxy/src/write.rs
- server/src/server.rs
- src/setup.rs
Closes #
Fix the bug that the automatic table creation will cause repeated table creation in the deployment mode without `ceresmeta`.
CI and TSBS.
> fix: auto_create_table without ceresmeta

- analytic_engine/src/engine.rs
- catalog/src/table_operator.rs
- cluster/src/cluster_impl.rs
- cluster/src/lib.rs
- cluster/src/shard_lock_manager.rs
- cluster/src/shard_tables_cache.rs
- router/src/cluster_based.rs
- server/src/grpc/meta_event_service/mod.rs
- server/src/grpc/meta_event_service/shard_operation.rs
Closes #
- Remove the shard from the cluster topology only after it is closed successfully.
- Freeze the shard to avoid any updates on it before close the shard, and do shard close with the tables of the frozen shard.
- Add some logs for open/close shards.
Test with CeresMeta, and trigger closing shard.
> fix: remove shard from cluster topology after shard closed

- common_util/src/partitioned_lock.rs
related with #914 
- Modify the type of `partitions` in `PartitionedMutex` and `PartitionedRwLock`.
- Fix the bug that multiple partitions use the same lock.
Unit tests under the same file.
> refactor: use binary bits to determine the number of partitions

- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/compaction/scheduler.rs
Closes #
- Compact schedule interval change to 30s
- Compact memory estimate change to sst size
New UT `test_time_window_newest_bucket`
> fix: ensure pick at least 2 files for compaction

- integration_tests/sdk/go/issue-779.go
- integration_tests/sdk/go/util.go
- proxy/src/write.rs
- query_frontend/src/planner.rs
Closes #
Refactor find new columns to improve write performance.
* Skip building column schema when columns already exists.
TSBS.
|                | auto_create_table = false | auto_create_table = true| performance loss |
|:--------:|:-------------------------:|:------------------------:|:-----------------:|
| Before    |       171273.03 rows/s        |         152436.35 rows/s    |        11%                |
| After       |       171699.82 rows/s        |        164791.73  rows/s    |       4.1%                |
> refactor: find new columns to improve write performance

- Cargo.lock
- common_types/Cargo.toml
- common_types/src/hash.rs
- common_util/src/partitioned_lock.rs
Closes #921 
Replace the hash algorithm from `DefaultHasher` to `ahash` for better performance in partition lock.
Time cost to compute hash on a 10-char string:
- DefaultHash: 10: 33.6364 ns
- ahash: 10: 19.0412 ns
- murmur3: 10: 33.0394 ns
> chore: replace DefaultHash with AHasher

- proxy/src/http/prom.rs
- proxy/src/http/sql.rs
- proxy/src/influxdb/mod.rs
- proxy/src/lib.rs
- proxy/src/read.rs
- server/src/grpc/storage_service/mod.rs
Closes #
The http api supports querying sub-tables of partition table.
Manual test.
> fix: http query support querying partitioned sub-table

- common_types/Cargo.toml
- common_types/src/hash.rs
- common_util/src/partitioned_lock.rs
Closes #921 
Be careful not to use `ahash` for non-memory scenarios.
Note that when an upstream dependency also references the same library, their `FEATURES` are merged.
Reference: 
[1] https://github.com/tkaitchuck/aHash/blob/master/README.md?plain=1#L22
> chore: add hint about `ahash` usage

- Cargo.lock
- Makefile
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/meta_data.rs
- common_util/Cargo.toml
- common_util/src/byte.rs
- common_util/src/lib.rs
- common_util/src/time.rs
- components/parquet_ext/src/meta_data.rs
- tools/Cargo.toml
- tools/src/bin/sst-metadata.rs
Closes #
When debug compaction related issue, it's helpful to check sst metadata.
- Add new cli tool `sst-metadata`.
Manually
```
$ ./target/release/sst-metadata --dir ~/bench/data/store/2/2199023255817/
Location:2/2199023255817/51491.sst, time_range:[2022-09-05 10:00:00, 2022-09-05 12:00:00), max_seq:305309, size:440.000M, metadata:55.219M, kv:51.565M, filter:38.470M, row_num:14480000
Location:2/2199023255817/53873.sst, time_range:[2022-09-05 10:00:00, 2022-09-05 12:00:00), max_seq:319320, size:666.969M, metadata:83.759M, kv:78.198M, filter:58.342M, row_num:21960000
Location:2/2199023255817/51538.sst, time_range:[2022-09-05 10:00:00, 2022-09-05 12:00:00), max_seq:305001, size:1161.511M, metadata:145.723M, kv:136.025M, filter:101.489M, row_num:38200000
Location:2/2199023255817/53269.sst, …
```
> feat: add sst-metadata tool to query sst metadata

- Makefile
add `cargo clippy --fix` to Makefile
> chore: add `cargo clippy --fix` to Makefile

- common_types/src/hash.rs
- common_util/src/partitioned_lock.rs
- components/object_store/src/mem_cache.rs
Ralated #914 
Add `build_fixed_seed_ahasher` to build fixed  seeds ahasher.
Use PartitionedMutex in `MemCache`.
UT.
> refactor: use partition lock for memory cache

- cluster/src/shard_lock_manager.rs
- common_util/src/runtime/mod.rs
Closes #
When shard lock is expired, the `on_expired` callback will be executed in the shard lock lease keepalive background task, and the callback will stop the background task and wait for its finish, leading to a deadlock. This change set fixes it by avoid waiting for the background task to finish.
Test it by these steps:
- Start ceresmeta and ceresdb;
- Wait all the shards to open on the ceresdb;
- Stop ceresmeta to let the shard lock lease be expired;
- Observe whether the shard lock can be revoked successfully.
> fix: deadlock when stop keepalive bg task

- analytic_engine/src/compaction/scheduler.rs
Closes #
The condition for checking whether to flush a table whose last flush time is too old is wrong.
> fix: too frequent flush

- analytic_engine/src/instance/write.rs
- analytic_engine/src/table/metrics.rs
- analytic_engine/src/table/mod.rs
- server/src/grpc/remote_engine_service/mod.rs
Closes #
Currently, the writer for the first request in the pending write queue is responsible for flushing all the writes in the queue, but it can't be ensured to always trigger flush because it may be cancelled when await for the serial exec lock. And this change set replaces the `try_join_all` in the rpc services to avoid such cancellation.
Test it manually.
> fix: write cancel when flush pending write queue

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/instance/flush_compaction.rs
Closes #
Since there are multiple levels now, the original logic of checking that the compact_file is empty fails. 
Fix check logic.
CI.
> chore: check compact_files is empty

- Cargo.lock
- Cargo.toml
- build.rs
- src/bin/ceresdb-server.rs
Part of #151
- `libgit2` used by `vergen` takes too much time to compile, and we can configure `gitcl` feature of `vergen` to remove such dependency.
- Upgrade `vergen` to output more information about the compiled binary.
> feat: upgrade vergen and remove dep libgit2

- proxy/src/error.rs
- proxy/src/write.rs
Closes #
* Fix the problem of inconsistent error message returned when auto_create_table fails.
* Grpc returns more detailed error info.
> fix: the problem of inconsistent error message returned when auto_create_table fails

- .github/pull_request_template.md
Rationale is important for reviewers
- Add rationale part in PR template
> chore: add rationale part in pr template

- analytic_engine/src/sst/parquet/async_reader.rs
- tools/src/bin/sst-metadata.rs
Closes #
- `sst-metadata` will print each kv size in verbose mode
- remove duplicated metric in async reader
Manually
> chore: remove duplicated metrics

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/row_iter/merge.rs
- partition_table_engine/src/partition.rs
- proxy/src/write.rs
- remote_engine_client/src/client.rs
- wal/src/tests/read_write.rs
Close #945 
Avoid using *join_all.
> refactor: replace *join_all with forloop in flush

- components/object_store/src/mem_cache.rs
Current mem cache will consume more memory than expected.
Fix the wrong capacity of a partition cache.
Add UT `test_mem_cache_capacity`
> fix: capacity should equal to total / part_num

- server/src/grpc/remote_engine_service/mod.rs
Information of partition table query routed to a specific ceresdb server is missing.
Add logs for the remote engine read.
> chore: add log for stream read of remote engine service

- analytic_engine/src/sst/parquet/meta_data.rs
- analytic_engine/src/sst/parquet/writer.rs
- common_types/src/schema.rs
- tools/src/sst_util.rs
Part of #955
- Ignore filter for null, double, float, varbinary, boolean 
- Fix parse meta in  `meta_from_sst`
UT and manually
- Before: max_seq:132734153, size:348.675M, metadata:40.142M, kv:38.175M, filter:28.525M, row_num:7038949
- After:    max_seq:132734153, size:334.045M, metadata:25.512M, kv:23.545M, filter:17.562M, row_num:7038949
> feat: ignore row group filter when certain column type

- analytic_engine/src/instance/read.rs
- analytic_engine/src/row_iter/chain.rs
- benchmarks/src/merge_sst_bench.rs
The metrics about scan is missing when chain iterator is used underlying.
Do metrics collection when using chain iterator.
Manually.
> fix: missing metrics when using chain iterator

- components/object_store/src/obkv/mod.rs
- components/table_kv/src/lib.rs
- components/table_kv/src/memory.rs
- components/table_kv/src/obkv.rs
Now the implementation of `get_range` in `ObjectStore` based on `OBKV` may cause extra IO operation, the better way is to let table_kv provide a api `get_batch` to avoid this.
* Add a api `get_batch` in table_kv
* use `get_batch` implement `get_range` in `ObjectStore` based on `OBKV` 
By unit tests
> feat: use `get_batch` to implement `get_range`

- analytic_engine/src/sst/parquet/writer.rs
- common_types/src/column.rs
- common_types/src/datum.rs
- common_types/src/record_batch.rs
- common_types/src/row/mod.rs
When doing benchmark, sst iterator and xor filter build cost too much CPU.
- Change RowViewOnBatchColumnIter's item from Datum to DatumView
I will do benchmark in my test env.
> refactor: optimize sst iterator and filter build to consume less CPU

- Cargo.lock
- analytic_engine/src/setup.rs
- analytic_engine/src/storage_options.rs
- analytic_engine/src/tests/util.rs
- common_types/Cargo.toml
- common_types/src/hash.rs
- common_util/src/partitioned_lock.rs
- components/object_store/src/disk_cache.rs
- components/object_store/src/mem_cache.rs
Close #914
Use `partition lock` in `disk cache`
add ut.
> refactor: disk cache use partition lock

- Cargo.lock
- common_types/src/hash.rs
- common_util/src/partitioned_lock.rs
- components/object_store/Cargo.toml
- components/object_store/src/disk_cache.rs
- components/object_store/src/mem_cache.rs
Add generic support to generate hasher 
Add generic support to generate hasher  for all `PartitionedLock`.
Ut.
> refactor: add generic support to generate hasher

- common_types/src/hash.rs
Part of #973
- Add UT for stable hasher. (Although DefaultHasher doesn't promise fixed code over rust release, it should be same for fixed rust version.)
> test: add test for hashers

- components/message_queue/src/kafka/config.rs
- components/message_queue/src/kafka/kafka_impl.rs
- components/message_queue/src/tests/cases.rs
- wal/src/message_queue_impl/region.rs
- wal/src/tests/util.rs
Kafka client allow setting multiple kafka boost brokers, expose this in ceresdb.
Allow setting multiple kafka boost brokers.
Test manually.
> feat: allow setting multiple kafka boost brokers

- common_util/src/partitioned_lock.rs
- components/object_store/src/disk_cache.rs
- components/object_store/src/mem_cache.rs
- Add a param(partition_num) in partition lock's init_fn.
UT
> refactor: add partition num as param in partition lock's init_fn

- Makefile
- components/message_queue/src/kafka/kafka_impl.rs
`clippy::dbg-macro` lint default to allow in clippy, but we want it to be denied.
Add `-D clippy::dbg-macro` when running `cargo clippy`.
Not need.
> chore: deny `dbg-macro` in clippy

- analytic_engine/src/instance/write.rs
- analytic_engine/src/table/data.rs
- common_types/src/row/contiguous.rs
Close #308 
This is a corner case between write and alter schema, the testcase is not easy to construct, so we plan to test this in test env first, then add tests later.
> fix: schema mismatch during write

- Dockerfile
git version is missing in docker
Install git in Dockerfile
https://github.com/CeresDB/ceresdb/actions/runs/5252618309
```
root@35379a134476:/# ceresdb-server --version
CeresDB Server 
Version: 1.2.2
Git commit: 5c63d19
Git branch: fix-version
Opt level: 3
```
> chore: install git in Dockerfile

- Cargo.lock
- components/profile/Cargo.toml
- components/profile/src/lib.rs
- server/Cargo.toml
- server/src/http.rs
> refactor: profiling

- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/serial_executor.rs
- analytic_engine/src/instance/wal_replayer.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/tests/alter_test.rs
- analytic_engine/src/tests/drop_test.rs
- analytic_engine/src/tests/read_write_test.rs
- analytic_engine/src/tests/util.rs
- table_engine/src/table.rs
- wal/src/message_queue_impl/region.rs
Part of #799 
- Define `WalReplayer` to carry out replay work.
- Support both `TableBased`(original) and `RegionBased` replay mode in `WalReplayer`.
- Expose related configs.
- Modify exist unit tests to cover the `RegionBased` wal replay.
- Refactor the integration test to cover recovery logic(TODO).
> feat: support region based wal replay

- .github/workflows/ci.yml
- integration_tests/Makefile
- integration_tests/config/shard-based-recovery.toml
- integration_tests/recovery/check.py
- integration_tests/recovery/run.sh
Part of #799 
Now we run the test about recovery manually that is so tired, this pr add this into integration tests which will be run automatically in ci.
+ Add  integration test about recovery.
+ Add above test to ci.
None.
> chore: add integration test about recovery

- proxy/src/grpc/metrics.rs
- proxy/src/grpc/sql_query.rs
- proxy/src/grpc/write.rs
- server/src/grpc/metrics.rs
- server/src/grpc/remote_engine_service/mod.rs
Add grpc query success counter metrics.
- Add counter metric in grpc proxy.
- Add counter metric in grpc remote engine service.
> refactor: add grpc handler metrics

- proxy/src/forward.rs
- proxy/src/grpc/sql_query.rs
- proxy/src/http/prom.rs
- proxy/src/http/sql.rs
- proxy/src/influxdb/mod.rs
- proxy/src/lib.rs
- proxy/src/read.rs
- proxy/src/write.rs
- server/src/grpc/storage_service/mod.rs
Close #984 
Add a parameter to the headers of grpc to mark that it has been forwarded.
Existing tests
> refactor: avoid grpc forwarding twice

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/table/version.rs
In current design, sst files may be picked multiple times.
- Mark files as in compacting when pick files candidates, and reset it to false when CompactionTask is dropped.
Manually
> fix: ensure files can only be picked once

- analytic_engine/src/sst/meta_data/cache.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/encoding.rs
- common_types/src/schema.rs
The metadata for arrow schema is encoded into the parquet file. However, this part is lost when building our custom metadata.
Keep the other metadata in the parquet metadata after extracting our custom metadata.
Add unit test `test_arrow_meta_data` for it.
> fix: arrow meta data is lost when decode custom meta data

- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/close.rs
- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/wal_replayer.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/table/data.rs
- analytic_engine/src/table/mod.rs
- table_engine/src/table.rs
Part of #990.
Some background jobs are still allowed to execute, and it will lead to data corrupted when a table is migrated between different nodes because of multiple writers for the same table.
Introduce a flag called `invalid` in the table data to denote whether the serial executor is valid, and this flag is protected with the `TableOpSerialExecutor` in table data, and the `TableOpSerialExecutor` won't be acquired if the flag is set, that is to say, any table operation including updating manifest, altering table and so on, can't be executed after the flag is set because these operations require the `TableOpSerialExecutor`. Finally, the flag will be set when the table is closed.
> fix: avoid any updates after table is closed

- Cargo.lock
- analytic_engine/src/instance/open.rs
- analytic_engine/src/manifest/details.rs
- components/message_queue/Cargo.toml
- components/message_queue/src/kafka/config.rs
- components/message_queue/src/kafka/kafka_impl.rs
Part of #799 
We use `rskafka` as our kafka client.
However I found it will retry without limit even though kafka service is unavailable...
(see [https://github.com/influxdata/rskafka/issues/65](https://github.com/influxdata/rskafka/issues/65))
Worse, I found `rskafka` is almostis no longer maintained...
For quick fix, I forked it to support limited retry.
+ Use the instead forked `rskafka`(supporting limited retry).
+ Add more logs in recovery path for better debugging.
Test manually.
> feat: use instead forked `rskafka` to support limited retry

- Cargo.lock
- common_types/Cargo.toml
- common_types/src/bitset.rs
- common_types/src/column.rs
- common_types/src/column_block.rs
- common_types/src/lib.rs
- common_types/src/record_batch.rs
- df_operator/src/functions.rs
- df_operator/src/udfs/time_bucket.rs
- interpreters/src/insert.rs
- proxy/src/grpc/prom_query.rs
- proxy/src/influxdb/types.rs
- table_engine/src/memory.rs
Introduce `Column` which is a columnar storage to optimize the writing process later.
CI.
> feat: fork `Column` and `ColumnData` from influxdb_iox

- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/wal_replayer.rs
- wal/src/message_queue_impl/log_cleaner.rs
- wal/src/message_queue_impl/region.rs
> chore: fix logs and style

- Cargo.lock
- Cargo.toml
See https://github.com/CeresDB/ceresdbproto/pull/81
After this, developers can set `export CERESDBPROTO_ENABLE_VENDORED=false` to use protoc on their host.
No need.
> chore: bump ceresdbproto

- query_frontend/src/frontend.rs
close #1022
Check statements' len before parse table name
add ut.
> fix: avoid crash due to empty sql

- tools/src/bin/sst-metadata.rs
More details about the sst are neeeded for troubleshooting problems.
- Output some statistics about the file;
- Output compression information;
Check the output of sst-meta tool.
> feat: add more details about the sst in sst-metadata tool

- analytic_engine/src/sampler.rs
Timestamp::now() produces a random timestamp which leads to occasional test fail.
Use a fixed timestamp.
> fix: `test_suggest_duration_and_ranges()` occasional fail.

- Cargo.lock
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/reader.rs
- components/parquet_ext/Cargo.toml
- components/parquet_ext/src/lib.rs
- components/parquet_ext/src/meta_data.rs
- components/parquet_ext/src/reader.rs
- tools/src/bin/sst-metadata.rs
#1000 was reverted in #1026, here to create a new one. See details in #1000
* add page index for metadata
> feat: add page indexes for metadata

- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/close.rs
- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/wal_replayer.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/table/data.rs
- analytic_engine/src/table/mod.rs
- table_engine/src/table.rs
This reverts commit 85eb0b7d7f221ccd1aa3247d9a1699edab90a21a.
The changes introduced by #998 are not reasonable. Another fix will address #990.
Revert #998
> Revert "fix: avoid any updates after table is closed (#998)"

- analytic_engine/src/setup.rs
- wal/src/rocks_impl/config.rs
- wal/src/rocks_impl/manager.rs
Now rocksdb as the wal, it is easy to become the bottleneck of write.
1. expose more rocksdb options to avoid write stall
2. introduce rocksdb's FIFO compaction style, which makes rocksdb looks like a message queue. 
(FIFO is more suitable for time-series data, maybe it will become the default option in the future?)
I will test it in my test env.
> feat: expose more rocksdb options

- Cargo.lock
- common_util/src/time.rs
- proxy/Cargo.toml
- proxy/src/lib.rs
- proxy/src/opentsdb/mod.rs
- proxy/src/opentsdb/types.rs
- server/src/http.rs
Part of #904 
1. write some data points 
```
curl --location --request POST 'http://127.0.0.1:5440/opentsdb/api/put' --data-ascii '
[
{
"metric": "sys.cpu.nice",
"timestamp": 1687935743000,
"value": 18,
"tags": {
"host": "web01",
"dc": "lga"
}
},
{
"metric": "sys.cpu.nice",
"timestamp": 1687935743000,
"value": 18,
"tags": {
"host": "web01"
}
}
]
'
```
2. select 
```
curl --location --request POST 'http://127.0.0.1:5440/sql' --data-ascii '
SELECT * from "sys.cpu.nice"
'
```
the response: 
```
{
"rows": [
{
"tsid": 1890867319031064034,
"timestamp": 1687935743000,
"dc": null,
"host": "web01",
"value": 18.0
},
{
"tsid": 7054964577922029584,
"timestamp": 1687935743000,
"dc": "lga",
"host": "web01",
"value": 18.0
}
]
}
```
> feat: support opentsdb put api

- .github/workflows/ci.yml
- integration_tests/Makefile
- integration_tests/opentsdb/run-tests.sh
- integration_tests/opentsdb/test-put.py
- server/src/http.rs
> test: add integration test for opentsdb put api

- tools/src/bin/sst-metadata.rs
When debugging SST, it's useful to check sst ordered by time/max_seq/size.
- add a option `sort`
> feat: sst-metadata support sort

- analytic_engine/src/compaction/picker.rs
Part of #987.
Current implementation will compact by file size, max_seq is not considered, this may cause data corruption
in corner case, eg:
- sst1, max_seq:10, PK1=10
- sst2, max_seq:11, PK1=9
- sst3, max_seq:12, no PK1
If compact pick sst1 and sst3, and output sst4, its max_seq will be 12, now PK1 exists in two files:
- sst2, max_seq:11, PK1=9
- sst4, max_seq:12, PK1=10
That's to say, PK1's value is 10 now, which is wrong value(9 is right).
When do compaction, first sort sst by max_seq desc, then only pick adjacent ssts, the original issue is fixed in this way.
At the same time picked ssts are ensured to meet other requirements such as `min_threshold`, `max_threshold`, `max_input_size`.
UT and manually.
> fix: compaction support pick by max_seq

- proxy/src/grpc/mod.rs
- proxy/src/grpc/sql_query.rs
- proxy/src/grpc/write.rs
- proxy/src/http/prom.rs
- proxy/src/influxdb/mod.rs
- proxy/src/lib.rs
- proxy/src/metrics.rs
- proxy/src/opentsdb/mod.rs
Add http write failed counter metrics.
- Add http counter metric in proxy.
Existing tests
> refactor: add http write metrics

- analytic_engine/src/memtable/mod.rs
- analytic_engine/src/memtable/skiplist/iter.rs
- analytic_engine/src/row_iter/tests.rs
- common_types/src/bitset.rs
- common_types/src/datum.rs
- common_types/src/lib.rs
- common_types/src/row/contiguous.rs
- common_types/src/row/mod.rs
- common_types/src/tests.rs
- common_util/src/bitset.rs
- common_util/src/lib.rs
For a table which contains many nullable columns, many nulls may cause huge memory consumption in the memtable, leading to small ssts where null values will be compressed.
- Introduce a bitset for continuous row encoding
- Use u32 to encode the offest in the encoded bytes rather than u64
Existing unit test. And test it with tsbs's data, here is result with write buffer 32MB:
|          description                  |   version  | encoded size of one row | number of rows in memtable | sst's size |
| --------------------------- | -------- | ------------------------- | ---------------------------- | --------- |
| 20 col (not null)                    | main      | 325B                                   | 70000+                                    | 1.8M        |
| 20 col (not null) …
> feat: memtable bitmap for null

- components/message_queue/src/kafka/kafka_impl.rs
- components/message_queue/src/tests/cases.rs
- wal/src/kv_encoder.rs
- wal/src/message_queue_impl/encoding.rs
- wal/src/message_queue_impl/namespace.rs
- wal/src/message_queue_impl/region.rs
- wal/src/message_queue_impl/region_context.rs
In the old kafka logs deletion and recovery logic, some conercases leading to logs can never be cleaned up.
+ Fix the logs deletion logic.
+ Fix recovery logic.
Test manually.
> fix: fix kafka wal logs deletion and recovery logic

- analytic_engine/src/instance/read.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- components/trace_metric/src/collector.rs
- components/trace_metric/src/metric.rs
- components/trace_metric_derive/src/builder.rs
- components/trace_metric_derive_tests/src/lib.rs
When some metrics contains more than one subtask, it's helpful to collect them together for output.
- Update metric macro, add metric operator.
Update `basic` UT to test this. This is what I get in my test env:
```
scan_sst_6655:                                                                                                                                                                            
project_record_batch=847.03µs                                                                                                                                                         
project_record_batch=1.182922ms                                                                                                                                                       
project_record_batch=1.208636ms …
```
> feat: add record batch mem stats

- wal/src/message_queue_impl/region.rs
Now when opening a fully flushed region, it may hang forever...
This pr fix this problem on wal level, but it is the problem in kafka client that is planned to fix in later.
See title.
Test manually.
> fix: fix fully flushed region open in kakfa wal

- analytic_engine/src/instance/open.rs
Now it will still scan logs from wal when no table datas needed to replay, it should directly return actually.
Add a fast path to return directly when no table datas needed to replay.
Test manually.
> fix: directly return when found no table datas to replay

- Cargo.lock
- Cargo.toml
- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/table_options.rs
- analytic_engine/src/tests/table.rs
- common_types/src/lib.rs
- common_util/src/time.rs
- proxy/Cargo.toml
- proxy/src/error.rs
- proxy/src/lib.rs
- proxy/src/read.rs
- server/src/http.rs
- system_catalog/src/sys_catalog_table.rs
- table_engine/src/lib.rs
Close #939
When query's time range exceed ttl, log warning message.
Manual test
> feat: warning when query's timestamp is exceeding table's ttl

- common_types/src/row/contiguous.rs
close #1055
- use varint to encode length of string/bytes in memtable
- Existing tests
> refactor: use varint to encode string/bytes length

- cluster/src/cluster_impl.rs
- cluster/src/lib.rs
- meta_client/src/types.rs
- router/src/cluster_based.rs
- server/src/http.rs
- server/src/server.rs
Close #1066 
- Add cluster in http server
- Add list shards in cluster trait
- Add query api in http server
- Existing tests
- Manually tests
> feat: support query opened shards info

- Cargo.lock
- common_types/Cargo.toml
- common_types/src/column_schema.rs
We support tag to be dictionary encoding, but in a back-incompatible way, it will throw following errors:
```
err:Arrow field meta key is not found, key:IsDictionary.
```
- When parse arrow meta, make is_dictionary optional
UT
> fix: make `is_dictionary` optional

- components/arrow_ext/Cargo.toml
- components/arrow_ext/src/ipc.rs
- components/arrow_ext/src/lib.rs
- integration_tests/cases/env/cluster/ddl/alter_table.sql
- integration_tests/cases/env/local/ddl/alter_table.result
- integration_tests/cases/env/local/ddl/alter_table.sql
When schema has more than one dict fields, datafusion may lose the `dict_id`, which will cause an error in the record batch encode, and the client decoded the record batch via ipc will throw following errors:
```
DecodeArrowPayload(InvalidArgumentError("Value at position 0 out of bounds: 0 (should be in [0, -1])"))
```
More context: https://github.com/apache/arrow-datafusion/issues/6784
- Assign unique dict id when there are more than one dict fields. 
UT and integration tests.
> fix: add missing `dict_id`

- Cargo.lock
- common_util/Cargo.toml
- common_util/src/future_cancel.rs
- common_util/src/lib.rs
In some case, the future cancel safety must be guaranteed, but there is no such a mechanism to make it now.
Introduce `CancellationSafeFuture` to wrap a future to ensure it must be executed.
This implementation refers to: https://github.com/influxdata/influxdb_iox/blob/885767aa0a6010de592bde9992945b01389eb994/cache_system/src/cancellation_safe_future.rs
> feat: support cancellation safe future

- analytic_engine/src/instance/open.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/table/data.rs
- analytic_engine/src/table_meta_set_impl.rs
Now we stats manifest updates of all tables in `Manifest` to trigger snapshot. 
However when snapshot is triggered, it will just do snapshot of latest table storing update.
It is obvious unreasonable...
Worse, this mechanism lead to bug #1075 ...
So In this pr, I place the manifest updates stats into `TableData` , and each table can only trigger snapshot of itself rather than others.
+ Place the manifest updates stats into `TableData`.
+ Use it to trigger manifest snapshot.
Test by new ut.
> feat: use manifest updates stats in `TableData` to trigger snapshot

- analytic_engine/src/instance/mod.rs
- analytic_engine/src/table/mod.rs
If the first write request is canceled, the write request in the queue will never be executed, until the queue is full, then an error will be returned.
Use `CancellationSafeFuture` to  execute the write requests, see #1071 
> fix: avoid write queue full block

- cluster/src/cluster_impl.rs
- cluster/src/shard_set.rs
In current implementation, open shard process have following issue:
1. When tables of shard is not fully opened, it will report to meta the shard is opened. It should wait all tables are opened.
2. Open shard may get executed multiple times, since meta may keep sending open shard request
1. Introduce ShardStatus, which will be set to `Opened` when all tables are opened, and only after this, shard can be sent to meta.
2. Before open shard, check status, if it's already in opening, return an Error.
WIP
> fix: ensure shard is opened once

- Cargo.lock
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/prefetchable_stream.rs
- analytic_engine/src/row_iter/chain.rs
- analytic_engine/src/row_iter/merge.rs
- analytic_engine/src/row_iter/record_batch_stream.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/writer.rs
- analytic_engine/src/sst/reader.rs
- benchmarks/Cargo.toml
- benchmarks/src/merge_memtable_bench.rs
- benchmarks/src/merge_sst_bench.rs
- benchmarks/src/sst_bench.rs
- benchmarks/src/sst_tools.rs
- benchmarks/src/util.rs
- components/test_util/Cargo.toml
- table_engine/src/provider.rs
- tools/Cargo.toml
- tools/src/bin/sst-convert.rs
Close #959
The current procedure to fetch sst data is started immediately, and it may lead to high memory consumption when massive concurrent queries reaches.
Introduce a prefetchable stream to replace the normal stream, with which a way to trigger the fetching data is provided and when to trigger it can also be determined by the caller.
The memory usage and latency of the old version and new one will be attached here.
> feat: avoid prefetching all sst streams at once

- Cargo.lock
- catalog/src/table_operator.rs
- cluster/src/cluster_impl.rs
- cluster/src/shard_set.rs
- meta_client/src/types.rs
- router/src/cluster_based.rs
- server/src/grpc/meta_event_service/mod.rs
After #1080, ceresdb will not heartbeat to meta until all table open finished, that is to say that all tables inside a shard will not be used for write/read, which is unreasonable.
- Introduce PartialOpen status sent to meta, and it will send this status when part of tables are opened, and meta will route table in this status.
- <del>Flush table when open successfully to reduce WAL size.</del>
Manually
> feat: add shard status when heartbeat to meta

- integration_tests/prom/remote-query.py
- query_frontend/src/promql/remote.rs
PromQL query should be case-sensitive for  column name
- Use `ident` when construct filter.
Update integration tests and UT
> fix: quote column name in prom query filter

- components/object_store/src/obkv/meta.rs
- components/object_store/src/obkv/mod.rs
In current version, there are two bugs in module `ObjectStore` based on OBKV.
* `Out of range` error occurs when calling  method `get_range` 
*  Save meta info error when putting an existing file.
* Fix these bugs
* Add some unit tests
* Test by unit tests
> fix:  out of range error in module ObjectStore base on OBKV

- server/src/http.rs
- wal/src/manager.rs
- wal/src/message_queue_impl/namespace.rs
- wal/src/message_queue_impl/region.rs
- wal/src/message_queue_impl/wal.rs
- wal/src/rocks_impl/manager.rs
- wal/src/table_kv_impl/namespace.rs
- wal/src/table_kv_impl/table_unit.rs
- wal/src/table_kv_impl/wal.rs
Although `get_statistic` method exist in `WalManager`, it print so less message and just impl in RocksDB wal.
In this pr, I impl this method in all wal impls, and print the detail inner infos through it.
The output example(RocksDB wal):
```
[Data wal stats]:
#RocksDB stats:
#Wal stats:
TableUnit { id: 2199023255724, next_sequence_num: 59 }
TableUnit { id: 2199023255777, next_sequence_num: 50 }
TableUnit { id: 2199023255627, next_sequence_num: 50 }
...
------------------------------------------------------
[Manifest wal stats]:
#RocksDB stats:
#Wal stats:
TableUnit { id: 2199023255739, next_sequence_num: 2 }
TableUnit { id: 2199023255669, next_sequence_num: 2 }
TableUnit { id: 2199023255740, next_sequence_num: 2 }
...
```
Impl and improve the `get_statistic` method in `WalManager`.
Test …
> feat: refactor stats method in wal

- common_types/src/row/contiguous.rs
- common_types/src/schema.rs
Close #1097 
The row encoding will be wrong when processing null columns which is caused by a different write schema from the logical table schema.
- Set the correct column index for the null bit sets in the row's encoding
Add a new designed test for different write schema.
> fix: wrong encoding when write schema is different

- Cargo.lock
- common_types/Cargo.toml
- common_types/src/datum.rs
- df_operator/Cargo.toml
- df_operator/src/aggregate.rs
- df_operator/src/udfs/thetasketch_distinct.rs
- integration_tests/cases/common/function/thetasketch_distinct.result
- server/src/http.rs
Our impl for `thetasketch_dinstinct` udf is so rough, that leading to the bad performance.
The aggregate stage cost `17s` in our production...
In this pr, I refactor the impl `thetasketch_dinstinct` for the better performance, now the aggregate stage will just cost `6s` for the same sample sql.
+ Update `hyperloglog` crate for better performance.
+ Use `DatumView` instead of `DfScalarValue` in `HllDistinct` to eliminate the unnecessary clone.
+ Fix related test.
Test by new ut and integration.
> feat: Improve performance of thetasketch dinstinct

- analytic_engine/src/compaction/mod.rs
- analytic_engine/src/compaction/scheduler.rs
When table with many small l0 sst, it will hurt query perf, so we should support compact same table concurrently.
- Reschdule another compact req before do compact.
WIP
> feat: support compact table concurrently

- analytic_engine/src/sst/parquet/async_reader.rs
See https://github.com/CeresDB/ceresdb/issues/1040
Manually
> fix: disable read parquet page index

- analytic_engine/src/sst/parquet/async_reader.rs
The code about the page index is not used for now and remove it.
Remove the unused codes about the page index.
No need.
> chore: remove unused codes about the page index

- analytic_engine/src/instance/read.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/memtable/factory.rs
- analytic_engine/src/space.rs
- analytic_engine/src/table/mod.rs
Some fields are not necessary in the `TableImpl`, so let's remove them.
Remove verbose fields in the `TableImpl`.
> chore: remove space_and_table from the table_impl

- wal/src/kv_encoder.rs
- wal/src/rocks_impl/manager.rs
- wal/src/table_kv_impl/table_unit.rs
In some cases(such as `Manifest::do_snapshot`), `actual_next_sequence` maybe less than `start_sequence`, and it will check this then return error in OBKV WAl.
In this pr, I refactor this open logic.
Refactor wal open logic to allow `actual_next_sequence` less than `start_sequence`.
Test by exist tests.
> fix: obkv wal open

- server/src/grpc/mod.rs
Currently meta service is running inside default runtime, which may cause some operation of meta service take very long time.
No need.
> fix: meta service change to meta_runtime

- analytic_engine/src/memtable/mod.rs
- analytic_engine/src/memtable/skiplist/iter.rs
- proxy/src/grpc/prom_query.rs
- proxy/src/grpc/route.rs
- proxy/src/grpc/sql_query.rs
- proxy/src/http/prom.rs
- proxy/src/metrics.rs
- proxy/src/read.rs
Currently route, prom query have no failed metrics.
Add metrics for route, prom query.
> feat: add metrics for prom route query

- query_frontend/src/promql/remote.rs
Now `promql` uses `regexp_match` macro to present the regex expr, which is not friendly for optimizing.
ut
> refactor: use `BinaryExpr` to present regex filter

- analytic_engine/src/lib.rs
- wal/src/table_kv_impl/model.rs
- wal/src/table_kv_impl/namespace.rs
When initing obkv wal, we need to check and create bucket table one by one...
However this process can be runned in parallel.
Check and create tables in parallel when opening obkv wal.
Test manually.
> feat: make obkv wal opening more parallelly

- Cargo.lock
- Cargo.toml
- components/table_kv/Cargo.toml
fix https://github.com/oceanbase/obkv-table-client-rs/issues/69
* Upgrade OBKV client to latest version.
* Upgrade `async-trait` to resolve dep conflicts.
OBKV team has tested the client.
> fix: upgrade obkv cilent to fix panic in mysql crate

- Cargo.lock
- docs/example-cluster-1.toml
- docs/minimal.toml
- integration_tests/Makefile
- integration_tests/config/ceresdb-cluster-1.toml
- integration_tests/postgresql/basic.sh
- server/Cargo.toml
- server/src/config.rs
- server/src/lib.rs
- server/src/postgresql/builder.rs
- server/src/postgresql/error.rs
- server/src/postgresql/handler.rs
- server/src/postgresql/mod.rs
- server/src/postgresql/service.rs
- server/src/server.rs
close #711 
I have to create a new PR again, because the old branch name is not valid for sdk-testing.
support PostgreSQL wire Protocol
Integration tests
> feat:  support PostgreSQL wire protocol

- Cargo.lock
- remote_engine_client/Cargo.toml
- remote_engine_client/src/lib.rs
- server/src/grpc/mod.rs
- server/src/grpc/remote_engine_service/mod.rs
- server/src/server.rs
#1127 add support for remote engine, but in client, it should be for server.
- Remove remote client record, add add for remote server.
Manually
> fix: record remote engine requests

- analytic_engine/src/setup.rs
- components/object_store/src/disk_cache.rs
- The corrupted file in the disk cache will lead to the panic of the server
- The whole cache page file is fetched when only a range of the file is accessed, leading to high memory consumption
- Store the file size in the memory for file integrity check
- Omit the corrupted file in the disk cache rather than panic
- Do IO operation outside the meta data cache lock
- Read only the involved range of a cached paged file instead of the whole file
Existing tests and a newly designed test.
> fix: avoid panic when the file is corrupted in disk cache

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- Makefile
- integration_tests/postgresql/basic.sh
- scripts/clean-large-folder.py
1.2.5 is released, start a new dev circle.
- Bump version to 1.2.6-alpha
- Clean disk when target dir is over 30G.
> chore: bump to 1.2.6-alpha

- scripts/license-header.txt
The missing license template leads to git pre-commit failure.
Add license template for pre-commit.
> chore: add apache license template

- integration_tests/cases/common/dml/issue-341.result
- integration_tests/cases/common/dml/issue-341.sql
- table_engine/src/provider.rs
close #341 
I  just change `supports_filter_pushdown` in `TableProvider` to return `TableProviderFilterPushDown::Exact` to fix this
pass
> feat: remove filter plan node in pipeline

- Cargo.lock
- Cargo.toml
- common_types/src/column_schema.rs
- common_types/src/datum.rs
- remote_engine_client/src/client.rs
- server/src/grpc/metrics.rs
- server/src/grpc/remote_engine_service/mod.rs
- table_engine/src/remote/model.rs
According to the cpu profile results, it costs too much cpu resource when encode/decode the payloads for the remote engine write service.
- Impose a new protocol for communication between remote engine client and service
- Avoid attaching the schema information in the payload
- Do the encoding work outside the io thread pool
Proved 60% traffic drop and 25% cpu performance improvement in one of our prod environment.
> refactor: use new protocol for remote engine service write

- common_types/src/datum.rs
- components/hash_ext/src/lib.rs
- interpreters/src/insert.rs
- query_frontend/src/promql/udf.rs
- table_engine/Cargo.toml
- table_engine/src/partition/rule/df_adapter/mod.rs
- table_engine/src/partition/rule/key.rs
The previous implementation of computing partition key is coarse, leading to poor performance.
Refactor the implementation of computing partition key, and the most of memory allocation is avoided.
Existing unit tests.
> refactor: improve the partition compute

- proxy/src/context.rs
- proxy/src/grpc/prom_query.rs
- proxy/src/grpc/sql_query.rs
- proxy/src/http/prom.rs
- proxy/src/http/sql.rs
- proxy/src/influxdb/mod.rs
- proxy/src/lib.rs
- proxy/src/opentsdb/mod.rs
- proxy/src/read.rs
- proxy/src/write.rs
- server/src/grpc/storage_service/mod.rs
- server/src/http.rs
- server/src/mysql/worker.rs
- server/src/postgresql/handler.rs
Currently when query failed, the error log doesn't contain request id, this makes it's very hard to tell how long the error query takes.
- Add `request_id` in context, and print this ctx when query failed.
- Remove `enable_partition_table_access`, `runtime` from context to avoid unnecessary clone.
- Remove unnecessary param's move, change to reference.
> refactor: add request id in context

- analytic_engine/src/memtable/skiplist/iter.rs
- components/time_ext/src/lib.rs
Use `duration_since` is vague, large than is more clearly.
Manually.
> fix: deadline check

- integration_tests/cases/common/function/aggregate.result
- integration_tests/cases/common/function/aggregate.sql
One of our user report follow errors:
```
{"code":500,"message":"Failed to handle request, err:Rpc error, code:500, message:Failed to execute plan, sql:select  distinct(`app_id`)   from visit where `period` <= 1692147800000 and `period` >= 1692147600000 , err:Internal error, msg:Failed to execute interpreter, err:Failed to execute select, err:Failed to execute logical plan, err:Failed to do physical optimization, err:DataFusion Failed to optimize physical plan, err:Internal error: Unsupported logical plan: Distinct should be replaced to Aggregate. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker."}
```
This bug is already fix in main, so add this to ensure it won't break any more.
> test: add integration test for distinct

- integration_tests/cases/common/function/aggregate.result
- integration_tests/cases/common/function/aggregate.sql
Currently, on the main branch, the integration test has failed resulting from a sql without the order by clause.
Add order by clause for the wrong case.
By the CI.
> fix: add order by for integration test case

- interpreters/src/tests.rs
- query_engine/src/datafusion_impl/codec.rs
- query_engine/src/datafusion_impl/executor.rs
- query_engine/src/datafusion_impl/mod.rs
- query_engine/src/datafusion_impl/physical_plan.rs
- query_engine/src/datafusion_impl/physical_planner.rs
- query_engine/src/executor.rs
- query_engine/src/physical_planner.rs
Part of #1112 
I found we holding the execution context in `DataFusionPhysicalPlanImpl`, rather than passing it as a  param when executing like what datafusion suggests to do.
It lead to problems when I plan to deserialize bytes to `DataFusionPhysicalPlanImpl`...
+ Remove `SessionContext` from `DataFusionPhysicalPlanImpl`.
+ Pass it as a param when executing the plan.
+ Wrap all common part to `DfContextBuilder` and use it to build `SessionContext` in `DatafusionExecutorImpl` and `DatafusionPhysicalPlannerImpl`.
Test by exist tests.
> refactor: pass the `TaskContext` when execute physical plan rather than holding it

- Cargo.lock
- Cargo.toml
- components/bytes_ext/src/lib.rs
- components/codec/Cargo.toml
- components/codec/src/columnar/bytes.rs
- components/codec/src/columnar/float.rs
- components/codec/src/columnar/int.rs
- components/codec/src/columnar/mod.rs
- components/codec/src/varint.rs
Current encoding of columnar bytes is naive, without any consideration about compression.
Introduce the compression encoding based on a designed threshold for columnar bytes.
> feat: implement compression encoding for columar bytes values

- components/codec/src/columnar/int.rs
- components/codec/src/columnar/mod.rs
Not all columnar encoding for integer types are not supported.
Support the columnar encoding for all the integer types.
> feat: implement columnar encoding for integer

- common_types/src/datum.rs
- common_types/src/row/bitset.rs
- components/codec/src/columnar/bool.rs
- components/codec/src/columnar/bytes.rs
- components/codec/src/columnar/mod.rs
The columnar compression encoding for boolean is not supported.
Supported compression for the encoding for boolean.
> feat: implement boolean columnar encoding

- .github/workflows/ci.yml
- analytic_engine/src/instance/write.rs
- analytic_engine/src/table/metrics.rs
Add write fields metrics.
No need
> chore: add fields metrics

- analytic_engine/src/table/data.rs
Recoverer misuse `ColumnarMemTable`.
Use `SkiplistMemTable` as default memtable.
CI.
> fix: recover memtable misuse ColumnarMemTable

- table_engine/src/partition/rule/key.rs
The remaining datums won't be consumed for computing partition if there is one empty datum in them.
Avoid break when encounter an empty string.
Add a unit test for this case.
> fix: not consume all the datums if some of them is empty

- analytic_engine/src/sst/meta_data/cache.rs
- analytic_engine/src/sst/metrics.rs
- proxy/src/hotspot.rs
- proxy/src/http/sql.rs
- proxy/src/read.rs
- server/src/grpc/remote_engine_service/mod.rs
There is no metrics to report the hit rate for the meta data cache.
- Add counter for the meta data cache hit/miss.
- Formalize the logs for the sql query and remote engine service query.
> chore: add metrics for meta data cache hit rate

- .github/workflows/ci.yml
- .gitignore
- integration_tests/Makefile
- integration_tests/build_meta.sh
- integration_tests/dist_query/diff.py
- integration_tests/dist_query/run.sh
- integration_tests/src/main.rs
Close #1191 
The integration test for partitioned table is too simple, now. We just insert data of poor amount and query them...
In this, tsbs is introudced for big data amount test for partitioned table.
+ Introduce tsbs and a pre-generated dataset for testing.
+ We don't want to remove and rebuild components(e.g. ceresmeta) on sometimes, and I added an option to control it in this pr, usage:
```
UPDATE_REPOS_TO_LATEST=false make run-dist-query
```
It is the test itself.
> feat: improved partitioned table tests powered by tsbs

- Cargo.lock
- Cargo.toml
- components/notifier/Cargo.toml
- components/notifier/src/lib.rs
- components/notifier/src/notifier.rs
- components/object_store/Cargo.toml
- components/object_store/src/disk_cache.rs
- components/object_store/src/metrics.rs
- server/Cargo.toml
- server/src/grpc/mod.rs
- server/src/grpc/remote_engine_service/mod.rs
The current disk cache may encounter the following scenario: Multiple threads taking the same block from object_store at the same time, To avoid this problem, we maintain a pull queue for each block, so that only one thread will pull the same block at the same time.
Add new UT `test_disk_cache_multi_thread_fetch_same_block`
> feat: limit multiple threads fetch the same block simultaneous

- server/src/grpc/mod.rs
- server/src/grpc/remote_engine_service/mod.rs
The deadlock will happen when dedup stream read requests because the serial execution of sending and receiving data on a bounded channel.
Send the data in background.
Test it manually.
> fix: deadlock when dedup stream read

- Cargo.lock
- integration_tests/Cargo.toml
- integration_tests/src/database.rs
- integration_tests/src/main.rs
Currently, we just left 20s for ceresmeta to do the initialization work in integration test.
However, it will be not enough something... And the test failure will make us so panic...
In this pr, I add a meta stable check to reduce the integration test failure.
Add a meta stable check by keep creating a radom named table utill succeeding(surely, retry max exists).
Test manually.
> chore: add meta stable check into integration test

- server/src/grpc/remote_engine_service/mod.rs
Now, we can't collect the time cost  of stream read
- Use drop trait to collect time cost  of stream read
Existing tests
> refactor: stream read metric

- components/object_store/src/disk_cache.rs
Close #1194 
Throw `OutOfRange` error when the query range is out of the file size.
Add a new dedicated unit test for this case.
> fix: panic when read data out of range by disk cache

- Cargo.lock
- components/arena/Cargo.toml
- components/arena/src/mono_inc.rs
There is no need to acquire the write lock when fetch arena's stats.
Use `RwLock` instead of `Mutex` to protect the core of the `MonoIncArena` to avoid lock contention.
> fix: lock contention on acquiring the arena stats

- proxy/src/lib.rs
It is too struggle to debug partitioned table because `enable_others` in `sub_table_access_perm` default to false...
When we try to query the specific sub table, we will always be prohibited... It will make us extremely unhappy...
Modify `enable_others` default true.
Test manually.
> chore: modify `enable_others` default true for happy debugging

- .gitignore
- cluster/src/cluster_impl.rs
- cluster/src/shard_set.rs
- integration_tests/cases/env/cluster/ddl/partition_table.result
- integration_tests/cases/env/cluster/ddl/partition_table.sql
- meta_client/src/meta_impl.rs
- meta_client/src/types.rs
In one of our deployments, I have one shard change its status from Ready to Init, there is no open/close shards requests between this change, so I add some info log to help investigate this issue.
- Skip update shard status when create/remove table
TBD
> fix: skip update shard status when create/remove table

- Cargo.lock
- Cargo.toml
- analytic_engine/Cargo.toml
- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/close.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/table/data.rs
Close #1205
- Add `TableStatus::Closed` to donate table is closed, and cancel background jobs, such as compaction.
> fix: add table status to cancel background jobs

- analytic_engine/src/memtable/skiplist/mod.rs
- components/arena/src/arena_trait.rs
- components/arena/src/mono_inc.rs
- components/skiplist/src/list.rs
In one of our cluster, we find the cost of calculate memory usage cost too much CPU, and it's  rwlock contention to be blamed.
- Use atomic usize to record written row size.
> refactor: use encoded_size as memory usage

- integration_tests/cases/env/cluster/ddl/partition_table.result
- interpreters/src/show_create.rs
The text is wrong of `show create table` for partition table.
Add the missing `PARTITION BY RANDOM` to the output of `show create table`.
> fix: wrong text of show create table for partition table

- analytic_engine/src/table/version.rs
- components/arena/src/arena_trait.rs
- components/skiplist/src/list.rs
- partition_table_engine/src/partition.rs
- table_engine/src/partition/mod.rs
- table_engine/src/partition/rule/df_adapter/mod.rs
- table_engine/src/partition/rule/factory.rs
- table_engine/src/partition/rule/key.rs
- table_engine/src/partition/rule/mod.rs
- table_engine/src/partition/rule/random.rs
Some memory allocation during partitioning write request can be avoided.
Introduce an enum called `PartitionedRows` as the return type of `PartitionRule.locate_partitions_for_write` to avoid unnecessary memory allocation.
Existing test.
> refactor: avoid memory allocation during partition write requests

- proxy/src/lib.rs
- table_engine/src/table.rs
When sub_table[0] is unhealthy, we can not drop the partition table.
Only log open partition table error, not return to outside.
> fix: ignore error when open partition table failed

- Cargo.lock
- wal/Cargo.toml
This closes #1222.
Fix compilation on macOS M1.
Upgrade TiKV's RocksDB crate to a new commit.
Existing CI workflows.
> build(deps): upgrade rust-rocksdb

- proxy/src/lib.rs
- table_engine/src/partition/mod.rs
Followup PR of #1220
Manually.
> fix: loop all sub tables to get table info

- analytic_engine/src/compaction/scheduler.rs
Current schedule stragety is too simple, when there are many pending task, we should stop reschedule.
No need.
> refactor: stop reschedule when pending task larger than max ongoing

- components/object_store/src/disk_cache.rs
- components/object_store/src/lib.rs
- components/object_store/src/test_util.rs
Close #1215
- Add MemoryStore to help test
- When persist file, first write to tmp file, then rename to dest file.
CI itself
> fix: disk cache deduped get_ranges

- Cargo.lock
- df_engine_extensions/src/dist_sql_query/mod.rs
- df_engine_extensions/src/dist_sql_query/physical_plan.rs
- df_engine_extensions/src/dist_sql_query/resolver.rs
- df_engine_extensions/src/dist_sql_query/test_util.rs
- interpreters/src/tests.rs
- query_engine/Cargo.toml
- query_engine/src/datafusion_impl/executor.rs
- query_engine/src/datafusion_impl/mod.rs
- query_engine/src/datafusion_impl/physical_plan.rs
- query_engine/src/datafusion_impl/physical_planner.rs
- query_engine/src/datafusion_impl/task_context.rs
- query_engine/src/error.rs
- query_engine/src/lib.rs
- query_engine/src/physical_planner.rs
- query_frontend/src/provider.rs
- remote_engine_client/src/client.rs
- remote_engine_client/src/lib.rs
- server/src/grpc/remote_engine_service/mod.rs
- server/src/server.rs
- src/ceresdb/src/config.rs
- src/ceresdb/src/setup.rs
- table_engine/src/memory.rs
- table_engine/src/provider.rs
- table_engine/src/remote/mod.rs
- table_engine/src/remote/model.rs
- table_engine/src/table.rs
Closes #1112 
The final part of #1112, we may do distributed query in the new way after this pr.
+ Impl rpc service to support physical plan's remote execution.
+ Refactor query engine to support the new query process.
Test by exist tests.
> feat: teach ceresdb to run the whole dist query process

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/read.rs
- analytic_engine/src/memtable/columnar/mod.rs
- analytic_engine/src/memtable/mod.rs
- analytic_engine/src/memtable/skiplist/factory.rs
- analytic_engine/src/memtable/skiplist/mod.rs
- analytic_engine/src/table/data.rs
- analytic_engine/src/table/version.rs
- benchmarks/src/merge_memtable_bench.rs
- integration_tests/cases/env/local/ddl/query-plan.result
- integration_tests/cases/env/local/ddl/query-plan.sql
Followup PR of #1225, this PR add the same logic for memtable.
Integration tests.
> feat: use real time range to filter memtable

- components/table_kv/src/obkv.rs
In obkv WAL implementation, when a table is deleted by one server, other servers will still delete same table,
In theory we should avoid this, and only allow a server to delete tables belonging to this server, but this will
major changes to OBKV WAL implementation, so here I add a check before do delete.
> fix: when drop table first check its existing

- query_engine/src/datafusion_impl/task_context.rs
- server/src/grpc/mod.rs
- server/src/grpc/remote_engine_service/mod.rs
Currently, the `execute_physical_plan` of the remote engine service is not supported yet.
Support the dedup the execution of `execute_physical_plan`.
Manual test.
> feat: support dedup execute physical plan

- catalog/src/schema.rs
- catalog_impls/src/volatile.rs
Currently, the existing table will be returned if create table with an expected table name but a different table id.
Throws an error if the provided table id is different.
This is fairly simple which doesn't need a test for it.
> fix: throw error when create a table with a different table id

- Cargo.lock
- components/table_kv/Cargo.toml
Upgrade obkv table client.
Include https://github.com/oceanbase/obkv-table-client-rs/pull/81
CI
> chore: upgrade obkv table client

- Cargo.lock
- Cargo.toml
- analytic_engine/src/compaction/picker.rs
- analytic_engine/src/sst/meta_data/cache.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/meta_data.rs
- analytic_engine/src/sst/parquet/row_group_pruner.rs
- analytic_engine/src/sst/parquet/writer.rs
- integration_tests/cases/env/local/ddl/query-plan.result
- integration_tests/cases/env/local/ddl/query-plan.sql
- table_engine/src/predicate.rs
- table_engine/src/remote/model.rs
Current filter is based on bloom-filter like structure, it can give accurate answer if an item doesn't exist in one collection, so by convert `col != value` to `col == value2`, we can fully utilize this feature.
- Save column value to SST metadata when distinct value is less than 20.
- Rewrite not-like expr to its opposite.
New UT.
> feat: rewrite `not in` expr to `in`

- cluster/src/cluster_impl.rs
- cluster/src/config.rs
- cluster/src/shard_lock_manager.rs
- components/object_store/src/disk_cache.rs
Currently, a restarted ceresdb-server must wait for the previous lock lease to expire before acquiring the new shard locks, leading to long failover time.
Support fast reacquire the shard lock by reusing the previous lock lease.
Manually test this feature.
> feat: support re-acquire shard lock in a fast way

- Cargo.lock
- Cargo.toml
- analytic_engine/src/instance/alter.rs
- catalog/src/schema.rs
- integration_tests/cases/env/cluster/ddl/partition_table.result
- integration_tests/cases/env/cluster/ddl/partition_table.sql
- partition_table_engine/src/partition.rs
- proxy/src/write.rs
- remote_engine_client/src/client.rs
- remote_engine_client/src/config.rs
- remote_engine_client/src/lib.rs
- server/src/grpc/metrics.rs
- server/src/grpc/remote_engine_service/mod.rs
- table_engine/src/memory.rs
- table_engine/src/remote/mod.rs
- table_engine/src/remote/model.rs
- table_engine/src/table.rs
Support for alter schema on partition table.
* Support for alter schema on partition table.
* Support for alter options on partition table.
* **Notice:** Currently, there is no concurrency control in place. If alter schema operations are performed simultaneously on the same partition table, it may result in schema inconsistency issue. #1247 
* **Notice:** Due to the ability to open partition table on multiple ceresdb nodes, there may be inconsistencies in the schema information maintained in memory. Currently, the approach of cleaning up through errors occurring during writing is relatively rough. #1248 
> feat: support alter partition table

- Cargo.lock
- Cargo.toml
- common_types/src/column_schema.rs
- integration_tests/cases/env/cluster/ddl/partition_table.result
- integration_tests/cases/env/cluster/ddl/partition_table.sql
- table_engine/src/remote/model.rs
The schema must be ensured to be correct during the remote write rpc call. Howerver, such check is missing now.
Introduce schema version check during remote write rpc call.
Add a new integration test for it.
> feat: support schema validate in remote write

- .github/workflows/ci.yml
- .github/workflows/docker-build-image.yml
- .github/workflows/tsbs.yml
Due to the huge cache of rust before, unit tests often failed due to insufficient capacity. [CI without cache](https://github.com/CeresDB/ceresdb/actions/runs/6492219953/job/17630769103?pr=1259) takes an acceptable time and does not cause failure problems.
https://github.com/CeresDB/ceresdb/pull/1261 show CI always fail in Rust Cache.
The github action's time seems have huge volatile, https://github.com/CeresDB/ceresdb/actions/runs/6517181839/job/17701414760?pr=1259 takes 24 min without cache, some pr have cache even is slower than this action
Delete out the configuration related to github cache
CI
> chore: delete the configuration related to github cache

- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/memtable/skiplist/mod.rs
- components/skiplist/src/list.rs
- wal/src/table_kv_impl/table_unit.rs
When drop a table, flush is unnecessary, and this cause the drop take a long time.
Mark WAL as deleted directly when drop table.
Manually
> feat: avoid flush when drop table

- query_frontend/src/parser.rs
This PR aims to resolve issue #1144 by simplifying the process of table creation with timestamp constraints. Specifically, the system will automatically infer and set the timestamp constraint under the following conditions:
1. No timestamp constraint has been previously set.
2. There exists exactly one column with a timestamp data type(`DataType::Timestamp`).
By introducing this automatic inference, we reduce the complexity for users who otherwise would have to manually set this constraint.
- **Automatic Inference of Timestamp Constraint**: The system now detects if there is only a single timestamp column during table creation and automatically sets it as the timestamp constraint.
- Added a function `build_and_check_timestamp_key_constraint` for checking and inference.
- Modified the …
> feat: infer timestamp constraint for single-timestamp column

- proxy/src/limiter.rs
When a table is blocked by the block rule, ceresdb-server logs useless stack information.
Remove backtrace of blocked table.
No need.
> chore: remove backtrace of blocked table

- .github/workflows/ci.yml
- integration_tests/Makefile
We may use `go-version-file` instead to avoid manually maintain the `go-version` field.
But the approach we currently clone ceresmeta and build is a bit complex to change; so I'd prefer to postpone it to a follow-up nice-to-have task.
> ci: setup golang in CI

- Makefile
- analytic_engine/Cargo.toml
- src/ceresdb/Cargo.toml
Currently although wal is gated by different features,  we can't disable a wal implementation.
- Remove default default in analytic_engine, and let upper layer to choose which wal to use.
Manually.
> chore: remove default features in analytic_engine

- analytic_engine/src/sampler.rs
- analytic_engine/src/sst/parquet/writer.rs
There are not many rows in min level, so we shouldn't record values for them, as they cost too much CPU.
- Skip record column values for level0
Existing UT.
> feat: skip record column values for level0 sst

- components/logger/src/lib.rs
Currently we set tag to empty string to tell it from slow log, this works for crates within ceresdb,
but for crates outside ceresdb, it will discard log.
> fix: log third party crates

- Cargo.lock
- analytic_engine/Cargo.toml
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/wal_replayer.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/manifest/meta_edit.rs
- analytic_engine/src/payload.rs
- benchmarks/src/wal_write_bench.rs
- common_types/src/datum.rs
- common_types/src/row/mod.rs
- components/codec/src/columnar/mod.rs
- components/codec/src/columnar/number.rs
- components/codec/src/columnar/timestamp.rs
- src/wal/src/kv_encoder.rs
- src/wal/src/lib.rs
- src/wal/src/log_batch.rs
- src/wal/src/manager.rs
- src/wal/src/message_queue_impl/region.rs
- src/wal/src/message_queue_impl/test_util.rs
- src/wal/src/table_kv_impl/namespace.rs
- src/wal/tests/read_write.rs
After the columnar encoding is supported for wal format, we should adapt such encoding in the wal write procedure.
Adapt the columnar encoding in the wal write procedure. And now, both rowwise and columnar encoding in the wal write procedure are supported, which to use depends on the configuration.
Existing tests. The compatibility tests have been designed as:
- Write rowwise-encoded wal logs and restart the server to replay it
- Write columnar-encoded wal logs and restart the server to replay it
> feat: support write wal logs in columnar format

- analytic_engine/src/instance/write.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/sst/meta_data/cache.rs
- analytic_engine/src/table/mod.rs
- analytic_engine/src/tests/alter_test.rs
- analytic_engine/src/tests/drop_test.rs
- analytic_engine/src/tests/table.rs
- common_types/src/schema.rs
- common_types/src/tests.rs
- interpreters/src/alter_table.rs
- proxy/src/grpc/prom_query.rs
- proxy/src/http/prom.rs
- proxy/src/influxdb/types.rs
- proxy/src/write.rs
- query_frontend/src/planner.rs
- system_catalog/src/sys_catalog_table.rs
- system_catalog/src/tables.rs
- table_engine/src/partition/rule/df_adapter/mod.rs
Current schema builder set `primary_key_index` inside `add_key_column`, which means key_indexes could only be in ascending order.
- Remove nullable limit for pk
- Refactor `primary_key_index`, user need to set it explicitly
> fix: ensure primary key order

- analytic_engine/src/instance/write.rs
- analytic_engine/src/payload.rs
- analytic_engine/src/table/mod.rs
- analytic_engine/src/tests/alter_test.rs
- analytic_engine/src/tests/table.rs
- common_types/src/row/mod.rs
- partition_table_engine/src/partition.rs
- proxy/src/write.rs
- query_engine/src/datafusion_impl/physical_plan.rs
- query_frontend/src/planner.rs
- system_catalog/src/sys_catalog_table.rs
- table_engine/src/partition/rule/df_adapter/mod.rs
- table_engine/src/remote/model.rs
The min/max timestamp in `RowGroup` is not used any more.
- Remove the min/max timestamp from the `RowGroup`
- Remove the `RowGroupBuilder` because it's too simple without min/max timestamp updating
All the tests in the CI should pass.
> refactor: remove unused min/max timestamp in the RowGroup

- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/reorder_memtable.rs
- analytic_engine/src/sampler.rs
- integration_tests/cases/env/local/ddl/sampling-primary-key.result
- integration_tests/cases/env/local/ddl/sampling-primary-key.sql
Current we suggest new primary keys in preflush, and do a reorder in flush task.
There is no easy way for flush task to know if reorder if required.
- Introduce a flag to represent whether reorder is required
- Change `col` to `ident` when build logical plan, `ident` will not normalize column name.
Integration test.
> fix: use flag in preflush to indicate whether reorder is required

- Cargo.lock
- Cargo.toml
- catalog_impls/src/volatile.rs
- cluster/src/shard_operator.rs
- cluster/src/shard_set.rs
- integration_tests/build_meta.sh
- meta_client/src/types.rs
- server/src/grpc/meta_event_service/mod.rs
For details, see: https://github.com/CeresDB/ceresmeta/issues/263
* Modify the return value of `CreateTableOnShard` & `DropTableOnShard` to return the latest shard version.
Pass all unit tests and integration test.
> refactor!: refactor shard version logic

- Cargo.lock
- analytic_engine/src/table/metrics.rs
- analytic_engine/src/table/mod.rs
- components/future_ext/Cargo.toml
- components/future_ext/src/cancel.rs
Write path metrics about pending queue is not enough, improve it in this pr.
+ Add time cost for pending queue wirter/waiter.
+ Add counter for related future cacellations.
Test manually.
> chore: add metrics to inspect write path

- .github/workflows/ci.yml
- integration_tests/Makefile
- integration_tests/config/ceresdb-cluster-1.toml
- integration_tests/sdk/go/alteraddcolumn.go
- integration_tests/sdk/go/autocreatetable.go
- integration_tests/sdk/go/go.mod
- integration_tests/sdk/go/go.sum
- integration_tests/sdk/go/issue-779.go
- integration_tests/sdk/go/main.go
- integration_tests/sdk/go/util.go
- proxy/src/write.rs
Fix adding column in `partition table` bug. 
1. Checking the schema inconsistency error in the write process, caused by adding columns. 
- Note: This only works for grpc write
3. Add a Go SDK test to check adding a column in a "partition table".
4. Start ceresdb cluster to run go-sdk tests.
GO SDK test.
> fix: alter partition table tag column

- integration_tests/build_meta.sh
Support specifying the Ceresmeta binary path in integration test.
Check CERESMETA_BIN_PATH in integration test.
CI.
> chore: refactor build_meta.sh in integration-test

- Cargo.lock
- analytic_engine/src/lib.rs
- components/runtime/src/lib.rs
- src/ceresdb/Cargo.toml
- src/ceresdb/src/config.rs
- src/ceresdb/src/setup.rs
Complex sqls, e.g. sql with massive condition in the where clause, may lead to stack overflow during query procedure. And currently, there is no a good to handle it in the query engine powered by datafusion so a simple way is just to enlarge the stack for the read threads.
- Support the stack size of read threads confiugrable
- Make the columnar format as the default wal payload
All the tests in the ci should pass.
> feat: support stack size of read threads configurable

- README-CN.md
- README.md
- integration_tests/build_meta.sh
Rename ceresdb to horaedb in the Readme.
Rename ceresdb to horaedb in the Readme.
CI.
> chore: rename ceresdb to horaedb

- analytic_engine/src/instance/alter.rs
- analytic_engine/src/instance/close.rs
- analytic_engine/src/instance/create.rs
- analytic_engine/src/instance/drop.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/manifest/details.rs
- analytic_engine/src/manifest/meta_edit.rs
- analytic_engine/src/manifest/mod.rs
- analytic_engine/src/table/data.rs
- analytic_engine/src/table_meta_set_impl.rs
Closes https://github.com/CeresDB/ceresdb/issues/1157
To be able to get the catalog from the table
I added the `schema id`, `schema name`, `catalog name` to `MetaEditRequest` for passing them to `TableData`, but because `MetaEdit` involves passing the protoc protocol, I don't save them here.
pass
> edit: add schema id, schema name, catalog name in TableData

- analytic_engine/src/instance/write.rs
- src/wal/src/dummy.rs
Currently DoNothing wal will incur too many logs 
Manually
> chore: ignore seq check for DoNothing wal

- Cargo.lock
- Cargo.toml
- components/logger/src/lib.rs
- df_engine_extensions/src/dist_sql_query/physical_plan.rs
- query_engine/src/datafusion_impl/task_context.rs
- server/src/grpc/remote_engine_service/mod.rs
- table_engine/src/remote/model.rs
Currently slow log won't record query from remote engine, this makes it's hard to explain which query has the most vital effect on current server.
- Add displayable plan in remote query request, and add to slow log
Manually
> feat: slow log include remote query

- scripts/license-header.txt
Related  https://github.com/CeresDB/horaedb/issues/1319
update `license-header.txt`'s org
UT.
> chore(license): rename `license-header.txt`'s CeresDB to HoraeDB

- integration_tests/cases/common/dml/issue-1087.result
- integration_tests/src/main.rs
- query_engine/src/datafusion_impl/logical_optimizer/type_conversion.rs
- query_engine/src/datafusion_impl/mod.rs
- query_engine/src/datafusion_impl/task_context.rs
- query_frontend/src/influxql/planner.rs
- table_engine/src/provider.rs
related https://github.com/CeresDB/horaedb/issues/1319
replace ceresdb with horaedb in code
CI
> chore: replace ceresdb with horaedb

- analytic_engine/src/sst/parquet/async_reader.rs
- integration_tests/build_meta.sh
When channel capacity < read_parallelism,  we will pass 0 to channel, which will cause panic
```
2023-12-05 20:31:32.974 ERRO [components/panic_ext/src/lib.rs:54] thread 'ceres-read' panicked 'mpsc bounded channel requires buffer > 0' at "analytic_engine/src/sst/parquet/async_reader.rs:736"
```
- Ensure channel size non zero
No need.
> fix: ensure channel size non zero

- analytic_engine/src/instance/close.rs
The flush failure before table close may lead to shard close failure. However, such failure is tolerable because the unflushed can still be recovered during the following table open.
Ignore the flush failure before closing table.
Pass all the tests in the ci.
> chore: ignore flush failure when flush

- analytic_engine/src/sst/metrics.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- components/parquet_ext/src/reader.rs
Metrics about fetched sst bytes with `get_ranges` is not collected.
Collect the missing metrics.
Query and check the metrics after executing a query.
> fix: collect metrics for `get_ranges`

- analytic_engine/src/sst/parquet/async_reader.rs
The stats about the number of bytes fetched from object store should not include the low-frequency reading, e.g. compaction because such stats are used to show the query load distribution across the tables.
Ignore collecting the fetched bytes stats in the low-frequency reading.
The ci's tests should pass.
> fix: ignore collecting fetched bytes stats when sst file is read only once

- proxy/src/grpc/sql_query.rs
- proxy/src/http/sql.rs
- proxy/src/lib.rs
- proxy/src/read.rs
HTTP API is mainly used for debugging, and should not be blocked.
Pass CI
> chore: disable block for http api

- Cargo.lock
- analytic_engine/Cargo.toml
- analytic_engine/src/instance/engine.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/serial_executor.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/meta_data/cache.rs
- analytic_engine/src/sst/meta_data/metadata_reader.rs
- analytic_engine/src/sst/parquet/async_reader.rs
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/sst/parquet/meta_data.rs
- analytic_engine/src/sst/parquet/row_group_pruner.rs
- analytic_engine/src/sst/parquet/writer.rs
- components/codec/src/columnar/timestamp.rs
- components/id_allocator/src/lib.rs
- server/src/grpc/remote_engine_service/mod.rs
- src/wal/src/rocksdb_impl/manager.rs
- table_engine/src/partition/rule/random.rs
Close #1105
- Reduce the parameters in the sst write path
- Avoid building dictionary for massive unique column values
- New unit test for the changeset
- Observe the metrics for disable/enable dictionary encoding
> feat: avoid building dictionary for massive unique column values

- analytic_engine/src/sst/parquet/async_reader.rs
The codes about deciding whether to do metrics collection according to the read frequency are duplicate.
Remove the duplicate codes.
CI.
> refactor: avoid duplicate codes

- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/sst/factory.rs
- analytic_engine/src/sst/meta_data/mod.rs
- analytic_engine/src/sst/parquet/encoding.rs
- analytic_engine/src/sst/parquet/writer.rs
- benchmarks/src/sst_tools.rs
- tools/src/bin/sst-convert.rs
The column value set has been summarized into the meta data if the column is low distinct. With such information, the sampling for the columns can be skipped.
Skip sampling over the low-cardinality columns.
Updated the unit tests.
> feat: utilize the column cardinality for deciding whether to do dict

- .asf.yaml
Reduce dev noise.
cc @tanruixiang
> docs: sync GH activities to commits only

- analytic_engine/src/compaction/scheduler.rs
- analytic_engine/src/instance/flush_compaction.rs
- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/serial_executor.rs
- analytic_engine/src/instance/wal_replayer.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/table/data.rs
#1003 tries to avoid frequent flush requests which may generate massive small ssts, but the write stall is also removed in the normal write path.
Introduce the `min_flush_interval` to avoid frequent flush requests and recover the write stall mechanism.
Add unit tests for the frequent flush check.
> fix: no write stall

- .github/workflows/publish-nightly-image.yml
The following error occurred when publishing the nightly image: 
```
buildx failed with: ERROR: failed to solve: failed to push ghcr.io/horaedb/horaedb-server:nightly-20231222-b77b6969: unexpected status from POST request to https://ghcr.io/ v2/horaedb/horaedb-server/blobs/uploads/: 403 Forbidden
```
Rename image name from `horaedb/horaedb-server` to `apache/horaedb-server`.
No need.
> fix: publich nightly image

- analytic_engine/src/instance/open.rs
- analytic_engine/src/manifest/details.rs
- query_engine/src/datafusion_impl/executor.rs
- query_engine/src/datafusion_impl/physical_plan.rs
Some logs about query are verbose and some key logs about opening shard are missing.
Remove verbose logs and add missing key logs.
CI.
> fix: missing and verbose logs

- README-CN.md
- README.md
related https://github.com/apache/incubator-horaedb/issues/1342
Add quick start to `README` to help users experience horaedb better.
Add quick start to `README`.
No need.
> chore: update README

- CONTRIBUTING.md
use available link
use available link
ut
> fix: fix broken link

- README.md
The link about the issue status is broken.
Fix the broken link.
Ensure that the rendered issue status works.
> fix: the broken link about the issue status

- analytic_engine/src/instance/mod.rs
- analytic_engine/src/instance/open.rs
- analytic_engine/src/instance/write.rs
- analytic_engine/src/lib.rs
- analytic_engine/src/table/data.rs
When data wal is disable, data is still encoded, which waste cpu usage.
Skip encode when data wal is disabled.
CI.
> fix: skip wal encoding when data wal is disabled

- Cargo.lock
- Cargo.toml
- df_engine_extensions/src/dist_sql_query/mod.rs
- df_engine_extensions/src/dist_sql_query/physical_plan.rs
- query_engine/src/datafusion_impl/task_context.rs
- server/src/grpc/remote_engine_service/mod.rs
- table_engine/src/remote/model.rs
In #1260, we implemented distributed analyze, but for query that are not analyze, metrics will be returned, which will lead to a decrease in query performance. Therefore, we will fix it in this PR, and metrics will not be returned for normal queries.
- Add is_analyze field to determine whether it is analyze
Existing tests
> refactor: avoid returning metrics in non-analyze sql

- components/logger/src/lib.rs
Refer https://github.com/apache/incubator-horaedb/issues/1319
* Rename `ceresformat` to `logformat`
No need.
> chore: rename ceresformat to logformat

- proxy/src/limiter.rs
- proxy/src/metrics.rs
- proxy/src/read.rs
- query_frontend/src/plan.rs
Query with long time range usually cost too much resources, which affect stable of the whole cluster
- Support block query by query range
Manually
```bash
curl 0:5000/admin/block -H 'content-type: application/json' -d '
{
"operation": "Set",
"write_block_list": [],
"read_block_list": [],
"block_rules": [
{"type": "QueryRange", "content": "24h"}
]
}'
```
> feat: block rules support query

- .github/workflows/ci.yml
- integration_tests/cases/env/cluster/ddl/partition_table.result
- integration_tests/cases/env/cluster/ddl/partition_table.sql
- interpreters/src/table_manipulator/meta_based.rs
- remote_engine_client/src/client.rs
- remote_engine_client/src/lib.rs
- Attach endpoint to remote error
CI
> chore: fix error message

- src/horaedb/bin/horaedb-server.rs
- src/horaedb/src/config.rs
Support setting `meta_addr` and `etcd_addrs` through environment variables.
`meta_addr` => HORAEMETA_SERVER_ADDR
`etcd_addrs` => ETCD_ADDRS
CI & Manual test.
> feat: support setting meta_addr&etcd_addrs by env

- catalog/src/schema.rs
- catalog_impls/src/cluster_based.rs
- catalog_impls/src/lib.rs
- catalog_impls/src/volatile.rs
- cluster/src/cluster_impl.rs
- cluster/src/lib.rs
- cluster/src/shard_set.rs
- meta_client/src/types.rs
- router/src/cluster_based.rs
- src/ceresdb/src/setup.rs
Refer to this issue https://github.com/apache/incubator-horaedb/issues/1386, currently, if the status of the shard is abnormal, we cannot get any valid exception information from the error message `table not found`.
* Add `TableStatus` in `cluster`, you can use it to get the status of the table in the current cluster..
* Add `SchemaWithCluster`, It wraps the schema inside the cluster, through which the state of the cluster and schema can be combined.
Pass CI.
> feat: add table status check

- README-CN.md
- README.md
- docker/docker-compose.yaml
Start horaedb cluster with docker-compose.
Support docker-compose and update README.
Manual test.
> feat: support docker-compose and update README

- analytic_engine/src/instance/write.rs
- server/src/grpc/remote_engine_service/mod.rs
- Disable seq check when wal is disabled
- Fix request id in remote query.
> chore: skip wal seq check when wal is disabled

- analytic_engine/src/table_options.rs
Make it compatible for old table options.
When `layered_memtable_opts` not found in `TableOptions`, we disable `layered_memtable`.
Test manually.
> fix: compatible for old table options

- .asf.yaml
Sometimes merging a branch with some reviewed PRs into another is necessary, but it is disabled now.
Enable to merge some branch to another without squashing.
Nothing to test.
> chore: enable merge on github

- Cargo.lock
- query_frontend/src/logical_optimizer/type_conversion.rs
- server/Cargo.toml
- server/src/postgresql/handler.rs
pgwire author here. This patch updates pgwire to 0.19 which contains compatibility fixes and API improvements.
Pass CI
> feat: update pgwire to 0.19

- Cargo.lock
- Cargo.toml
- components/system_stats/Cargo.toml
- components/system_stats/src/lib.rs
Part of #1438. The preparations for reporting system statistics.
- Add a new component called `system_stats` to helps collect system statistics.
- Introduce a dependency [`sysinfo`](https://crates.io/crates/sysinfo).
Add a new unit test.
> feat: add system_stats lib to collect system stats

- README.md
The old links is invalid.
Influxdb_iox repo change into influxdb main branch. So I modified the links.
no need test.
> chore(docs): fix invalid repo links

- src/components/system_stats/src/lib.rs
Only the total cpu usage is implicit if the numbers of cpus are different across the cluster nodes.
Introduce the `num_cpus` in the system stats, and adjust the average cpu_usage to the sum of all the cpus' usage, whose range is `[0.0, num_cpus]`.
Add a new check to ensure the `cpu_usage`'s range to to be `[0.0, num_cpus]`.
> refactor: adjust cpu's stats

- Cargo.lock
- src/catalog/Cargo.toml
- src/catalog/src/consts.rs
- src/catalog_impls/src/table_based.rs
- src/catalog_impls/src/volatile.rs
- src/query_frontend/src/planner.rs
- src/query_frontend/src/tests.rs
- src/server/src/server.rs
- src/server/src/session.rs
When rename ceresdb to horaedb, there are some breaking changes.
In order to allow old version to upgrade to main branch, some changes are required.
- Make default catalog configurable via env vars,
Manually.
Before upgrade, first setup required envs
```bash
export HORAEDB_DEFAULT_CATALOG=ceresdb
``` 
Etcd's root should be configured both in horaedb and horaemeta
For horaedb
```
[cluster_deployment.etcd_client]
server_addrs = ['127.0.0.1:2379']
root_path = "/rootPath"
```
For horaemeta
```
storage-root-path = "/rootPath"
```
Then 
1. Upgrade horaemeta, then horaedb will throw following errors, which is expected
```
2024-01-23 14:37:57.726 ERRO [src/cluster/src/cluster_impl.rs:136] Send heartbeat to meta failed, err:Failed to send heartbeat, cluster:defaultCluster, err:status: …
```
> fix: changes required for migrate dev to main

- src/analytic_engine/src/sst/parquet/async_reader.rs
- src/analytic_engine/src/sst/parquet/meta_data/filter.rs
- src/analytic_engine/src/sst/parquet/meta_data/mod.rs
- src/analytic_engine/src/sst/parquet/row_group_pruner.rs
- src/analytic_engine/src/sst/parquet/writer.rs
Current filter index won't be created over the primary key columns, and it leads to unexpected low prune rate in some cases.
- Separate the filter module as a sub-module of the meta_data
- Create filter index over the primary key columns except the tsid and timestamp column.
Should pass the CI.
> fix: missing filter index over the primary keys

- src/components/system_stats/src/lib.rs
The unit test `test_collect_system_stats` often fails when running on the github ci server.
Remove the check for cpu usages.
Should pass the CI.
> fix: random failure of test_collect_system_stats

- src/analytic_engine/src/engine.rs
- src/analytic_engine/src/instance/write.rs
- src/analytic_engine/src/sst/metrics.rs
- src/analytic_engine/src/sst/parquet/writer.rs
- src/analytic_engine/src/table/data.rs
- src/analytic_engine/src/table/metrics.rs
- src/benchmarks/src/merge_memtable_bench.rs
- src/benchmarks/src/merge_sst_bench.rs
- src/benchmarks/src/sst_bench.rs
- src/benchmarks/src/sst_tools.rs
- src/benchmarks/src/util.rs
- src/table_engine/src/engine.rs
- src/tools/src/bin/sst-convert.rs
Close #1438.
Support report statistics on shard level.
New unit tests is added and the CI should pass.
> feat: support collect statistics about the engine

- .github/workflows/check.yml
- .github/workflows/ci.yml
- .github/workflows/docker-build-image.yml
horaemeta and horaedb ci names are too close to identify.
rename meta's ci name
UT
> chore: rename ci's prefix name

- .github/workflows/ci.yml
- Cargo.toml
- src/benchmarks/bench.toml
- src/benchmarks/config/bench.toml
- src/benchmarks/src/config.rs
- src/benchmarks/src/merge_sst_bench.rs
- src/benchmarks/src/util.rs
- src/df_engine_extensions/Cargo.toml
- src/horaedb/Cargo.toml
- src/meta_client/Cargo.toml
- src/wal/Cargo.toml
Add sst level configuration for the benchmark test.
Add sst level configuration for the benchmark test.
Manual test
> feat: add sst level config for benchmark

- .github/workflows/ci.yml
- Makefile
- scripts/free-disk-space.sh
CI fails due to no space...
```
Error: No space left on device : '/home/runner/runners/2.313.0/_diag/pages/e678fbe3-017c-41da-8bca-a6d70099419c_0ce2596c-30e4-5db6-a7ae-10ecfd0107a7_1.log'
```
- https://github.com/apache/incubator-horaedb/actions/runs/7974416510/job/21770259595
Refer https://github.com/orgs/community/discussions/25678
CI
> chore: free disk for ci

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- integration_tests/cases/env/local/ddl/query-plan.result
- integration_tests/cases/env/local/ddl/query-plan.sql
When time column is not in `select`, `extract_time_range` will not find time range of one query
- https://github.com/CeresDB/influxql/pull/16
CI
> fix: bump influxql, fix query priority

- horaemeta/server/cluster/cluster.go
- horaemeta/server/cluster/metadata/cluster_metadata.go
- horaemeta/server/cluster/metadata/cluster_metadata_test.go
- horaemeta/server/coordinator/inspector/node_inspector.go
- horaemeta/server/coordinator/inspector/node_inspector_test.go
- horaemeta/server/coordinator/scheduler/manager/scheduler_manager.go
- horaemeta/server/coordinator/shard_picker_test.go
- horaemeta/server/service/http/api.go
In some extreme scenarios, etcd events may be lost or update failures may occur, which may cause the mapping between nodes and shards to fail to be updated correctly. We need to add a cover-up mechanism to ensure that the mapping relationship is always correct.
* Add `NodeInspector`, it will start when the cluster start, running in he background and detect the status of nodes.
Pass CI.
> feat(horaemeta): add node inspector

- integration_tests/config/horaedb-cluster-0.toml
- integration_tests/config/horaedb-cluster-1.toml
- integration_tests/sdk/rust/src/main.rs
- src/proxy/src/limiter.rs
- src/proxy/src/write.rs
Table blocking is found disable in grpc write path, that is annoying... 
This pr fix it for making us happy when handling the problematic tables in production.
- support table blocking in grpc write path.
- add related its.
CI
> fix: table blacklist not work for write

- Cargo.lock
- integration_tests/Cargo.toml
See https://github.com/CeresDB/sqlness/releases/tag/v0.6.0
CI
> chore: bump sqlness to 0.6.0

- .asf.yaml
Update protected_tags in .asf.yaml.
Temporarily ignore tag protection in order to remove erroneous tags v2.0.0 .
No need.
> chore: update protected_tags in .asf.yaml

- horaemeta/server/cluster/manager.go
Currently, not suppport to delete a partitioned table through HTTP API, as it results in a "shard not found" error.
Since the partition table is not assigned to  a shard, deleting the table metadata directly.
Manual test.
> feat(horaemeta): drop metadata of partition table by http api

- Cargo.lock
- Cargo.toml
- src/analytic_engine/Cargo.toml
- src/analytic_engine/src/error.rs
- src/analytic_engine/src/instance/wal_replayer.rs
- src/analytic_engine/src/lib.rs
- src/analytic_engine/src/memtable/columnar/iter.rs
- src/analytic_engine/src/memtable/columnar/mod.rs
- src/analytic_engine/src/memtable/error.rs
- src/analytic_engine/src/memtable/layered/iter.rs
- src/analytic_engine/src/memtable/layered/mod.rs
- src/analytic_engine/src/memtable/mod.rs
- src/analytic_engine/src/memtable/reversed_iter.rs
- src/analytic_engine/src/memtable/skiplist/iter.rs
- src/analytic_engine/src/memtable/skiplist/mod.rs
- src/components/macros/src/lib.rs
Part of #1513
Replace snafu-based Error to thiserror-based for memtable module.
CI
> refactor: first step to refactor error

- src/horaedb/src/setup.rs
Currently, disable wal in standalone mode will directly cause panic. This behavior is incorrect. Sometimes we also need to disable wal in standalone mode.
* Disable wal in stand-alone mode will not panic and print a log to warn the user.
Pass CI.
> refactor: allow disable wal in standalone mode

- README-CN.md
- README.md
Add dingtalk group for better communication with users in Chinese.
No need.
> chore: add dingtalk

- src/analytic_engine/src/table/data.rs
We just panic but log nothing when found two tables with the same table name, it turns debugging into a disaster...
Log the needed table infos when found two tables with the same table name before panic.
Test maually.
> chore: log more info for debug when tables with same name found

- src/components/object_store/src/disk_cache.rs
- src/components/object_store/src/mem_cache.rs
- src/components/partitioned_lock/src/lib.rs
Extended the `try_new` interface while keeping the old one for compatibility.
* Implemented the `try_new_suggest_cap` method, while changing the old `try_new` method to `try_new_bit_len` to ensure compatibility.
* Modified structs and functions that call old interfaces.
* Added new unit tests
* Passed CI test
> refactor: partitioned_lock's elaboration

- integration_tests/cases/env/local/dml/insert_into_select.result
- integration_tests/cases/env/local/dml/insert_into_select.sql
- src/interpreters/Cargo.toml
- src/interpreters/src/insert.rs
Close #1542 
Do select and insert procedure in stream way.
CI test.
> refactor: insert select to stream mode

- src/server/src/grpc/remote_engine_service/error.rs
Updating an error comment in the code to reflect the correct service name is needed.
No need
> fix(comment): update error documentation comment for remote engine service

- src/analytic_engine/src/instance/engine.rs
- src/analytic_engine/src/manifest/details.rs
- src/analytic_engine/src/manifest/error.rs
- src/analytic_engine/src/manifest/meta_edit.rs
- src/analytic_engine/src/manifest/meta_snapshot.rs
- src/analytic_engine/src/manifest/mod.rs
- src/analytic_engine/src/memtable/key.rs
- src/analytic_engine/src/table_meta_set_impl.rs
#1513 
Replace snafu-based Error to thiserror-based for manifest module.
CI test
> refactor: manifest error code

- src/wal/src/message_queue_impl/wal.rs
Fix the issue of sequence overflow when dropping a table using a message queue as WAL.
close #1543 
Check the maximum value of sequence to prevent overflow.
CI.
> fix: sequence overflow when dropping a table using a message queue as WAL

- Cargo.lock
- integration_tests/Makefile
- src/analytic_engine/Cargo.toml
- src/horaedb/Cargo.toml
- src/horaedb/src/setup.rs
- src/wal/Cargo.toml
- src/wal/src/config.rs
- src/wal/src/lib.rs
- src/wal/src/local_storage_impl/config.rs
- src/wal/src/local_storage_impl/mod.rs
- src/wal/src/local_storage_impl/record_encoding.rs
- src/wal/src/local_storage_impl/segment.rs
- src/wal/src/local_storage_impl/wal_manager.rs
- src/wal/tests/read_write.rs
#1279
1. Added a struct `Segment` responsible for reading and writing segment files, and it records the offset of each record.
2. Add a struct SegmentManager responsible for managing all segments, including:
1.	Reading all segments from the folder upon creation.
2.	Writing only to the segment with the largest ID.
3.	Maintaining a cache where segments not in the cache are closed, while segments in the cache have their files open and are memory-mapped using mmap.
3. Implement the `WalManager` trait.
Unit tests.
> feat: Add a new disk-based WAL implementation for standalone deployment

- Cargo.lock
- Cargo.toml
- Makefile
- src/analytic_engine/src/manifest/details.rs
- src/analytic_engine/src/setup.rs
- src/analytic_engine/src/sst/meta_data/cache.rs
- src/analytic_engine/src/sst/parquet/writer.rs
- src/analytic_engine/src/tests/util.rs
- src/benchmarks/src/merge_memtable_bench.rs
- src/benchmarks/src/merge_sst_bench.rs
- src/benchmarks/src/parquet_bench.rs
- src/benchmarks/src/scan_memtable_bench.rs
- src/benchmarks/src/sst_bench.rs
- src/benchmarks/src/sst_tools.rs
- src/benchmarks/src/util.rs
- src/components/object_store/Cargo.toml
- src/components/object_store/src/aliyun.rs
- src/components/object_store/src/config.rs
- src/components/object_store/src/disk_cache.rs
- src/components/object_store/src/lib.rs
- src/components/object_store/src/local_file.rs
- src/components/object_store/src/mem_cache.rs
- src/components/object_store/src/multi_part.rs
- src/components/object_store/src/prefix.rs
- src/tools/src/bin/sst-convert.rs
- src/tools/src/bin/sst-metadata.rs
- src/wal/Cargo.toml
Use opendal to access the object store, thus unifying the access method of the underlying storage.
- use opendal to access s3/oss/local file
- Existed tests
> feat: use opendal to access  underlying storage

- src/wal/src/local_storage_impl/config.rs
- src/wal/src/local_storage_impl/record_encoding.rs
- src/wal/src/local_storage_impl/segment.rs
- src/wal/src/local_storage_impl/wal_manager.rs
Improving WAL based on local disk.
This is a follow-up task for #1552.
1. Make MAX_FILE_SIZE configurable.
2. Allocate enough space when creating a segment to avoid remapping when appending to the segment.​
3. Add `MultiSegmentLogIterator` to enable cross-segment reading.
4. When writing, if the current segment has insufficient space, create a new segment and write to the new segment.​
Unit test.
> feat: Implementing cross-segment read/write for WAL based on local disk

- CONTRIBUTING.md
- README-CN.md
- README.md
> chore: fix doc links

- Cargo.lock
- src/analytic_engine/src/compaction/scheduler.rs
- src/analytic_engine/src/instance/write.rs
- src/wal/Cargo.toml
- src/wal/src/local_storage_impl/config.rs
- src/wal/src/local_storage_impl/segment.rs
- src/wal/src/local_storage_impl/wal_manager.rs
- src/wal/tests/read_write.rs
Currently the WAL based on the local disk does not support the delete function. This PR implements that functionality.
This is a follow-up task of #1552 and #1556.
1. For each `Segment`, add a hashmap to record the minimum and maximum sequence numbers of all tables within that segment. During `delete` and `write` operations, this hashmap will be updated. During read operations, logs will be filtered based on this hashmap.
2. During the `delete` operation, based on the aforementioned hashmap, if all logs of all tables in a read-only segment (a segment that is not currently being written to) are marked as deleted, the segment file will be physically deleted from the disk.
Unit test, TSBS and running a script locally that repeatedly inserts data, forcibly kills, and restarts the database …
> feat: Implement delete operation for WAL based on local storage

- src/analytic_engine/src/instance/open.rs
- src/analytic_engine/src/lib.rs
- src/analytic_engine/src/manifest/details.rs
- src/analytic_engine/src/table/data.rs
- src/analytic_engine/src/table_meta_set_impl.rs
We introduce the explicit flag to control should we enable layered memtable, but it has some compatibility problem when upgrading from old version.
This pr add an option to support compating the old layered memtable on/off control method.
Add an option to support compating the old layered memtable on/off control method.
Manually.
> fix: support to compat the old layered memtable options

- src/analytic_engine/src/instance/wal_replayer.rs
- src/analytic_engine/src/lib.rs
- src/server/src/http.rs
1. Add replay cost in log
2. Remove verbose http log
3. Recover default to shard based, which is faster in most wal implementation.
> chore: record replay cost in log

- src/analytic_engine/src/instance/wal_replayer.rs
In RegionBased replay, a batch of logs is first scanned from the WAL, and then replayed on various tables using multiple threads. This approach works fine for WALs based on tables, as the logs for each table are clustered together. However, in a WAL based on local disk, the logs for each table may be scattered across different positions within the batch. During multi-threaded replay, it is possible that for a given table, log2 is replayed before log1, resulting in missed logs.
1. Modify `split_log_batch_by_table` function to aggregate all logs for a table together.
2. Modify `tableBatch` struct to change a single range into a `Vec<Range>`.
> fix: logs might be missed during RegionBased replay in the WAL based on local disk

- .asf.yaml
- .github/workflows/ci.yml
- .github/workflows/tsbs.yml
- Cargo.lock
- Cargo.toml
- docs/example-cluster-0.toml
- docs/example-cluster-1.toml
- docs/example-standalone-static-routing.toml
- docs/minimal.toml
- integration_tests/Makefile
- integration_tests/cases/env/cluster/ddl/partition_table.result
- integration_tests/cases/env/cluster/ddl/partition_table.sql
- integration_tests/cases/env/local/ddl/query-plan.result
- integration_tests/config/horaedb-cluster-0.toml
- integration_tests/config/horaedb-cluster-1.toml
- integration_tests/config/shard-based-recovery.toml
- src/horaedb/Cargo.toml
- src/wal/Cargo.toml
- src/wal/src/local_storage_impl/record_encoding.rs
- src/wal/src/local_storage_impl/segment.rs
`length` field is not required in wal record, it's duplicated with value_length.
- Remove length from wal record
- Remove rocksdb-wal from default features
CI and manually do some benchmark with [avalanche](https://github.com/prometheus-community/avalanche)
> fix: remove redundancy length field in wal record

- .github/workflows/check-pr-title.yml
Close #1575 
Update the check-pr-title pattern to include type `test`, `style` and `build`.
No need.
> chore: support type `test`, `build` and `style` in pr title

- .github/release.yml
- .github/workflows/publish-github-release.yml
Add automatic publish github release workflow.
Supports automatic generation of release content and divides pr into the following categories:
* Breaking Changes
* Features
* Refactor
* Fixed
* Docs
* Chore
Manual test.
> chore: add publish-github-release action

- .github/workflows/metric-engine-ci.yml
- horaedb/Cargo.lock
- horaedb/Cargo.toml
- horaedb/Makefile
- horaedb/metric_engine/src/storage.rs
Support sorted record batch of write request by primary key.
- use datafusion to sort record batch
- CI
- Unit tests
> feat: sort record batch of write request

- horaedb/metric_engine/src/lib.rs
- horaedb/metric_engine/src/manifest.rs
- horaedb/metric_engine/src/read.rs
- horaedb/metric_engine/src/sst.rs
- horaedb/metric_engine/src/storage.rs
- horaedb/metric_engine/src/types.rs
- horaedb/pb_types/protos/sst.proto
> feat: init scan implementation for time merge storage

- horaedb/metric_engine/src/storage.rs
- horaedb/metric_engine/src/types.rs
We should custom how parquet write handle its metadata.
> refactor: make writing properties independently

- horaedb/Cargo.lock
- horaedb/Cargo.toml
- horaedb/metric_engine/Cargo.toml
- horaedb/metric_engine/src/lib.rs
- horaedb/metric_engine/src/macros.rs
- horaedb/metric_engine/src/read.rs
- horaedb/metric_engine/src/storage.rs
- horaedb/metric_engine/src/test_util.rs
- horaedb/metric_engine/src/types.rs
Part of Metric Engine.
- Scan SSTs in parallel based on segment
- Sort SST using SortPreservingMergeExec, which is more efficient than SortExec
- Add MergeExec to dedup record batch based on sorted batches, currently only `overwrite` semantics is supported.
Add two new UT.
> feat: add merge stream

- horaedb/Cargo.lock
- horaedb/Cargo.toml
- horaedb/metric_engine/Cargo.toml
- horaedb/metric_engine/src/manifest.rs
- horaedb/metric_engine/src/storage.rs
close #1592 
- support merge manifest ssts background
CI
> feat: support persist manifest efficientlly

- horaedb/Cargo.lock
- horaedb/Cargo.toml
- horaedb/metric_engine/Cargo.toml
- horaedb/metric_engine/src/compaction.rs
- horaedb/metric_engine/src/compaction/mod.rs
- horaedb/metric_engine/src/compaction/picker.rs
- horaedb/metric_engine/src/compaction/scheduler.rs
- horaedb/metric_engine/src/manifest.rs
- horaedb/metric_engine/src/sst.rs
- horaedb/metric_engine/src/storage.rs
- horaedb/metric_engine/src/types.rs
Setup the basic structure for compaction
Old CI, not scheduler has no tests now.
> feat: init compact scheduler

- horaedb/Cargo.lock
- horaedb/Cargo.toml
- horaedb/metric_engine/Cargo.toml
- horaedb/metric_engine/src/compaction/mod.rs
- horaedb/metric_engine/src/compaction/picker.rs
- horaedb/metric_engine/src/compaction/scheduler.rs
- horaedb/metric_engine/src/sst.rs
- horaedb/metric_engine/src/types.rs
Implement pick_candidate for compaction
UT
> feat: support pick ssts in compact

- horaedb/Cargo.lock
- horaedb/Cargo.toml
- horaedb/metric_engine/Cargo.toml
- horaedb/metric_engine/src/manifest.rs
Close #1600 
Creating a new data format to represent the manifest snapshot file.
```text
| magic(u32) | version(u8) |  flags(u8) | length(u64) | Record(N) ... |
The Magic field (u32) is used to ensure the validity of the data source.
The Flags field (u8) is reserved for future extensibility, such as enabling compression or supporting additional features.
The length field (u64) represents the total length of the subsequent records and serves as a straightforward method for verifying their integrity. (length = record_length * record_count)
| id(u64) | time_range(i64*2)| size(u32) |  num_rows(u32)|
```
In do_merge, the snapshot data handle is like:
```text
Old data flow in do_merge:
delta_sstmetas
| (extend vec)
V                                
object_store -> org_bytes -> org_pb -> …
```
> feat: another format for manifest

- .github/workflows/ci.yml
- Makefile
- src/metric_engine/src/compaction/executor.rs
- src/metric_engine/src/compaction/picker.rs
- src/metric_engine/src/compaction/runner.rs
- src/metric_engine/src/compaction/scheduler.rs
- src/metric_engine/src/lib.rs
- src/metric_engine/src/manifest.rs
- src/metric_engine/src/manifest/encoding.rs
- src/metric_engine/src/sst.rs
- src/metric_engine/src/storage.rs
- src/metric_engine/src/util.rs
- src/pb_types/protos/sst.proto
When compact finished, we need to delete the old input sst and expired sst.
- The delta file use `ManifestUpdate` struct.
- Refactor compact scheduler, to make it more modular.
CI
> feat: manifest support delete

- src/metric_engine/src/compaction/executor.rs
- src/metric_engine/src/compaction/scheduler.rs
- src/metric_engine/src/manifest/encoding.rs
- src/metric_engine/src/manifest/mod.rs
Followup #1610, to make manifest more modular.
CI
> refactor: move encoding struct into independent file

- Cargo.lock
- docs/example.toml
- src/benchmarks/src/encoding_bench.rs
- src/metric_engine/Cargo.toml
- src/metric_engine/src/compaction/executor.rs
- src/metric_engine/src/compaction/mod.rs
- src/metric_engine/src/compaction/picker.rs
- src/metric_engine/src/compaction/scheduler.rs
- src/metric_engine/src/config.rs
- src/metric_engine/src/lib.rs
- src/metric_engine/src/manifest/encoding.rs
- src/metric_engine/src/manifest/mod.rs
- src/metric_engine/src/read.rs
- src/metric_engine/src/sst.rs
- src/metric_engine/src/storage.rs
- src/metric_engine/src/types.rs
- src/server/Cargo.toml
- src/server/src/config.rs
- src/server/src/main.rs
Fix bugs found in local write bench.
- When manifest starts up, the delta num may overflow since it's initialized to 0.
- When manifest merge_update, since the deltas is unsorted, so we may first delete a non-existing file.
CI
> fix: manifest delta num may overflow

- Cargo.toml
- src/benchmarks/Cargo.toml
- src/common/Cargo.toml
- src/metric_engine/Cargo.toml
- src/metric_engine/src/compaction/executor.rs
- src/metric_engine/src/read.rs
- src/metric_engine/src/storage.rs
- src/pb_types/Cargo.toml
- src/server/Cargo.toml
- Refactor package metadata
- ParquetReader add `keep_sequence` args, and set it to `true`for compaction, `false` for query.
CI
```
cargo publish --dry-run --registry crates-io
```
This commands run successfully.
> feat: skip add sequence column when compact 

- src/metric_engine/src/compaction/scheduler.rs
- src/metric_engine/src/config.rs
- add Clone & PartialEq in config
- use ReadableDuration & ReadableSize
CI
> refactor: add more `macro`  in config

- Cargo.lock
- src/metric_engine/Cargo.toml
- src/metric_engine/src/compaction/executor.rs
- src/metric_engine/src/operator.rs
- src/metric_engine/src/read.rs
- src/metric_engine/src/storage.rs
- src/metric_engine/src/test_util.rs
- src/metric_engine/src/types.rs
In order to maintain compatibility, add a reserved column for future use.
CI
> feat: add reserved column
